blueboxgroup/ursula

roles/keystone/tasks/monitoring.yml
Add sensu monitoring for the shibboleth daemon which
is used with apache for keystone to keystone federation.
=> Add sensu monitoring for shibd

roles/keystone-defaults/defaults/main.yml
This minimal change makes package based installs with Ansible 2.1 work
again. Probably should define this globally across the projects.
=> Define project_name for keystone

envs/example/defaults-2.0.yml, requirements.txt, roles/apt-repos/defaults/main.yml, roles/ceilometer-common/defaults/main.yml, roles/cinder-common/defaults/main.yml, roles/common/tasks/python.yml, roles/heat/defaults/main.yml, roles/heat/tasks/main.yml, roles/keystone-defaults/defaults/main.yml, roles/keystone-setup/tasks/main.yml, roles/neutron-common/defaults/main.yml, roles/nova-common/defaults/main.yml
We get access to os_user, os_keystone_role, and os_user_role now so lets
use them. Also we need to set up the admin user to have admin role on
the default domain, which is a new keystonev3 thing.
=> Use upstream ansible modules for keystone setup

roles/client/defaults/main.yml
We no longer rely on the command line in our automation, and we don't
rely on the libraries as much any more given use of shade. Unpinning
these seems to make the clients work again, including openstackclient,
which wasn't previously working.
Keystone client is pinned under 3.0.0 as the newer one does break a few
things.
=> Unipin (most) clients

roles/neutron-common/defaults/main.yml
Following commit removed neutron-keepalived-state-change and neutron-rootwrap-daemon from neutron alternatives list in error.
1ef4659
They are present in the commit from which this was cherry-picked from (8cf09fc) and are required for neutron.
=> Restore required neutron alternatives

library/sensu_check.py, library/sensu_metrics_check.py, library/sensu_process_check.py
Due to more complicated alert routing required, the checks and alerts
generated need to have tags sent with them (to direct to the correct
recipient).
Dependencies are also useful for silencing an alert based upon the state
of some other specified checkt.
=> library: sensu_*_check modules support tags/deps

roles/keystone-defaults/defaults/main.yml
`_member_` role was not being automatically created by Ansible
=> added _member_ to list of roles created by default

roles/heat/tasks/main.yml
Shade backed modules don't support domains very well, when Keystone has
domain specific configuration enabled, which prevents keystone from
returning all users when doing an API listing.
To work around this, we track when we add the heat admin user, and only
if we add that user do we attempt to use the command line to assign a
role. The os_user_role module cannot work here as it can't find the user
we're trying to manipulate, because it doesn't look in the right domain.
This work around can go away when things like
https://storyboard.openstack.org/?#!/story/2000615 are fixed.
=> Work around shade domain bugs in heat setup

roles/keystone-defaults/defaults/main.yml, roles/keystone/templates/etc/shibboleth/shibboleth2.xml
This adds the option for shibboleth to not verify the certificate
of the keystone idp. This is for testing purposes.
=> Add option to verify k2k idp cert

library/keystone_federation_mapping.py
This fixes an error where the mapping creation request to keystone returns
a formatting error.
=> Load correct federation mapping format

roles/client/defaults/main.yml, test/common
3.0.0 drops the keystone executable and changes some of the python API
in a way that we aren't ready for in the 2.1.x release tree.
=> Pin keystoneclient below 3.0.0

library/keystone_service_provider.py
This fixes a bug where the 'enabled' parameter gets set as type string
instead of type bool. Keystone throws an error saying that 'True' is
an invalid paramter for 'enabled' when creating the service provider.
=> Set the enable type for the service provider module

roles/common/tasks/ntp.yml, roles/common/templates/etc/ntp.conf, roles/common/templates/etc/ntp/cluster.conf
vendor ntp configuration into /etc/ntp.conf;
use ntp servers as configured in vars @ common.ntpd.servers, or use defaults from ubuntu;
integrates ntp peering into single file (removes /etc/ntp/cluster.conf).
=> fix ntp configuration

roles/ceilometer-common/templates/etc/ceilometer/policy.json
Removed extra lines as per community's new Mitaka policy, and removed `cloud_admin` from `context_is_admin`.
=> updated ceilometer policy with mitaka community rules

roles/keystone/templates/etc/shibboleth/shibboleth2.xml
Shibboleth establishes sessions when authenticating the user during
the SAML flow. Memcached will be used to store the sessions
and enable Shibboleth to share sessions on multiple nodes.
This is to fix the bug where a federated user logs in using the Keystone to Keystone SAML ECP flow - the first request goes to controller 1 and then the 2nd request goes to controller 2. Since the sessions are not shared shibboleth does not know what to do with the 2nd request. The k2k auth plugin does not appear to use cookies, so using session stickiness with HAProxy doesn't seem like an option.
**Shibboleth2.xml documentation:** 
https://wiki.shibboleth.net/confluence/display/SHIB2/NativeSPShibbolethXML
**Storage backend documentation:**
https://wiki.shibboleth.net/confluence/display/SHIB2/NativeSPStora …
=> Enable memcached for Shibboleth sp

roles/common/tasks/password-policy.yml
Fix the invalid pam-config
Rebased PR #1903 
Please close #1903 when merged
=> Fix invalid configuration in /etc/pam.d/common-password

roles/horizon/handlers/main.yml
Use become and become_user instead.
There is still a sudo call in swift roles, but that should be addressed in PR #1931 .
=> Avoid sudo in commands

roles/neutron-data-network/tasks/main.yml
1. If l3ha is enabled, install only keepalived since conntrackd is not required.  
2. For upgrade path, if conntrackd is already installed, remove it.
=> Remove conntrackd

envs/example/defaults-2.0.yml, roles/horizon/tasks/main.yml, roles/neutron-common/defaults/main.yml, roles/neutron-common/templates/etc/neutron/neutron.conf, roles/neutron-control/tasks/main.yml, roles/neutron-control/tasks/monitoring.yml, roles/neutron-data-network/handlers/main.yml, roles/neutron-data-network/tasks/main.yml, roles/neutron-data-network/tasks/monitoring.yml
Our internal envs had it listed wrong, so 'smart' was used all the time.
Rename it here so that everything matches up and fits convention.
=> Use "enabled" instead of "enable" for lbaas

roles/ceilometer-common/defaults/main.yml
There may not be a secret defined for mongo, so let it default to
something silly rather than be undefined.
=> Protect against undefined mongodb password

roles/neutron-common/templates/etc/neutron/policy.json
For defects with _member_ owner access to Update/Delete Network, Floating IP, Router Interface and Router Gateway
Also adds cloud_admin access to shared networks
=> reverted to mitaka rules to give owner access

roles/endpoints/defaults/main.yml
tenant_id is deprecated. This should only impact new installs, as there
is no API yet to modify existing endpoints.
=> Use project_id in endpoints instead of tenant_id

roles/horizon/templates/etc/openstack-dashboard/local_settings.py
Adds the ability to configure the list of available KeyStone to KeyStone
service providers at the login screen. The user can select one of
the service providers and then try to login into it using their
keystone identity provider credentials.
=> Add configuration to horizon for K2K federation selection at login time

roles/neutron-common/defaults/main.yml, roles/neutron-common/templates/etc/neutron/plugins/ml2/ml2_plugin.ini
arp_responder default value has changed to false in Mitaka. Restoring arp_responder to true to prevent existing clouds from networking issues when migrating to Mitaka.
=> Restore arp_responder to true for migration to Mitaka

roles/nova-common/templates/etc/nova/nova.conf
VNC consoles were intermittently failing, because we were running multiple nova-consoleauth, and only one would get a token while the other would not. This would lead to token rejections. Using memcache allows these to be kept in sync so either will work.
=> Make VNC great again

roles/nova-common/defaults/main.yml
New version breaks some cases of volume attach.
This can be removed when we switch over to upper constraints.
Change-Id: I179cf0b25a3f2ba8194a376748af15848224572c
=> Pin os-brick version for nova

roles/nova-common/templates/etc/serverspec/nova_spec.rb
The filters baremetal-compute-ipmi.filters and baremetal-deploy-helper.filters have been removed from /etc/nova/rootwrap.d folder. So the check in serverspec has been removed.
=> removed filters from nova serverspec

roles/aodh/defaults/main.yml, roles/aodh/meta/main.yml, roles/ceilometer-common/defaults/main.yml, roles/ceilometer-common/meta/main.yml, roles/cinder-common/defaults/main.yml, roles/cinder-common/meta/main.yml, roles/glance/defaults/main.yml, roles/glance/meta/main.yml, roles/heat/defaults/main.yml, roles/heat/meta/main.yml, roles/horizon/defaults/main.yml, roles/horizon/meta/main.yml, roles/ironic-common/defaults/main.yml, roles/ironic-common/meta/main.yml, roles/keystone-defaults/defaults/main.yml, roles/keystone/meta/main.yml, roles/magnum/defaults/main.yml, roles/magnum/meta/main.yml, roles/neutron-common/defaults/main.yml, roles/neutron-common/meta/main.yml, roles/nova-common/defaults/main.yml, roles/nova-common/meta/main.yml, roles/openstack-source/defaults/main.yml, roles/openstack-source/tasks/main.yml, roles/swift-common/defaults/main.yml, roles/swift-common/meta/main.yml
Each project can specify an upper constraints file to fetch and use to
constrain the deps and project itself.
A project can still opt out of being constrained.
This also has the byproduct of fixing source installs with a pypi mirror
(which was broken), and updating pip inside the virtualenv (which was
really really old).
Change-Id: Idb02f7bb3071f3cab336bf473d1c70ca1a7ede46
=> Support for pip upper constraints

roles/openstack-source/tasks/main.yml
Swift had some language that could not be handled by the setuptools that
gets inserted into the virtualenv, so we need to update it along with
the pip we're already updating.
Change-Id: Ie92b4d1622d6a4ff4b9c7fe9b114f2a821350eb4
=> Update setuptools in project virtualenv

roles/cinder-common/tasks/ceph_integration.yml, roles/glance/tasks/ceph_integration.yml
Also clean up the tasks so that we always use the same path to fetch the
file into, as that path is consistent across install methods.
Change-Id: I63008124ab2276e0b11555680fc5eea8e36a91fb
=> Add a timeout to rdb/rados fetches

roles/common/templates/etc/hosts
Right now the code assumes that there is a 'compute' group. This might
not actaully be the case.
=> Support Swift-only install

site.yml
This reverts commit 724b9d634942cc2f84059b6216f13c333d6ead5c.
We've ran into numerous unexplained instabilities after this change, so
we're reverting it. Will try again at a later time.
=> Revert "Use free strategy where possible (#1986)"

roles/client/defaults/main.yml, upgrade.yml
Clients may be in an odd state, so reset some of them to make sure we
install good sets of them on upgrade.
=> Ensure clients work after upgrade

site.yml
Having this task run on localhost meant that a --limit would limit out
localhost.
Change-Id: I6bd871f554ea5a46e38ed38a77741935d238684e
=> Force fact gathering even when using --limit

plugins/filters/sensu_filters.py, roles/sensu-check/defaults/main.yml
Additional work based on #1959 to more clearly show the criteria used in a sensu check dependency.
=> jinja filter for sensu dependencies

roles/ceilometer-common/handlers/main.yml
Change-Id: Ib23529165f5ad770a78388f6648f5251bfa791ad
=> Fix a ceilometer service typo in a handler

library/keystone_service.py
We're going to work like the upstream module, where we just accept that
we can't change the endpoint with v2.
=> Do not attempt to update endpoint

roles/cinder-common/templates/etc/cinder/policy.json, roles/neutron-common/templates/etc/neutron/policy.json, roles/nova-common/templates/etc/nova/policy.json
The `context_is_admin` rule is checked when allowing access to quota resources. `cloud_admin` requires this access to update quotas. Other API access should not change with this PR, except in Nova where `cloud_admin` is added to the `admin_or_owner` rule.
=> added cloud_admin to context_is_admin for quota access

roles/cinder-common/templates/etc/cinder/policy.json, roles/nova-common/templates/etc/nova/policy.json
`cloud_admin` was unable to see certain buttons in Horizon despite being able to perform actions in the CLI, explicitly adding the role to `admin_or_owner` fixes this issue. 
Some APIs in Cinder require the `is_admin:True` boolean to be checked rather than `role:admin` in order to give proper access. This change effectively reverts the Cinder policy to the community Mitaka policy, with the addition of full admin rights to `cloud_admin`.
=> fixed errors with cloud/admin access

roles/percona-server/tasks/main.yml
The mysql.err file is not getting created till later in the run. Thus the file permissions were not getting set correctly on a new deployment. Moved this to later in the run so that mysql.err file is created.
=> Move the file permission update for mysql.err to later in the task

roles/swift-common/tasks/main.yml
We were trying to download swiftool file to a directory that didn't
exist, so just toss it in /opt/stack instead.
Change-Id: Ie96639e559b9c74dc70fc93b202e8c61c584e480
=> Fix swiftool file install method

roles/openstack-source/tasks/main.yml, roles/swift-common/handlers/main.yml
It looks like there was some duplication applied from this
commit: ed41072a212615019d04734e8508423f6715044c Removing
duplication since it is overriding some functionality and
you can’t duplicate ‘register’, ‘until’ and ‘retries’ keys
in the same task.
=> Remove duplicate Ansible keys

roles/keystone/templates/etc/keystone/policy.json
Same fix as in PR 1982, applied to validate token rules. The project_admin role was previously being blocked by requiring a check to a project_id that didn't exist.
=> fixed project_admin access to token validation

roles/swift-common/tasks/main.yml
The file method doesn't work well with pbr, so install directly from a
pre-built pip as an alternative to just from git.
Change-Id: I5545d253a8ca3dc9d0da53dd559f56111ce54ecc
=> Replace swifttool file method with pip

roles/swift-common/defaults/main.yml, roles/swift-common/tasks/main.yml
We aren't putting swifttool into devpi root, so callout a specific
mirror url for it.
Change-Id: Ia3806815243c85454659cd4b986457d49c0aa672
=> Use specific mirror for swifttool install

roles/common/templates/etc/sensu/stackrc
This reverts commit 15f247b9f352c031a0d381e23edb901522bd59c8.
Revert back to v2 auth until we fix all the sensu checks to work with
v3.
=> Revert "use v3 stackrc file for sensu checks (#2023)"

Vagrantfile, envs/example/defaults-2.0.yml, envs/example/swift/group_vars/all.yml, envs/example/swift/ring_definition.yml, envs/example/swift/vagrant.yml, library/swift_disk.py, plugins/filters/sensu_filters.py, roles/swift-account/tasks/main.yml, roles/swift-container/tasks/main.yml, roles/swift-object/tasks/main.yml, roles/swift-proxy/tasks/main.yml, roles/swift-ring/handlers/main.yml, roles/swift-ring/tasks/main.yml, site.yml, vagrant.yml
Swift was previously using swift-init to manage all of the swift
services. Well it turns out that this leads to some confusion when using
upstart.
To address this, call all of the native binaries in the upstart_services
and reorder when we build the rings. This moves the start/restart
control back into Ansible's hands for now.
Some other small swift updates to make Vagrant great again.
=> Make swift great again

roles/common/templates/monitoring/sensu-sudoers, roles/sensu-check/defaults/main.yml
A sudo key isn't being read by the ansible module or by sensu itself,
the sudo action needs to go on the command itself.
Also, given that some commands are now done without paths, we need to
define the secure path for sensu user for sudo.
Change-Id: I0942b7e44898cff7f1fc575f5bd0f73f9d712ba5
=> Fix sudo needing sensu checks

roles/neutron-common/templates/etc/neutron/policy.json
Neutron policy engine does not like this comment, and as it has no
bearing on functionality, remove it.
=> Remove neutron policy comment

envs/example/ci-ceph_swift/group_vars/all.yml, envs/example/ci-ceph_swift/hosts, playbooks/ci-ceph_swift/tasks/pre-deploy.yml, playbooks/ci-ceph_swift/templates/heat_stack.yml, playbooks/ci-ceph_swift/templates/usr/bin/lshw, playbooks/tests/tasks/main.yml, playbooks/tests/tasks/swift.yml, test/common, test/gen-cert, test/setup
Implement Ursula test with Swift enabled (based on current heat provisioner approach for ursula PR tests and ceph tests). Once the swift deployment and tests are enabled, it can be included in the current nightly ursula test jenkins job which already has ceph enabled since they are sharing the same set of ursula env "envs/example/ci-ceph_swift".
The test cases for swift in this PR are only very basic ones to make sure swift is deployed properly and working well. After the Openstack is deployed with swift, glance will be configured with swift as backend store by default, so that the swift component can also be verified by the general image creation and query actions during the existing ursula tests.
=> Implement Ursula test for Swift

roles/neutron-data-network/files/etc/neutron/lbaas_templates/haproxy.loadbalancer.j2, roles/neutron-data-network/files/etc/neutron/lbaas_templates/haproxy_base.j2, roles/neutron-data-network/files/etc/neutron/lbaas_templates/haproxy_proxies.j2, roles/neutron-data-network/tasks/main.yml, roles/neutron-data-network/templates/etc/neutron/neutron_lbaas.conf
HAProxy defaults to 2000 connections as a global limit. Increase this by
using our own modified configuration templates.
This is a temporary workaround until a more complete solution can be introduced upstream: https://review.openstack.org/#/c/341806/
Ideally we could use the intree haproxy templates, but until this connection limit is address in tree we can specify the configuration option to use our own modified templates.
=> lbaas: increase haproxy global default connection limit

roles/rabbitmq/tasks/main.yml
Latest erlang breaks rabbitmq-server output,
https://github.com/rabbitmq/rabbitmq-management/issues/244
Change-Id: Iad80d55fc549a840e43d73057f3623ce0a8e4868
=> Pin erlang version

roles/rabbitmq/tasks/main.yml
Latest erlang breaks rabbitmq-server output,
https://github.com/rabbitmq/rabbitmq-management/issues/244
Change-Id: Iad80d55fc549a840e43d73057f3623ce0a8e4868
(cherry picked from commit 34d567cb8dfa2e8dc8d578fae8901d01349784fa)
=> Pin erlang version (3.0.x)

roles/nova-common/defaults/main.yml, roles/nova-common/templates/etc/nova/nova.conf
This setting will have the scheduler pic randomly from up to N computes
that pass through the filters. On a busy system or with multiple
schedulers at play this can more evenly distribute the load of instances
across systems.
Leave the setting at 1, the default, which should have no impact. This
will allow us to tune clusters based on needs.
Change-Id: I97fb3eea1b11755c3fbade7910650c7218c482e3
=> Add ability to tune scheduler subset size

upgrade.yml
Some left over repos may break our ability to run apt, which can stall
an upgrade. Just blow away what's there and let Ansible put the repos
back as it needs them.
Change-Id: Id6c145c986ff35eda0cfb1bad9929c8674351073
=> Clean apt repos on upgrades

roles/common/templates/etc/hosts, test/setup
Allow a test to optionally add log forwarding location info to
/etc/hosts.
=> Add log forwarding host info to test envs

upgrade.yml
Some left over repos may break our ability to run apt, which can stall
an upgrade. Just blow away what's there and let Ansible put the repos
back as it needs them.
Change-Id: Id6c145c986ff35eda0cfb1bad9929c8674351073
(cherry picked from commit 8925b327ffc2a36fa0bf67b337b3e30bd5a9d521)
=> Clean apt repos on upgrades (3.0.x)

roles/serverspec/defaults/main.yml
pin rspec gem to keep serverspec gem from installing a newer version of rspec-core.
=> Pin rspec version

library/keystone_service.py, library/neutron_network.py, library/neutron_router.py, library/neutron_router_gateway.py, library/neutron_router_interface.py, roles/heat/tasks/main.yml, roles/keystone-setup/tasks/main.yml
There is no need to put a version in there, modern clients figure it
out. Of course, I had to update a bunch of our modules because they
aren't modern.
=> Use versionless URL for identity endpoint

requirements.txt
With the release of 2.1.1.0 some of our plays are now broken. We need to
explicitly pin to the older working release until we sort this out.
Change-Id: I8ec5c0de22bdb5ae7696ab263b1feaa3e5972290
=> Upgrade ansible version pinning to be explicit

requirements.txt
With the release of 2.1.1.0 some of our plays are now broken. We need to
explicitly pin to the older working release until we sort this out.
Change-Id: I8ec5c0de22bdb5ae7696ab263b1feaa3e5972290
(cherry picked from commit 13067e599db34cb305c4db7d6ed62727b751038a)
=> Upgrade ansible version pinning to be explicit (3.0.x)

roles/common/templates/etc/hosts, test/setup
Using logstash_* Ansible variables allows us to enable logstash
forwarding for Ursula tests by passing them as --extra-vars.
=> Use logstash_* Ansible vars

roles/keystone-setup/tasks/main.yml
The contents of the auth dict get marked as no_log, which apparently
transforms the value of the data returned by os_user_facts. By moving
the 'admin' words out of the auth dict, the correct values come through.
In addition, the attribute where the name is found is "name" not
"username". Finally, it's a fact module so the facts are integrated
directly into the host facts, so we can access them without a register.
Change-Id: I9e28aa566c76372c31e16d4c0c138dc77fc2b146
=> Work around bugs in os_user_facts

roles/keystone-setup/tasks/main.yml
The contents of the auth dict get marked as no_log, which apparently
transforms the value of the data returned by os_user_facts. By moving
the 'admin' words out of the auth dict, the correct values come through.
In addition, the attribute where the name is found is "name" not
"username". Finally, it's a fact module so the facts are integrated
directly into the host facts, so we can access them without a register.
Change-Id: I9e28aa566c76372c31e16d4c0c138dc77fc2b146
(cherry picked from commit f49bf2f12ec1aaf3f9e82e065c2cf679bc065ada)
=> Work around bugs in os_user_facts (3.0.x)

roles/rabbitmq/tasks/main.yml
On systems where erlang is already too new, the apt module needs a force
to downgrade. Limit the force to just erlang as to minimize the scope of
things that could be forced in.
Change-Id: I562fc2c967f463988968a1bd804375744d89395c
=> Force install of older esl-erlang

roles/common/tasks/python.yml
Related to https://review.openstack.org/#/c/351394/
The change this reverts broke how ansible modules work, as all arguments
to ansible modules are being passed into os-client-config, and things
are stomping on each other.
Change-Id: I0b2889c0ff982eb65ac56ec540c8ec7b07e1596b
=> Pin os-client-config

roles/keystone/tasks/main.yml, roles/keystone/tasks/openidc.yml
The openidc tasks were ran anyways if any type of federation was enabled.
This fixes that problem by requiring openidc to be enabled.
=> RELEASE-3.0.X Fix so that openidc does not run when only federation is enabled

roles/heat/tasks/main.yml, roles/keystone-setup/tasks/ldap.yml, roles/keystone-setup/tasks/main.yml
We're masking these problems currently by pinning openstack-client-config, but when we unpin or move to a higher version, we'll want all of these things set correctly to avoid any future attempt at interpreting meaning from an incorrect variable.
=> Fix handling of domain auth details for openstack clients and modules

roles/heat/tasks/main.yml
A user with heat_stack_user role will not be allowed to build heat
stacks. This role shouldn't be added to any real users, it just gets
added when heat adds users.
Change-Id: Icd37784d1bfe8a36a099df151292d95050ac4fc9
=> Do not add heat_stack_user role to admin

roles/keystone-defaults/defaults/main.yml
The keystone-all binary doesn't exist in the latest version of keystone
so linking the alternative fails. The implementation has moved on to
support uwsgi deployment instead so there's no reason to keep it around.
=> Remove keystone-all from alternatives

envs/example/ironic/group_vars/all.yml, roles/openstack-setup/tasks/flavors.yml
On setup, the ability to add baremetal flavors to nova is needed.
This commit adds the usage of the ironic.flavors to iterate over and
install required baremetal flavors when ironic.enabled is True.
Signed-off-by: Philip Marc Schwartz <philip@progmad.com>
=> Add task to install ironic flavors from group_vars

playbooks/tests/tasks/rally/run.sh
Moved the install logic into a function to make the main body of the run
script more readable.  Using 'nova' instead of 'openstack' client until
an issue with network listing with the 'openstack' client is resolved.
=> Updates to Rally run script

envs/example/defaults-2.0.yml
Missed this one Monday for 3.0.1
=> Bump default monitoring tarball for CI and vagrant

roles/client/defaults/main.yml, roles/common/tasks/python.yml
The upstream bug is fixed, and shade will pull in the version it wants.
Change-Id: I8c25a890ff323a74039c546a5643e938cd660de9
=> Remove pin on os-client-config

roles/ipv6ra/tasks/main.yml
When using ipv6ra we don't actually want to use dnsmasq for our local
dns server so make sure it doesn't affect resolvconf if that is
installed.
Without this as soon as dnsmasq is installed everything stops getting
resolved.
Change-Id: I5d3ff13e9b1cbc58fd97caf6f6bbf6fbfa74f545
=> Don't use dnsmasq for local dns

roles/common/tasks/python.yml
The +simple extension is something typically added by devpi, though it
exists on pypi.python.org. For some envrionments like the upstream
openstack pypi mirror and the portbleu mirror we don't have the +simple
path. The +simple path isn't required, if ommited it will correctly
lookup the path and enable the non +simple use case.
=> Don't add +simple to pypi_mirror

roles/neutron-common/templates/etc/neutron/policy.json
This is the first step in granting cloud_admin appropriate role permissions (another update is planned). In neutron, cloud_admin should be able to perform many of the actions admin can, but should not be able to update or delete admin objects.
=> added permissions to cloud_admin role

roles/keystone/tasks/ldap.yml, roles/keystone/tasks/main.yml
Do not merge
Keystone does not currently pick up ldap config until it is restarted after the ursula run
I'm going to test this on pureapp Austin 2; will update when/if it works
=> Added missing keystone restart on ldap config change

ansible.cfg
We're having SSH stability issues, so I wante to see what changing
the transport to standard 'ssh' would do (or how it fails).
=> Extend timeout

envs/example/defaults-2.0.yml, envs/example/mirrors/group_vars/all.yml
The specific path was tied to a specific upstream mirror, which we had
to stop using. The "trusty" url is a generic path that points to
whatever we're currently using for an upstream mirror.
Change-Id: I905cc4eb562113493beea9492456c58250e296cb
=> Use a generic path to ubuntu mirror

roles/client/templates/root/stackrc, roles/common/templates/etc/sensu/stackrc
The root user on our environments was having the nova CLI
version pinned to the v2.0 API which has been deprecated
since the Liberty release of OpenStack. It also meant that
we don't get the latest available microversion support from
our cloud and the installed version of python-novaclient by
default when using the nova CLI.
This removes the OS_COMPUTE_API_VERSION from the root client
role so by default the nova CLI negotiates the latest available
microversion. I've left a comment in the stackrc file for that
role to note that scripts shouldn't rely on that being set or
pinned to a specific version, it's purely for operator
convenience.
The sensu stackrc was also pinning the compute API version to
2 which is the deprecated v2.0 API, and with the latest code
upstream is actually gone. It's …
=> Don't pin OS_COMPUTE_API_VERSION for root client role

envs/example/defaults-2.0.yml, library/ceph_bcache.py, roles/ceph-common/defaults/main.yml, roles/ceph-common/handlers/main.yml, roles/ceph-common/meta/main.yml, roles/ceph-common/tasks/main.yml, roles/ceph-common/tasks/upgrade_flags.yml, roles/ceph-common/templates/etc/ceph/ceph.conf, roles/ceph-monitor/tasks/main.yml, roles/ceph-osd/tasks/bcache.yml, roles/ceph-osd/tasks/main.yml, roles/ceph-update/defaults/main.yml, roles/ceph-update/tasks/ceph_owner.yml, roles/ceph-update/tasks/main.yml, roles/cinder-common/tasks/ceph_integration.yml, roles/cinder-control/tasks/main.yml, roles/cinder-data/tasks/main.yml, roles/glance/tasks/ceph_integration.yml, roles/glance/tasks/main.yml, site.yml
This PR is to support installing ceph jewel, upgrading ceph from hammer to jewel.
Differences between ceph hammer and jewel:
1. ceph jewel run daemons as ceph:ceph user group, while hammer run as root:root. So /var/lib/ceph should be accessed by ceph user in jewel.
2. python-rbd and python-rados have been refactored in jewel. rados.py and rbd.py are replaced with rados.so and rbd.so.
Ceph use a whole disk partition as a journal, but disk partitions are owned by root:disk by default.
To make journal partitions owned by ceph:ceph, we need to change partitions' GUID, so that the udev rules can change partitions' owner in every OS reboot.
After upgrade, all ceph services and cinder services should be restarted.
=> Support ceph jewel installation and upgrading from hammer

roles/nova-common/defaults/main.yml
From openstack/puppet-nova:
In the context of noVNC, numpy adds little performance according
to websockify maintainer: kanaka/websockify#77
By removing python-numpy we remove the Fortran dependency.
=> Do not install python-numpy for VNC proxy

roles/ceph-monitor/tasks/monitoring.yml
These nodes should have enough to query the ceph system to get the
metrics we want displayed.
Change-Id: I1d46b84f431185cf8c0ca16a37837d226ad00ff0
=> Add ceph usage metrics to ceph-monitor

roles/nova-common/defaults/main.yml
This got bumped in cloud_archive for
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2016-5403 but this
doesn't seem to impact us.
Change-Id: I8b8dc4d40957adf25868a7e18ac9a7cc789fafbc
=> Update the version of qemu-kvm

roles/horizon/templates/etc/openstack-dashboard/local_settings.py, roles/keystone/templates/etc/apache2/sites-available/keystone.conf
Oauth has many optional values that can be supported in apache/keystone.conf.
=> optional parameters for oauth configuration for federation

roles/percona-server/tasks/main.yml
This is needed to upgrade our percona to the latest minor release
offered. Installing the package will cause the DB to restart, so we want
to take care that the cluster is in a healthy state before we move on.
Also, becuase this is risky, we want to add an additional run-time flag
of 'dbupgrade' to determine whether or not these tasks run.
Change-Id: I0dbdf21a828325a2dbac08c2c812f97b7f779ec2
=> Add tasks to upgrade percona to latest minor

roles/rabbitmq/tasks/monitoring.yml
The existing check, while it would ignore its own process, was finding
many other processes with "rabbitmq" in the name, like other sensu
checks. This was causing the process count to baloon with false
positives. Narrowing down the process search to "rabbitmq-server"
appears to correctly select just the server processes and avoid the
other sensu processes.
Fixes #2200
Change-Id: I0d2bcdd5a9af7b0fb7dd3ec2569d910d89fcd012
=> Narrow rabbit process check to rabbitmq-server

roles/nova-common/templates/etc/nova/nova.conf
The config path for this changed in one of the last releases and our
setting was being ignored for the upstream default, which disabled live
snapshots. This will make live snapshots happen again.
Change-Id: I973956b77f8b2030f3f9727445cd6def83eb8f91
=> Make snapshots live again

roles/ceph-common/tasks/main.yml, roles/ceph-common/tasks/upgrade_flags.yml
```
- include: upgrade_flags.yml
when: ceph_upgrade_flag_done is undefined
```
The condition will be applied to every task in upgrade_flags.yml,
instead of applying to the single `include upgrade_flags.yml`.
So flag should be set `ceph_upgrade_flag_done` at the end of upgrade_flags.yml,
instead of using an existing variable as flag.
=> fix ceph upgrade_flag.yml condition check

playbooks/adjust-cinder-backend.yml
1. create cinder volume type failed, because cinder service is not started. Fixed it by waiting for 30s for cinder service restarted.
2. `ceph.bcache_ssd_device` is defined as ceph_osds_hybrid group variable, while adjust-cinder-backend.yml is against controller nodes. So `ceph.bcache_ssd_device` is always undefined.
=> fix two defects in adjust-cinder-backend.yml

roles/keystone-defaults/defaults/main.yml
The package 1.8.3 has a bug that is fixed in 1.8.5
1.8.5 fixes parsing of OIDCOAUTHTokenExpiryClaim
=> Updated mod_auth_openidc package version from 1.8.3 to 1.8.5

roles/ceph-update/defaults/main.yml
There is the same variable in roles/ceph-common/defalt/main.yml
but deploy result shows that it can't be accessed in ceph-update
this patch is to add this variable for ceph-updpate
=> set ceph.journal_guid for ceph-update role

roles/apt-repos/tasks/main.yml
Some repo urls may have passwords in them, so we do not want to log
those anywhere.
This also cleans up some of the task formatting for readability.
Change-Id: I1b6e5018e83310f960aac942710c5edd6a40c9c9
=> Do not log repo urls

roles/common/tasks/networking.yml
sack=1 is configured in common role(networking.yml)
If task in common role fails, it may case that sack=1 is configured in sysctl config file, while it's not applied in OS. Because it can't trigger the apply sysctl handler.
Re-run will not be able to trigger apply sysctl, because sysctl configure files will not change in re-run, then sack=1 will never be applied until reboot or do sysctl -p manually.
As too many tasks are in common role, the failure probability of common
role is relative high. This patch is to make apply-sysctl triggered in every deployment.
=> always trigger apply-sysctl in case failure in common role

upgrade.yml
This playbook won't be used until we move to Newton, but I wanted to
remove this FIXME now that we're past 3.0.x and on to 3.1.x. There is no
path from 2.x to 3.1.x so there is no need for this code any more.
Change-Id: Ief5d9cb27e9d59c7b62bf83170833f67aabbc061
=> Remove a FIXME from upgrade playbook

roles/aodh/tasks/main.yml
Just removing the upstart service file left the service running. We want
to explicitly stop it (if it exists) and THEN remove the upstart file.
Change-Id: I54f3137d444551a742f08617102962fec816b441
=> Stop aodhi-expirer service before removing service

roles/keystone/templates/etc/keystone/policy.json
Added `_member_` access to listing projects and role assignments. This is required for middleware filtering which allows `_member_` to see only the projects he belongs to. The change was necessary for a bug wherein`_member_` was unable to edit himself via the Identity>Users>Edit action button.
Also removed an extraneous rule. The APIs it would have applied to required scope-less access, so `rule:admin_or_cloudadmin or role:project_admin or role:_member_` is used instead.
=> added _member_ permissions to list APIs

roles/ceph-common/tasks/main.yml
As variables set in upgrade_flags.yml are used in other tasks,
so we should make sure these variables are set in upgrade_flags.yml even
when users run deploy with tags.
=This patch is to add related tags to tasks in upgrade_flags.yml, to make sure variables are defined when users run deploy with these tags.
=> add tags for upgrade_flags tasks

roles/preflight-checks/tasks/ceph.yml, roles/preflight-checks/tasks/main.yml, site.yml
We have to make sure ceph HEADLTH_OK before re-run/upgrade,
this patch is to add preflight check for ceph.
For developers, they can set skip_prechecks_all/skip_prechecks_ceph to skip this preflight check for debug stuff.
=> add preflight check

roles/percona-server/tasks/main.yml
We want percona to be upgraded when upgrade=True is passed as well,
simplifying the command argument for operations.
Change-Id: I2601f7497dcd3b2f621c87fba66b3617ef4bdd10
=> Upgrade percona when upgrading cloud

roles/nova-common/defaults/main.yml, roles/nova-data/tasks/libvirt.yml
The newer package version has some issues with libvirt doing any
managedsave actions (suspend). Until we sort that out, downrev qemu back
to the version we were using before.
Change-Id: I8bedadfd24b88afcaa236ea8d587af9c4c20083c
=> Downrev qemu package version

roles/client/defaults/main.yml
stable/mitaka is only tested to work with this version, and we've had
problems with the newer version, so pin it down.
Change-Id: I550dcb9d5c56c50d6a201116b439cf26e7872036
=> Pin neutron client to version in constraints

roles/ceph-osd/tasks/pool_names.yml
the host name used by ceph maybe a substring of host name in inventory file `hosts`.
So use `search` instead of exact match.
=> Fix bug, replace ceph host name exact match with search

roles/neutron-common/templates/etc/neutron/policy.json
The rule `admin_or_network_owner` included the `cloud_admin` role, which was allowing `cloud_admin`s to bypass middleware filtering and edit subnets belonging to the admin project.
=> updated subnet rules to protect admin networks

roles/ceph-osd/tasks/bcache.yml
`activate osds` need uuids of bcaches, but this task is executedimmediately after `mkfs xfs on bcache devices`.
Sometimes it happens that the uuid of the last bcache is not ready when `activate osds`.
This patch is to make sure all uuids of bcaches are ready before `activate osds`
=> fix bug -- make sure all uuids of bcaches exist

roles/common/templates/etc/sensu/stackrc
Use of 2.1 was causing client code to try to sort out microversions and
getting an error. Backing down to 2 for now until we sort this out with
all the client code in a future release sprint.
Change-Id: I0a75d10bc241d2fbef7f319bb29223588d32282d
=> Back down sensu to NOVA api 2

roles/ceph-monitor/tasks/monitoring.yml, roles/common/templates/monitoring/sensu-sudoers
give sensu ability to sudo to ceph in order to read ceph keyring file, repairing
the metrics-ceph.py check's ability to connect to the cluster
=> fix ceph metrics checks

roles/client/templates/usr/local/bin/migrate_neutron_services
A domain name does not always equal a domain ID (Default vs default).
Let the system sort it out by using the right argument.
Change-Id: I77619303efdfe54dfd2cda0624a17714c51098f3
=> Fix keystone auth in neutron service migration

roles/ceph-monitor/tasks/monitoring.yml, roles/common/templates/monitoring/sensu-sudoers
ceph keyring file /etc/ceph/ceph.client.admin.keyring is owned by root
user(in 3.0.1 or upgrade from 3.0.1) or ceph user in 3.1.0 new installation.
sensu check need to read this keyring file, so we need to run the check with root
permission.
This patch is to make metrics-ceph.py run with root permission.
=> run metrics-ceph.py by root user

plugins/vars/default_vars.py, requirements.txt, roles/ironic-data/meta/main.yml
With 2.1.1.0 there was a code change that broke our default vars plugin.
Our default variables would win over inventory specific group variables.
With guidance from upstream, we're now accessing the existing variables
a different way which appears to retain our ability to not override
group specific variables, only supply defaults.
Change-Id: I11fb684785730ff275390a866315cc54e12836f8
=> [WIP] Fix ansible 2.1.1+ variable plugin issue

roles/horizon/templates/etc/openstack-dashboard/local_settings.py
- Remove TEMPLATE_DEBUG, now tied to DEBUG.
- Remove default subnet pool lables. Deprecated.
Change-Id: I86a8c0c5dec857ced10950df51cfcb9f2763a6ca
=> Update horizon role for Newton

roles/cinder-common/tasks/main.yml, roles/cinder-common/templates/etc/cinder/api-paste.ini, roles/cinder-common/templates/etc/cinder/cinder.conf, roles/cinder-common/templates/etc/cinder/policy.json, roles/nova-common/tasks/main.yml, roles/nova-common/templates/etc/nova/nova.conf
- Use a shared lock path for cinder/nova to avoid race conditions with
os-brick usage.
- Change the sizelimit middleware
- Move cors settings out of paste and into config
- Update policy from upstream
Change-Id: I473eb25c9a9893ca119f4dd916dba3854eb39655
=> Update cinder for Newton

roles/neutron-common/defaults/main.yml, roles/neutron-common/templates/etc/neutron/api-paste.ini, roles/neutron-common/templates/etc/neutron/dhcp_agent.ini, roles/neutron-common/templates/etc/neutron/l3_agent.ini, roles/neutron-common/templates/etc/neutron/neutron.conf, roles/neutron-common/templates/etc/neutron/plugins/ml2/ml2_plugin.ini, roles/neutron-common/templates/etc/neutron/policy.json
- Add config for ha keepalived threads (set lower than default of 1/2
cores)
- Set default ml2 overlay ip version to 4, but configurable.
- Remove use_namespaces option, which was removed in Mitaka.
- Update policy from upstream
- Update paste from upstream
Change-Id: I229485ae4d3738ce42d6395eac80369966e5817e
=> Update Neutron for Newton

playbooks/prep-ceph-chown.yml, roles/ceph-update/files/ceph_owner.sh, roles/ceph-update/tasks/ceph_owner.yml
We change owner of files in /var/lib/ceph in ceph-update roles, this is very time consuming when ceph has large mount of data in it.
The bottleneck is the IO, there are so many random read requests when chown.
This patch is to add a new playbook for pre-reading the metadata of files. So that the chown will be much faster.
=> make chown be faster

roles/nova-common/defaults/main.yml
In our 3.0.1 release, qemu versions were not capped, and toward the end
of 3.0.1 installs, a newer qemu build was released. Our 3.1.0 release
was pinned to a previous build, which presented a downgrade scenario. To
resolve this, bump the version we pin to.
Change-Id: I53e6193ee6ec51a96229fee90a57afac358f3a3a
=> Bump qemu version to 1.28

roles/percona-server/tasks/main.yml
Turns out the server requires a version of xtrabackup and it may not
properly express the verison requirement. So we want to upgrade it to
the latest at the same time as the server so the restart works.
Also, this play only runs on one host at a time, no need for run_once
and delegate shenanigans.
Change-Id: I840cc7fd78920f8deb06e59a0b50b04a9979a3cb
=> Upgrade percona-xtrabackup along with server

roles/endpoints/defaults/main.yml, roles/haproxy/templates/etc/haproxy/haproxy_openstack.cfg, roles/percona-server/tasks/main.yml
This is a MVP for mysql behind haproxy, so that openstack services can
proxy through and survive a single node's mysql restart. Before this,
all nodes would point at the internal floating IP and connect to the
mysql process there directly. If mysql was restarted, all connections
would die. With a proxy, they can retry / reconnect to another member of
the cluster.
The backend checking isn't completely robust, there is a FIXME in place,
but this gets us started and testing.
Only OpenStack services (things that consume endpoints.db) are set to
use the proxy.
Change-Id: Ibf066ec4f515ab585a85a8061a16db12b8397cb2
=> [WIP] Add mysql to haproxy

library/ceph_bcache.py, playbooks/tests/tasks/network.yml, roles/ceph-osd/tasks/bcache.yml
We have several osds on each osd node.
For hybrid ceph, we can't run ursula deploy against a single osd.
We have to run against all osds on the node.
So we can't add a failed disk back to hybrid ceph cluster by ursula.
This patch is to support this feature. Also support replacing bad journal disk without destroy the osds.
=> Support adding a failed disk back to Hybrid Ceph Cluster

playbooks/check_compute_services.yml, playbooks/reboot_cluster.yml
- timeouts of 500 seem to work well, 900 takes forever
- add ability to reboot computes in parallel
- check nova services before bouncing computes
- move check_nova_services into an included yml
- add tags so just a group of servers can be restarted
=> improve reboot cluster

doc/vagrant.md
Removed the unnecessary Ansible requirement from the Vagrant
documentation. This line was redundant because Ansible is prerequisite
for Ursula. This line was also confusing because it had listed Ansible
(1.7ish), which was incorrect since the current version of Ursula
requires 2.1.X.
Corrected the spelling of "prerequisites" in the same file.
Signed-off-by: Matt Langbehn <matthew.langbehn@gmail.com>
=> Removed Ansible prereq from doc/vagrant.md

playbooks/tests/tasks/network.yml
Adding retries to the neutron router ping test because the ping test fails intermittently due to timing issue.
=> Fix neutron router ping

roles/common/defaults/main.yml, roles/common/tasks/main.yml
baud rate wasn't able to be set for primary tty port.  this fixes that.
=> set baud rate for main serial port

upgrade.yml
This step was missing, and needed to make each nova process re-evaluate
what internal API level it should be talking with other Nova services.
See step 3 in
http://docs.openstack.org/developer/nova/upgrade.html#rolling-upgrade-process
Change-Id: I56117008d00db2935a940f2c6fd8484c9b53bc0d
=> Send HUP signal to nova processes after upgrade

roles/preflight-checks/meta/main.yml, roles/preflight-checks/tasks/main.yml, roles/preflight-checks/tasks/network.yml, roles/preflight-checks/tasks/neutron.yml, roles/preflight-checks/tasks/subnet.yml
- First draft for neutron preflight checks
- Checks for admin networks and subnets and detects any
discrepancy between openstack-envs neutron networks definition and networks in the stack
=> Add neutron preflight checks

roles/percona-server/tasks/main.yml
Turns out the server requires a version of galera and it may not
properly express the verison requirement. So we want to upgrade it to
the latest at the same time as the server so the restart works.
=> Upgrade percona-xtradb-cluster-galera along with server.

roles/openstack-network/tasks/main.yml
CI tests are failing because ip_forwarding is not enabled for bridge and tap interfaces. This setting is required to forward the packet from bridge device to physical ethernet device (eth0) for external connectivity to work.
=> set ip_forward to 1 for vagrant and CI based testing

roles/neutron-data/tasks/monitoring.yml, roles/neutron-data/templates/check-neutron-l3-routers.sh, roles/sensu-check/defaults/main.yml
I set the interval to 600 seconds as requested.
I also limited this to only run on the first controller.
This is in accordance with: https://github.com/blueboxgroup/ursula-monitoring/pull/119
=> Add Neutron l3 Agent Sensu Check

doc/ironic.md, doc/vagrant.md, playbooks/tests/tasks/swift.yml
Previously, some of the documentation and one task had incorrect
capitalization of "OpenStack" (either as "openstack" or "Openstack" in
cases where "OpenStack" would have been correct). Now, it has been
corrected.
Signed-off-by: Matt Langbehn <matthew.langbehn@gmail.com>
=> Fixed capitalization of OpenStack

library/sensu_check_dict.py
with ucarp_node_only=True, the check will be executed only on ucarp primary node.
default is False, so existing sensu_check_dict function will not be affected.
=> sensu_check_dict to support ucarp primary only

roles/horizon/templates/etc/openstack-dashboard/local_settings.py
Horizon was redirecting to http instead of https for the login page.
=> Fix the typo in local_settings.py for the SECURE_PROXY_SSL_HEADER

envs/example/defaults-2.0.yml
Openstack services were referencing /etc/ssl/certs/ca-certificates.crt which is not created in rhel.
=> cafile location for rhel

envs/example/ci-full-centos/heat_stack.yml
Allow cloud deployment with no floating ips to cloud node when using heat provisioner and ci-full-centos envs.
=> remove fp assignments from heat_stack.yml

roles/preflight-checks/defaults/main.yml, roles/preflight-checks/tasks/ceph.yml, roles/preflight-checks/tasks/main.yml
To upgrade ceph to `jewel`, we must make sure current ceph is at least `hammer`.
=> add precheck of ceph version

roles/keystone/templates/etc/keystone/keystone.conf
Since we changed SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https') in openstack-dashboard it broke verification of trusted dashboard.
=> secure trusted dashboard

roles/preflight-checks/tasks/main.yml
We need to assert os is defined to ensure that the OS is in [ ubuntu, centos, redhat].
Otherwise we shouldn't continue the ursula run.
So, we will not support Debian and Fedora, right?
=> make sure os is defined

roles/preflight-checks/tasks/main.yml, site.yml
Sometimes, developers run ursula with `--skip-tags precheck` for debug.
But there are tasks those never should be skipped in preflight-checks
role. For example, the task for setting variable `os`.
This patch is to move the precheck tag into role, so we will only skip
the tasks we mean to.
=> move tag precheck into preflight-checks role from site.yml

envs/example/ci-full-centos/heat_stack.yml, envs/example/defaults-2.0.yml, roles/nova-data/tasks/main.yml
update MTUs for neutron to fit in < 1500
update heat stack to allow igmp
set ternary operator on nova data ownership ( qemu user need access)
=> updates to make neutron networking work on centos in VMs

envs/example/defaults-2.0.yml, roles/common/tasks/inspec.yml, roles/common/tasks/main.yml, roles/inspec/defaults/main.yml, roles/inspec/meta/main.yml, roles/inspec/tasks/main.yml, roles/inspec/templates/etc/inspec/inspec.yml, roles/repos/defaults/main.yml, roles/sensu-check/defaults/main.yml, site.yml
Inspec is a testinf framework for compliance and policy requirements. It will
replace sererspec eventually. As of now it will test rhel stigs.
=> Inspec support for ubuntu and rhel

envs/example/ci-full-centos/heat_stack.yml
Updated ci-full-centos heat.yml to reference image by it's name instead of uuid.
=> Refer image by name instead of id in ci.

roles/common/defaults/main.yml, roles/common/tasks/monitoring.yml, roles/common/tasks/python.yml, roles/common/templates/etc/sensu/stackrc, roles/haproxy/tasks/monitoring.yml, roles/horizon/tasks/monitoring.yml, roles/rabbitmq/tasks/monitoring.yml
1. install python-dateutil for check-glance-store, since it face import
error for dateutil
2. modify sensu/stackrc for rhel ( simlar to /root/stackrc logic)
3. haproxy server check,  existing args has issue, which cause critical
threshold is not parsed correctly
4. apache process is different for centos and rhel, one is apache,
another is httpd, so related check should be changed.
5. rhel has no process named as rabbitmq-server, so related process
check should be changed too.
6. add sensu plugin path
7. add pciutils package
=> centos related monitoring change

test/common, test/setup
According to Paul/Nikki/Niraj's suggestion, I switched another approach: use parameters for key/etc when calling ursula to create heat stack.
//I deleted playbooks/ci-full-centos/templates/heat_stack.yml, and moved envs/example/ci-full-centos/heat_stack.yml to playbooks/ci-full-centos/templates/, then add {{ ansible_env.testenv_instance_prefix }} into the heat_stack.yml (like ci-full does), now no key exists issue is shown.. (Job #111 and #113 are running concurrently)
=> Add parameters to fix concurrent Centos PR issue

envs/example/ci-full-centos/heat_stack.yml
Instead of using image name use image id to ensure correct image is being used by CI runs.
=> Reference image by id in ci heat template.

roles/logging/defaults/main.yml, roles/logging/tasks/main.yml, roles/logging/templates/etc/rsyslog.d/60-remote-syslog.conf
This allows configuration of rsyslog to forward events
to a remote host.
=> Add Remote rsyslog Forwarding

roles/logging/defaults/main.yml, roles/logging/tasks/main.yml, roles/logging/templates/etc/rsyslog.d/60-remote-syslog.conf
This allows configuration of rsyslog to forward events
to a remote host.
=> Add Remote rsyslog Forwarding for 3.1.x

roles/nova-common/defaults/main.yml
Adjust our defaults to catch-up with Canonical bumping some packages on 1/7/2017 (qemu-kvm, libvirt_bin, and librbd1)
=> bump qemu_kvm, libvirt_bin and librdb1 version.

envs/example/ci-full-centos/group_vars/all.yml, envs/example/ci-full-rhel/group_vars/all.yml
Removing keystone.ldap.enabled from ci envs as it is not applicable to our CI environment.
=> Remove ldap enabled from ci envs.

roles/cinder-control/tasks/monitoring.yml, roles/cinder-data/tasks/monitoring.yml, roles/common/tasks/monitoring.yml, roles/common/templates/monitoring/config.json, roles/glance/tasks/monitoring.yml, roles/heat/tasks/monitoring.yml, roles/monitoring-common/defaults/main.yml, roles/neutron-control/meta/main.yml, roles/neutron-control/tasks/monitoring.yml, roles/neutron-control/templates/check-neutron-l3-routers.sh, roles/neutron-data/tasks/monitoring.yml, roles/nova-control/tasks/monitoring.yml, roles/nova-data/tasks/monitoring.yml, roles/sensu-check/defaults/main.yml
1. as https://github.com/blueboxgroup/ursula-monitoring/pull/120  sam cooper's suggestion,  I move the ruby path from sensu-plugin to sensu user's path.
2.  will add rhel related monitoring change after https://github.com/blueboxgroup/ursula/pull/2363 merged.
-- openstack_install_method == distro, no need to add external sensu repo;
-- openstack_install_method == distro,  use /etc/sysconfig/sensu to replace /etc/default/sensu
-- openstack_install_method == distro, change openstack related service's process monitoring, like nova-api change to openstack-nova-api
=> rhel related monitoring change

roles/common/tasks/python.yml
Higher six version is breaking our python setup for shade. We need to pin it to 1.10.0
=> pin six version to 1.10.0 for shade

envs/example/ci-full-centos/group_vars/all.yml
the bug[1] upstream has been merged so we can go back
to using the upstream upper constraints.
[1] https://review.openstack.org/#/c/424865/
=> revert to using upstream upper constraints

roles/swift-common/tasks/main.yml
https://pypi.python.org/simple/ should still be used for `-i`,
which is needed to install dependencies. 
`--extra-index-url` should point to the swifttool index.
=> Add index-url and extra-index-url for installing swifttool

roles/ceph-common/meta/main.yml, roles/ceph-common/tasks/main.yml, roles/ceph-common/tasks/upgrade_flags.yml, roles/cinder-common/meta/main.yml, roles/cinder-common/tasks/ceph_integration.yml, roles/cinder-control/tasks/main.yml, roles/cinder-data/tasks/main.yml, roles/glance/meta/main.yml, roles/glance/tasks/ceph_integration.yml, roles/glance/tasks/main.yml, roles/nova-data/tasks/monitoring.yml, roles/preflight-checks/tasks/main.yml
We have several topology for cloud deployments i.e converge controller, dedicated controller, with/without ceph. Currently, when ceph is enabled, ceph repo get's configured on controller and compute and ceph pkgs are installed to get ceph client, rbd and rados. This get's installed from bbc ceph repo and thus we end up with librbd1 librados2 version as 10.2.3~bbc1.
On compute nodes, nova-data installs libvirt-bin which bring in rados and other dependencies and this is installed from cloud archive repo which is versioned as 10.2.3-0ubuntu0.16.04.2~cloud0.
This same version pkgs with name differences hosted by 2 repos is causing conflicts.
In this PR, we are ensuring that
no bbc ceph repo configured on controller and compute
install librbd, librados, ceph-common from cloud archive repo …
=> Fix ceph package conflicts on controller and compute nodes.

roles/ceph-common/defaults/main.yml, roles/cinder-common/tasks/ceph_integration.yml, roles/glance/tasks/ceph_integration.yml, roles/preflight-checks/tasks/main.yml
Unbreak update path by removing unwanted ceph pkgs from controller and computes. We have to leverage dpkg -r to remove ceph, ceph-osd, ceph-mon etc without removing other dependencies and they will impact libvirt.
=> Remove unwanted Ceph pkgs from Controller and Compute.

test/run
We need to pass the user now for heat runs so ursula-cli's test_ssh method works.
=> Pass ursula-user param in test/run

roles/cinder-data/tasks/main.yml
The cinder-volume install wasn't working on vagrant centos with source install.
=> Corrected the check for cinder-volume install

roles/nova-common/defaults/main.yml
When using qemu-kvm=1:2.5+dfsg-5ubuntu10.5~cloud0 from cloud archive repo nova server suspend action fails due to apparmor policy for libvirtd. The error message reported is:
Error: Failed to perform requested operation on instance "bbg-abcde-ds0030", the instance has an error status: Please try again later [Error: internal error: unable to execute QEMU command 'migrate': Migration disabled: failed to allocate shared memory]. 
This PR will avoid qemu-kvm version bump to cloudarchive and use one that we know is working and tested.
=> Unbreak nova server suspend operation.

roles/neutron-common/defaults/main.yml, roles/neutron-common/templates/etc/neutron/dhcp_agent.ini
This option forces the metadata proxy process to be created in every DHCP namespace regardless of whether or not it is a routed network, solving the problem that Perry saw in his RHOSP Newton testing.
=> Add force_metadata option to dhcp_agent.ini

roles/ceilometer-common/defaults/main.yml, roles/ceilometer-common/templates/etc/ceilometer/ceilometer.conf
In a larger cloud topology ceilometer rabbitmq queue at times grows quite a bit. This causes our monitoring alerts to go off. Given we only enable ceilometer on a dedicated controllers we are increasing ceilometer collecter workers to 4 from 1.
=> Metering.sample queues grows in a larger environment.

roles/keystone-defaults/defaults/main.yml, roles/keystone/meta/main.yml, roles/neutron-common/defaults/main.yml, roles/neutron-common/meta/main.yml, roles/openstack-distro/defaults/main.yml, roles/openstack-distro/tasks/osp.yml, roles/openstack-source/defaults/main.yml, roles/openstack-source/tasks/main.yml
This adds the ability to install any dependencies which need
to get pip installed after the project gets installed. This
is done for both source and distro install.
=> Add ability to post pip install after project installation

roles/common/tasks/monitoring.yml, roles/common/templates/monitoring/sensu-sudoers, roles/monitoring-common/defaults/main.yml
Changes in monitoring task and sensu-sudoers to enable IPMI sensor check plug-in https://github.com/blueboxgroup/ursula-monitoring/pull/124
When monitoring.ipmi_checks not defined in env, the check will be skipped.
Running ipmitool requires root privilege thus additional entry in sensu-sudoers is required.
=> Support plugin for IPMI sensors checks

roles/cinder-control/tasks/main.yml, roles/glance/tasks/main.yml, roles/heat/tasks/main.yml, roles/horizon/tasks/main.yml, roles/keystone/tasks/main.yml, roles/magnum/tasks/main.yml, roles/neutron-control/tasks/main.yml, roles/nova-control/tasks/main.yml
Currently changes are not made to the active config, so firewalld needs to be restarted in order make the firewall changes.  Adding "immediate: true" removes the need for the service restart.  This also fixes the name of the task in the neutron role.
=> Make firewalld changes effective on active config

roles/ceph-osd/tasks/pool_names.yml
registered variables are always exists even the task is skipped.
So we can't judge if a task is skipped by if registered variable is
defined or not
This patch is to fix the bug in pool_names.yml
=> fix register variables

roles/aodh/tasks/main.yml, roles/ceilometer-control/tasks/main.yml, roles/common/tasks/main.yml, roles/glance/tasks/main.yml, roles/heat/tasks/main.yml, roles/horizon/tasks/main.yml, roles/keystone/tasks/main.yml, roles/magnum/tasks/main.yml, roles/nova-control/tasks/novnc.yml, roles/swift-proxy/tasks/main.yml
Merged tags `ufw`,`firewall`,`firewalld` into a universal `firewall`.
Cleaning up extra whitespace is just a side-effect perk of Atom.
=> Settle on common tag firewall instead of ufw and firewalld.

library/ceph_bcache.py, roles/ceph-osd/tasks/bcache.yml
Changes:
1. bcache_index to support values more than 9
2. When a partition is created on nvme device it has an extra character, 'p' in it. This code change is to account for the extra character.
Please DONOT merge this into Master. Will submit a separate PR for master.
=> Ceph NVMe support

envs/example/allinone-centos/group_vars/all.yml, envs/example/allinone-rhel/group_vars/all.yml, envs/example/ci-ceph-redhat/group_vars/all.yml, envs/example/ci-full-centos/group_vars/all.yml, envs/example/ci-full-rhel/group_vars/all.yml
Logging is defaulted to False in `envs/example/defaults-2.0.yml`, but I noticed that certain envs had logging enabled in their respective all.yml. Without specifying a `logging.forward.host` value as well in the all.yml, it defaults to `null` which was causing errors starting the service as the template (`roles/logging/templates/etc/filebeat/filebeat.yml`) wasn't being filled in properly.
Three possible solutions here:
1. Disable logging again in all.yml
2. (Current PR) - Set Forward Host to LocalHost (127.0.0.1) in all.yml's to allow service start with only connection refused and test the templating path
3. Implement the `logging.forward.enabled` feature that is currently being unused (maybe only run the filebeat.yml tasks when forward is enabled?)
=> Provide Forwarding LocalHost For All Logging Enabled Envs

envs/example/defaults-2.0.yml, playbooks/run-openstack-ansible-security.yml
This is an initial drop of playbook to enable use of openstack-ansible-security role.
=> Initial drop of playbook for openstack-ansible-security and defaults

roles/common/defaults/main.yml
Adding the following network tools to help developers troubleshoot:
- tcpdump
- traceroute
- net-tools: arp, hostname, ifconfig, ipmaddr, iptunnel, mii-tool, nameif, netstat, plipconfig, rarp, route, slattach
- bind-utils: dig, host, nslookup
=> Add network troubleshoot tools

roles/preflight-checks/tasks/check_items.yml, roles/preflight-checks/tasks/main.yml, site.yml
when we use '--skip-tags precheck' before, ursula will skip all registered variables and all items that need to be prechecked, however, registered variables are very useful and cannot skip them.
changes:
1. move checked items to file ' roles/preflight-checks/tasks/check_items.yml' and tag it 'precheck'.
2. keep all registered variables in file 'roles/preflight-checks/tasks/main.yml'.
=> modifications for skip tag 'precheck'

roles/aodh/defaults/main.yml, roles/aodh/meta/main.yml, roles/ceilometer-common/defaults/main.yml, roles/ceilometer-common/meta/main.yml, roles/cinder-common/defaults/main.yml, roles/cinder-common/meta/main.yml, roles/glance/defaults/main.yml, roles/glance/meta/main.yml, roles/heat/defaults/main.yml, roles/heat/meta/main.yml, roles/horizon/defaults/main.yml, roles/horizon/meta/main.yml, roles/ironic-common/defaults/main.yml, roles/ironic-common/meta/main.yml, roles/keystone-defaults/defaults/main.yml, roles/keystone/meta/main.yml, roles/magnum/defaults/main.yml, roles/magnum/meta/main.yml, roles/neutron-common/defaults/main.yml, roles/neutron-common/meta/main.yml, roles/nova-common/defaults/main.yml, roles/nova-common/meta/main.yml, roles/openstack-distro/defaults/main.yml, roles/openstack-distro/tasks/osp.yml, roles/swift-common/defaults/main.yml, roles/swift-common/meta/main.yml
Openstack distro packages could bring in un-wanted dependent packages when using openstack-{project_name} as package to be installed. This approach work good with our giftwrap as we bundle required supported features in each project giftwrap.
Example: openstack-nova rhosp package will install all the openstack-nova plgs (cell, cert, placement-api, etc).
This PR, enabled openstack-distro to take list of project_packages that will be installed for a given project.
=> Explicitly define distro project packages to be installed.

roles/percona-server/tasks/main.yml
depending how the hostname is set mysql on installation ends up creating anonymous user (empty user and empty password) for host with fqdn and/or shertname. This will cause failure for mysql root user when it tries to connect using password.
=> delete mysql anonymous users.

roles/horizon/templates/etc/openstack-dashboard/local_settings.py
In netwon there are new required setting to be set in horizon local_setting.py for create image panel to show source type.
Our create image from URL is still broken and will be worked under a separate PR.
=> Fix horizon for creating image using file upload method.

envs/example/ci-ceph-redhat/group_vars/all.yml, envs/example/ci-full-rhel/group_vars/all.yml, envs/example/defaults-2.0.yml, roles/heat/defaults/main.yml, roles/heat/meta/main.yml
Enables heat role for post python dependencies hook which will allow deployment of heat plugin extension for distro and source install types.
=> enable heat ucd plugin post_python_dependencies hook.

roles/openstack-network/handlers/main.yml, roles/openstack-network/tasks/main.yml
Ansible firewalld module doesn't allow for masquerade & rich_rule in same task
Consolidated `result.id` when condition to the block level
=> Fix DNS Failure in VM

roles/haproxy/tasks/main.yml, roles/haproxy/templates/usr/lib/tmpfiles.d/haproxy.conf, roles/keystone/tasks/main.yml, roles/keystone/templates/usr/lib/tmpfiles.d/openstack-keystone.conf
On controller reboot, haproxy and uswgi fails to start due to missing directories in /run. This PR will drop-in haproxy.conf and openstack-keystone.conf in /usr/lib/tmpfiles.d that will ensure these folder are created on service start.
In ubuntu we are doing this via our wrapper start scripts.
=> using tmpfiles.d create  /run/haproxy and /run/uswgi on reboot.

library/cinder_volume_type.py
make cinder_volume_type module support `insecure` parameter
=> add parameter 'insecure' for module cinder_volume_type

envs/example/allinone-centos/group_vars/all.yml, envs/example/allinone-rhel/group_vars/all.yml, roles/horizon/tasks/main.yml, roles/horizon/templates/etc/openstack-dashboard/local_settings.py
Put tasks in blocks based on OS/install type wherever possible. Update horizon config to point to correct ca_bundle. 
Verified horizon works on centos/rhel/ubuntu.
=> cleanup horizon role

envs/example/defaults-2.0.yml, roles/common/defaults/main.yml, roles/common/tasks/main.yml, roles/common/tasks/password-policy.yml, roles/common/tasks/remove-default-users.yml, roles/common/tasks/ssh.yml, roles/common/tasks/system-file-permissions.yml, roles/common/templates/etc/ntp.conf, roles/common/templates/etc/security/pwquality.conf, roles/common/templates/etc/sshd_config
Some of the os settings on the RHEL are different than ubuntu. This PR takes those changes into account. In addition it also add some of the security settings that RHEL7 stig requires. Also adds additional default overrides for openstack-ansible-security for stig requirements.
=> compliance changes to handle rhel 7 inspec checks

roles/neutron-data/tasks/main.yml
Upstart creates a new service log for every tap interface, and this cron job cleans those up.  Since we are running systemd on RHEL we do not need this cron job.
=> Add OS condition to interface log cleanup cron job

playbooks/ci-full-rhel/tasks/pre-deploy.yml, test/setup
When running Ursula with ci-full-rhel started from ursula/test/setup, and found that we missed the playbook of ci-full-rhel so that setup is failed. So here I added the playbook of ci-full-rhel referred to ci-full-centos playbook.
Also I modified test/common to fit ci-full-rhel running.
=> Add playbooks for ci-full-rhel

roles/rhn-subscription/tasks/main.yml
Enabling single repo at a time using with_items si adding up significant additional time to ursula run. This PR will join the repo list into a single cmd and enable all the repos at once.
=> enable rhn repos in a single cmd.

roles/horizon/defaults/main.yml, roles/horizon/tasks/main.yml
- install / remove lbaas ui rpm as per flag
- remove _1480_project_loadbalancersv2_panel.py to make sure only one lbaas v2 tab on Horizon
=> enable/disable lbaas ui on horizon as per neutron.lbaas flag

envs/example/defaults-2.0.yml, roles/aodh/defaults/main.yml, roles/ceilometer-common/defaults/main.yml, roles/cinder-common/defaults/main.yml, roles/client/templates/root/stackrc, roles/common/tasks/ssl.yml, roles/common/templates/etc/sensu/stackrc, roles/glance/defaults/main.yml, roles/heat/defaults/main.yml, roles/horizon/templates/etc/openstack-dashboard/local_settings.py, roles/ironic-common/defaults/main.yml, roles/magnum/defaults/main.yml, roles/mongodb-common/defaults/main.yml, roles/neutron-common/defaults/main.yml, roles/nova-common/defaults/main.yml, roles/preflight-checks/tasks/check_items.yml, roles/preflight-checks/tasks/main.yml, roles/swift-proxy/templates/etc/swift/proxy-server.conf
This PR remove duplicate variables (ca_bundle and ssl.cafile) and uses one common variable ssl.cafile that is required to be defined in defaults-2.0.yml. 
Preflight has assertion to ensure ssl.cafile is defined.
This will fix up all our self signed ssl issues.
=> remove duplicate variables for cafile value.

roles/inspec/defaults/main.yml, roles/inspec/tasks/main.yml, roles/inspec/templates/etc/inspec/host-controls/attributes.yml, roles/inspec/templates/etc/inspec/host-controls/controls/controller/openstack-security.rb, roles/inspec/templates/etc/inspec/host-controls/inspec.yml, roles/inspec/templates/etc/inspec/inspec.yml
This adds the feature to download a tar bar of an inspec profile
dependency. The dependency being pulled down are the inspec
openstack security check. A control file called openstack-security.rb
will contain the list of controls to run for a controller node.
=> Add initial inspec checks for the OpenStack services

roles/ceilometer-common/handlers/main.yml
Restarting the ceilometer services on the compute node fails
because some of the services are not present. This ignores that.
=> Add failed_when for restarting ceilometer services

roles/ceph-common/defaults/main.yml, roles/ceph-monitor/tasks/monitoring.yml, roles/common/tasks/monitoring.yml, roles/common/templates/monitoring/sensu-client-path
on sensu-service start, it execute below  in squence :
1. . /etc/default/sensu
2. . /etc/init.d/functions (only on rhel)
3. ./etc/sysconfig/sensu-client (only on rhel)
. /etc/init.d/functions reset the $PATH, which cause PATH in
/etc/default/sensu not work.
so need to setup path in /etc/sysconfig/sensu-client.
=> enable venv path for sensu on rhel

roles/haproxy/defaults/main.yml
We moved the haproxy global/defaults tuning to the haproxy role defaults. This PR is to set timeout connect to 5s in role defaults
=> haproxy default tunning for timeout connect

library/systemd_service.py
To ensure openstack services points to ursula config dirs we are writing override systemd files. Currently these were written to /usr/lib/systemd/system. This PR enforces the systemd override guidelines to write override systemd files to /etc/systemd/system
=> write override systemd service files to /etc/systemd/system.

roles/horizon/defaults/main.yml, roles/keystone-defaults/defaults/main.yml
Heat currently does not support satisfying specify password requirements. We
will relax the requirements for now to only require letters, digits
and be a length of atleast 8.
=> Relax password requirements

roles/inspec/defaults/main.yml, roles/inspec/tasks/main.yml, roles/inspec/templates/etc/inspec/host-controls/controls/controller/openstack-security.rb, roles/inspec/templates/etc/inspec/host-controls/controls/openstack-security.rb
This adds checks for the ownership and modes for the config files of
Apache and the openstack services: cinder, nova, keystone, and neutron.
More checks, including glance, will be added later.
=> Add more inspec checks from openstack security

roles/nova-control/tasks/main.yml
For centos and rhel openstack packages provides the novnc files in /usr/share. This PR will leverage that instead of laying down bbc novnc tarball.
=> fix novnc for rhel and centos.

roles/glance/defaults/main.yml, roles/glance/meta/main.yml, roles/horizon/defaults/main.yml, roles/horizon/templates/etc/openstack-dashboard/local_settings.py
Newton broke remote downloading of images via Horizon, and the required plugin is not being installed on rhel.
This installs the bbchttp plugin on rhel, and re-enables remote downloading of images in Horizon.
*new PR to test CI*
=> fix bbc-openstack-plugins and disable image creation from url in horizon

envs/example/ci-ceph-redhat/heat_stack.yml, envs/example/ci-full-centos/group_vars/all.yml, envs/example/ci-full-centos/heat_stack.yml, envs/example/ci-full-rhel/heat_stack.yml, roles/openstack-source/files/constraints.txt, test/common
Heat templates for centos, rhel and rhel_ceph needed to be adjusted to parameterized AZ so that CI can pass appropriate AZ via --heat-params to ursula run.
=> Fix CI bugs

roles/horizon/templates/etc/openstack-dashboard/local_settings.py, roles/inspec/defaults/main.yml
This adds more inspec horizon checks. To satisfy the checks,
the following have been changed:
1. login page password reveal button has been disabled
2. password required field has been added for admins changing other user's
passwords
=> Add more inspec horizon checks

roles/inspec/tasks/main.yml, roles/inspec/templates/etc/inspec/host-controls/controls/openstack-security.rb
This adds defaults while checking if the host belongs
to the cinder_volume group. This check is failing for inspecs
when cinder_volume is not defined.
=> Add defaults to cinder_volume host check

envs/example/defaults-2.0.yml, roles/common/templates/etc/hosts
Enhance /etc/hosts templates to create entries using hostname_fqdn and hostname_short along with taking difference of operatingsystem into account.
=> adjust /etc/hosts for rhel/centos and ubuntu

roles/neutron-common/templates/usr/local/bin/neutron-reset
changed regex to account for the extra "@if" tag at the end of tap device names. 
Added regex for netns because red hat adds its ID when performing a ip netns list
=> RHOSP and Ubuntu compatible neutron-reset script

playbooks/tests/tasks/network.yml
Met this issue several times in test TASK [neutron router can ping internet] - 
"FAILED - RETRYING: TASK: neutron router can ping internet (1 retries left).
fatal: [controller-0]: FAILED! => {"changed": true, "cmd": "ROUTER_NS=$( ip netns show | grep qrouter- | awk '{print $1}' ); ip netns exec ${ROUTER_NS} ping -c 5 8.8.8.8", "delta": "0:00:00.005319", "end": "2017-02-26 03:10:05.496612", "failed": true, "rc": 1, "start": "2017-02-26 03:10:05.491293", "stderr": "Cannot open network namespace \"ping\": No such file or directory", "stdout": "", "stdout_lines": [], "warnings": []}"
Tested locally, and found that qrouter-*** cannot be found in controller-0 but controller-1, that's because neutron has no this variable "l3ha: enabled: True".
Not sure which test_env will enable this variable, …
=> Add condition for test task - router ping internet

roles/horizon/templates/etc/openstack-dashboard/local_settings.py
The url method fro image creation does not provide an option to get image copied from remote location at image creation time. This PR will hide this option from horizon.
=> Hide image create url method from horizon.

roles/haproxy/templates/etc/haproxy/haproxy_openstack.cfg
We always added cinder endpoint to haproxy even when cinder is disabled. This PR check on cinder.enabled to add the cinder endpoint in haproxy config.
=> add cinder endpoint to haproxy when enabled.

library/systemd_service.py, roles/keystone/tasks/main.yml
The default systemd kill signal is SIGTERM, which will reload uwsgi workers. Uwsgi requires a SIGQUIT be sent to immediately kill the entire uWSGI stack.
=> add sigquit keystone systemd service

roles/common/tasks/main.yml, roles/common/templates/etc/profile.d/ursula-motd.sh
RHEL does not provide the update-motd mechanism that ubuntu provides.
=> Add ursula-motd for rhel

roles/common/tasks/networking.yml
File name for `/etc/sysconfig/network-scripts/route-<interface>` should not have `.cfg` extension
=> Fix multipod route check

roles/rhn-subscription/defaults/main.yml, roles/rhn-subscription/tasks/main.yml
This PR is to address below rhn subscription optimizations:
- Register system only when it is not subscribed to rhn
- dislablae/enabled rhel repos only for new subscription or refresh repo is true
=> avoid rhn re-registration on every ursula run.

roles/keystone/tasks/main.yml, roles/keystone/templates/etc/cron.d/drop-expired-keystone-tokens
The job was not running because the path was wrong. This caused
the token count to go high. This fixes the path and should
only run on the machine that the undercloud floating ip is
assigned to.
=> Fix flush token cron job for RHEL

roles/monitoring-common/defaults/main.yml
this screwed up our dashboards etc,  graphite treats .'s as seperators
and effort is made to ensure host metrics ship without .'s in the scheme.
unfortunately under rhel the FQDN was being used,  this fixes it to use the
newer `hostname_short` variable and if that doesn't exist defaults back to
using `ansible_nodename`.
=> metrics scheme was getting set with .'s on rhel

roles/heat/defaults/main.yml, roles/heat/templates/etc/heat/heat.conf
Convergence engine has many problems, and we'd disable convergence engine by default in Newton.
1) convergence engine won't support ucd plugin. This is confirmed by heat team cores and ucd dev. 
2) bugs to software deployment deletion and load balancers with two listeners.
=> disable convergence engine

roles/logging-config/templates/etc/filebeat/filebeat.d/template.yml, roles/logging/templates/etc/filebeat/filebeat.yml, roles/preflight-checks/tasks/check_items.yml
* updated filebeats config templates to handle the global_fields
* set flag to ensure fields are in root namespace in logs
also fixed a couple of preflight checks so they don't show as changed tasks.
=> filebeats configs were not setting extra fields from log definitions.

roles/endpoints/defaults/main.yml, roles/haproxy/templates/etc/haproxy/haproxy_openstack.cfg
Haproxy healthcheck calls for ceilometer and aodh api causes socket connect reset errors in service journalctl logs. This error is occurring as haproxy health check closes the connection as soon as it fetches the header and on other end ceilometer-api / aodh-api python is trying to write the body and get's the exceptions.
We are switching haproxy healthcheck for ceilometer and aodh to tcp-check for time being.
=> use tcp-check for ceilometer and aodh api healthcheck.

roles/haproxy/defaults/main.yml, roles/haproxy/templates/etc/haproxy/haproxy_openstack.cfg
Our current haproxy setting does not set check interval and rely on haproxy default of 2s. This PR make check interval a tuneable property with default of 2s.
We tested with 5s and we are see'ing more longer disruptions (~6-8 secs) in api calls as service is stopped on other controller. With 2sec disruption is very short and at time no disruption (i.e no 503).
=> make haproxy healthcheck inter tuneable with default to 2s.

test/common
Job names need to be shorter because it becomes the hostname for ci stack nodes. They also need to have more destinct names so we are making the naming convention usula-build number-pr number.
=> Make job names shorter and concise

roles/horizon/defaults/main.yml, roles/keystone-defaults/defaults/main.yml, roles/keystone/templates/etc/keystone/keystone-paste.ini
Heat is having issues creating users with passwords requirements. So
the password complexity feature by Keystone will be disabled to allow
heat to work again. The JellyRoll password validator will
be enabled again.
=> Re-enable JellyRoll Password Complexity

test/common
Heat stacks cant start with numbers so we are gonna add the ursula prefix to all builds so naming is consistent and heat stacks are valid.
=> Add ursula prefix to other build names

roles/preflight-checks/defaults/main.yml, roles/preflight-checks/tasks/ceph.yml, site.yml
To upgrade ceph, we must make sure the current version is at least Jewel.
=> add precheck of ceph version if current version is less than Jewel.

roles/openstack-source/tasks/main.yml
Setup tools version got bumped which moves pyparsing to 2.2.0. This is breaking neutron/lbaas when install from source. 
This PR breaks the venv setup by updating pip to latest, setting up upper contraint facts and then install setuptool latest pointing to contrain file. This will ensure setuptools upgrade will not move up the pyparsing version to 2.2.0 and stick with what is mentioned in contrain file i.e 2.1.10.
=> unbreak source install due to setuptools version bump.

test/common
Creates a unique id no matter what branch we pull down, build id is always in the build parameters that jenkins supplies
=> Add build ids to all heat stacks

roles/neutron-control/tasks/main.yml, roles/neutron-data-network/tasks/main.yml, roles/neutron-data/tasks/main.yml
The neutron-rbac jellyroll calls were failing with ssl cert errors on test environment where we are using self-signed certs. This PR set's the environment in neutron systemd with certs path. It matches up what is already being done for ubuntu stacks.
=> fix neutron-rbac when using self-signed certs.

roles/ceilometer-common/defaults/main.yml, roles/cinder-common/defaults/main.yml, roles/glance/defaults/main.yml, roles/heat/defaults/main.yml, roles/keystone-defaults/defaults/main.yml, roles/nova-common/defaults/main.yml, roles/swift-common/defaults/main.yml
We will deploy the openstack-selinux package on the nodes.
We will still be running in PERMISSIVE mode but this will
reduce the 'denies' that we will be seeing in the logs. Will
allow for easier debugging of the other denies
=> Enable SELinux to run in enforcing mode part 1

roles/swift-common/defaults/main.yml, roles/swift-common/handlers/main.yml
On RHOSP, swifttool is installed at sysytem level as it has dependencies on swift pkgs. This PR add's the condition to no uninstall swifttool ourside of venv when running on rhosp.
=> avoid removing swifttool outside of venv for rhosp.

roles/logging-config/meta/main.yml, roles/logging-config/tasks/main.yml, site.yml
Currently the logging role runs twice per run in site.yml and every time a service role is run (nova,keystone,rabbit,etc). This role only needs to be run once. The logging config role puts each service's filebeat/logstash template in the appropriate directory. This assumes that you have run the logging role once prior to running other roles (it's run before any services in site.yml) You can override the logging.forward_type from envs if you want to use logstash (which is now deprecated). Removing this dep should shorten the ursula run time.
=> remove logging-config dep on logging role

roles/ceph-monitor/tasks/monitoring.yml, roles/common/defaults/main.yml
MOTD requires PyYAML to parse the ursula release config. This PR is adding PyYAML to python system dependencies list in common role.
In addition, removing hard coded references to basevenv and pointing to one common variable we already have defined.
=> ensure PyYAML is installed on all nodes for MOTD.

envs/example/defaults-2.0.yml, roles/rhn-subscription/tasks/main.yml
In our CI runs we seeing random rhn subscription errors so adding retires logic to it. Also, setting arp_responder: false as this will be default in production as well.
=> add retires for rhn subscription and disable arp_responder.

roles/cinder-control/tasks/main.yml, roles/cinder-data/tasks/main.yml, roles/openstack-meta/defaults/main.yml
cinder volume backup fails due to bug in oslo.privsep which is passing --config_dir as list. This bug is fix in oslo.privsep 14.x and up under https://review.openstack.org/#/c/361125/2/oslo_privsep/priv_context.py.
For newton oslo.privsep is pinned to 1.13.1 and that has this bug. Removing --config_dir from systemd fixes cinder backup issue. Given we are using default /etc/cinder as config dir it get's loaded by oslo even if not passed to start up cmd.
=> remove --config_dirs from cinder systemd.

roles/nova-data/tasks/main.yml
During our RHOSP PR CI runs we been intermittently seeing some ci run job failing with temout at starting nova-compute. This PR adds retries logic to nova-compute service started.
=> add re-tries to nova-compute start.

roles/neutron-data/tasks/main.yml
Only neutron-linuxbridge-agent service is needed on compute hosts however, all neutron services are installed. When running `neutron-reset` on compute hosts, these unwanted services will get started.
=> Mask unwanted neutron services for compute hosts

playbooks/tests/tasks/integration.yml, playbooks/tests/tasks/network.yml
our RHOSP CI runs are intermittently failing at nova boot and ping test as router status is down. This PR is providing a temporary hack to skip these tests until we find a fix. We will revert this back once we fix the underlying issue.
=> skip nova boot and ping tests for rhosp.

playbooks/tests/tasks/rally.yml, playbooks/tests/tasks/rally/bbc-cloud-validate-ceph.yml, playbooks/tests/tasks/rally/bbc-cloud-validate.yml, playbooks/tests/tasks/rally/run.sh
Some envs have no ceph nodes so that ceph-related rally cases cannot be run successfully.
=> Split rally cases for different envs

roles/nova-common/defaults/main.yml, roles/nova-common/templates/etc/nova/nova.conf
Right now there is no way to allow set libvirt's cpu_mode without side
effects. In order to preserve the current functionality, add host-model
as the nova default, but allow an operator to override if necessary.
=> Do not hardcode nova cpu_mode

envs/example/defaults-2.0.yml, roles/inspec/defaults/main.yml, roles/inspec/tasks/main.yml, roles/inspec/templates/etc/inspec/host-controls/attributes.yml, roles/inspec/templates/etc/inspec/host-controls/controls/openstack-security.rb, roles/inspec/templates/etc/inspec/host-controls/controls/rhel7-stigs.rb, roles/inspec/templates/etc/inspec/host-controls/inspec.yml
This restructures the Inspec role default variables for profiles to
be a dictionary instead of a list. We then build a list
of needed dependency profile installations by checking if the
dependent profile is enabled. We only install dependency profiles
if needed.
=> Restructure Inspec Defaults to Dictionary

roles/keystone/tasks/main.yml
The keystone expired token flush cron job needs to be deployed on both the controllers. It was getting installed on only one controller as `run_once` was specified. The job itself has logic in it to check if the controller on which it is running has the ucarp and only then runs the token flush. However, since it was deployed on only one controller and when the ucarp failed over, the expired tokens were not getting flushed.
=> deploy the keystone token flush cron job on both controllers

playbooks/tests/tasks/lbaas.yml
1) remove the restriction on ubuntu and support rhel
2) use relative path to support running test from envs/example/ci-full-rhel instead of env/test
=> enable lbaas testing in ci

envs/example/allinone-centos/group_vars/all.yml, envs/example/ci-full-centos/group_vars/all.yml, library/sefcontext.py, roles/common/defaults/main.yml, roles/common/tasks/main.yml, roles/glance/tasks/main.yml, roles/nova-common/tasks/main.yml, roles/nova-data/tasks/main.yml, roles/swift-object/tasks/main.yml
This is part 2 of the SELinux enablement and deals with nova and glance services on the controller and compute nodes. The `permissive` mode is still left in place for now till we get ceph and swift. Once those services have been verified the mode will be changed to `enforcing`. The changes here were tested in the `enforcing` mode
=> enable selinux enforcing mode

roles/openstack-setup/tasks/dispersion.yml
Swift-dispersion-populate does not support custom cafiles. In self signed environments there is no way to get swift-dispersion-populate to run. This hack adds the cafile parameter to the URLlib call within the SimpleClient class. This should be addressed upstream at some point in the future.
=> custom cafile support swift-dispersion

roles/openstack-setup/tasks/dispersion.yml
This fixes a typo for PR:
https://github.com/blueboxgroup/ursula/pull/2606
=> fix typo in conditional for swift dispersion

roles/openstack-setup/tasks/dispersion.yml
Openstack-setup role is run on controller nodes only. We need to limit the fix for swfit-dispersion work in insecure mode when using self-signed cert to swiftnode only.
=> limit swift-disperssion hack for self-signed cert to swiftnodes.

envs/example/ci-ceph-redhat/group_vars/all.yml, envs/example/ci-ceph_swift/group_vars/all.yml, envs/example/ci-full-centos/group_vars/all.yml, envs/example/ci-full-rhel/group_vars/all.yml, envs/example/ci-full/group_vars/all.yml, envs/example/defaults-2.0.yml, playbooks/tests/tasks/integration.yml, playbooks/tests/tasks/main.yml, playbooks/tests/tasks/network.yml
Below changes are made for CI:
- enables L3HA  
- arp_responder=false, l2_population=false
- fix VM ping to take place in controller with active L3-agent
- change ping from router namespace to network namespace
=> enable L3HA and fix  ping tests for CI

envs/example/ci-ceph-swift-rhel/group_vars/all.yml, playbooks/tests/tasks/all.yml
Disable l2pop until is fix or supported in ci envs.
=> disable l2pop for ci-ceph-swift-rhel envs.

roles/preflight-checks/tasks/ceph.yml, roles/preflight-checks/tasks/check_items.yml
ceph version check fails on new osd nodes when  do scale-out, because `ceph --version` fails.
when check ceph cluster, we check on only one node(cpm1). While ceph
version check need to be done on every ceph node. For ceph scale-out,
the check should pass on new osd nodes.
=> separate individual ceph nodes check from ceph cluster check

roles/openstack-source/tasks/main.yml
There is currently a bug that is being investigated in pip/setuptools that we are running into where an existing version of a package is already installed that is different then what is defined in upper_constraints.  Pip trys to uninstall the existing package and replace it with the pinned version in contraints, but fails due to a race condition and then rolls back the install of the correct version:
Output from failed install:  
" Found existing installation: appdirs 1.4.3\n    Uninstalling appdirs-1.4.3:\n      Successfully uninstalled appdirs-1.4.3\n  Rolling back uninstall of appdirs. No such file or directory: '/opt/bbc/openstack-2016.1-mitaka/keystone/lib/python2.7/site-packages/appdirs-1.4.3.dist-info/METADATA'\n"}" 
It seems the 34.x versions of setuptools are currently affected, …
=> pin setuptools in venv

roles/nova-common/defaults/main.yml
libvirt-bin version in cloudarchive repo got bumped in our mirror. This PR is updating nova-common defaults to point to new version.
https://apt-mirror.openstack.blueboxgrid.com/cloud_archive/ubuntu/dists/trusty-updates/mitaka/main/binary-amd64/Packages
=> adjust libvirt-bin version to new version in cloudarchive repo.

roles/ceph-client/tasks/main.yml, roles/nova-common/defaults/main.yml, roles/nova-data/tasks/libvirt.yml
We use ceph 10.2.3, the newest ceph version in redhat repo is 10.2.5
If we don't specify the ceph version, default 10.2.5 is installed.
So we specify ceph version in this patch.
=> fix ceph package dependency

roles/nova-data/tasks/monitoring.yml
nova compute data out of sync is a defect in mitaka version.  Add this check to remind
operator to take action. With this check an operator will be alerted and can correct the situation thus avoiding false vm boot errors (due to nova hypervisor stats out of sync)
=> add nova compute data out of sync check

roles/common/tasks/main.yml, roles/common/templates/etc/profile.d/ursula-motd.sh
…rather than a profile.d script that is run on every shell invocation.
The data is now surrounded by BEGIN/END lines that ansible uses to know what to edit.
The perl script is idempotent.
=> use blockinfile to edit /etc/motd on rhel

roles/openstack-meta/defaults/main.yml
to check the process name correctly. This configuration only used by
monitoring. and swift account installation for rhosp didn't use this
configuration.
=> fix typo error

roles/common/tasks/main.yml
We do not need to install hwraid clients on rhel as our environment comes with storcli installed.
=> skip installing hwraid clients for rhosp.

library/neutron_router_gateway.py, roles/openstack-setup/tasks/networks.yml
The default router gets assigned a random IP from within the subnet allocation pool, not the second IP after gateway IP. This commit allows us to accept an optional input from all.yml to specify the fixed IP.
=> Specify Fixed IPs When Setting Gateway

envs/example/ci-ceph-redhat/heat_stack.yml, envs/example/ci-ceph-swift-rhel/heat_stack.yml, envs/example/ci-ceph-ubuntu/heat_stack.yml, envs/example/ci-full-centos/heat_stack.yml, envs/example/ci-full-ubuntu/heat_stack.yml
Without igmp, multicast is not supported. It means many things don't work, .e.g vxlan, vrrp
In the openstack which deploy on tardis by using VMs, the router on both controller nodes are active, because vrrp is not supported.
We can't get connect to VMs, because vxlan is not supported.
This patch is to add igmp in all envs, it was only in ci-full-centos and ci-full-rhel.
=> allow igmp in template

roles/aodh/meta/main.yml, roles/ceilometer-common/meta/main.yml, roles/glance/meta/main.yml, roles/heat/meta/main.yml, roles/inspec/defaults/main.yml, roles/inspec/templates/etc/inspec/host-controls/attributes.yml, roles/neutron-control/meta/main.yml, roles/neutron-data/meta/main.yml, roles/nova-control/meta/main.yml, roles/nova-data/meta/main.yml
This refactors the openstack checks to be set up in the inspec meta
role for glance, neutron, nova. It also adds additional checks for
aodh, ceilometer, and heat. More checks for glance was also added
and the list of glance configuration files has been added as well.
=> Add more checks from inspec-openstack-security 

roles/inspec/defaults/main.yml, roles/mongodb-common/meta/main.yml, roles/nova-data/meta/main.yml, roles/percona-server/meta/main.yml, roles/rabbitmq/meta/main.yml
Inspec checks from ursula-inspec have been added.
This includes mongodb, kvm, mysql, and rabbitmq.
This depends on https://github.com/blueboxgroup/ursula-inspec/pull/5
This is in conflict and needs to be rebased with https://github.com/blueboxgroup/ursula/pull/2632.
=> Add checks from ursula-inspec

library/keystone_service.py, roles/endpoints/defaults/main.yml
For newton release our nova api endpoints url's should be v2.1 to take advantage of api micro-version 2.1 and up. 
This PR will recreate endpoint if url's are different and up the endpoint definition for nova to use v2.1 in endpoint urls.
The library will skip checking keystone endpoint as it is created outside of the library via keystone-setup role using keystone-manage bootstrap and does not include /v2.0 in url. Also, we cannot delete/create keystone endpoint in library as keystone client used by library depends on this endpoint.
=> update nova endpoint url's to v2.1

roles/neutron-common/templates/usr/local/bin/neutron-restart-all, roles/neutron-common/templates/usr/local/bin/neutron-start-all, roles/neutron-common/templates/usr/local/bin/neutron-stop-all
neutron services start/stop/restart scripts need to use `service <service_name> start|stop|restart` syntax for it to be compatible with Red Hat/CentOS and Ubuntu
=> Fix neutron services scripts

envs/example/defaults-2.0.yml, roles/common/defaults/main.yml, roles/common/templates/etc/sshd_config, roles/inspec/defaults/main.yml
This is the default timeout value for ssh sessions that is set. Matching the inspec check to look for this value otherwise the check will fail.
=> set the default check for ClientAliveInterval to be 1800 sec

roles/inspec/defaults/main.yml, roles/nova-data/tasks/libvirt.yml, roles/nova-data/tasks/main.yml
This sets up libvirt files to be compliant with our inspec checks. This
also drops the check for the secure glance endpoint.
This is similar to the closed PR: https://github.com/blueboxgroup/ursula/pull/2638
I couldn't reopen the previous PR.
=> Update nova files to be compliant with inspecs

roles/common/templates/etc/ntp.conf
Adds the maxpoll parameter to the servers in the ntp.conf
maxpoll value is required to be set to 10, which is also the
default. If not set the STIG check fails
=> fix ntp config to pass the RHEL STIG inspec checks

roles/ceph-client/meta/main.yml
Deployment failed when it could not find handler to restart sensu-client
in ceph-client in the inspec role
=> fix monitoring handler missing in ceph-client

envs/example/allinone-centos/group_vars/all.yml, envs/example/allinone-rhel/group_vars/all.yml, envs/example/allinone/group_vars/all.yml, envs/example/ci-ceph-redhat/group_vars/all.yml, envs/example/ci-ceph-ubuntu/group_vars/all.yml, envs/example/ci-ceph_swift/group_vars/all.yml, envs/example/ci-full-centos/group_vars/all.yml, envs/example/ci-full-rhel/group_vars/all.yml, envs/example/ci-full-ubuntu/group_vars/all.yml, envs/example/ci-full/group_vars/all.yml, envs/example/defaults-2.0.yml
Currently envs/examples/defaults-2.0.yml has inspec set to true. Inspecs is not applicable for ubuntu ci envs. This PR defaults serverspec and inspec to false in defaults-2.0.yml and handles enablement at each ci envs group_vars/all.yml
=> handle inspec/serverspec enablement within each ci envs.

roles/glance/defaults/main.yml, roles/glance/templates/etc/glance/glance-api.conf, roles/glance/templates/etc/glance/policy.json
This change restricts set_locations and delete_locations to admin and cloud_admin. In addition, it allows ability to extend set_locations and delete_locations to all via attribute in all.yml.
For glance member-create to function without 403 get_locations needs to be available to all.
=> enable admin access to glance location apis.

envs/example/ci-full-centos/group_vars/all.yml
As repos of centos doesn't have librbd1-10.2.3, we use specify
librbd1-0.94.5 to be installed.
=> specify librbd version for ci-full-centos

envs/example/defaults-2.0.yml
default ntp servers are configured in [roles/common/defaults/main.yml](https://github.com/blueboxgroup/ursula/blob/master/roles/common/defaults/main.yml#L13), while
[defatuls-2.0.yml](https://github.com/blueboxgroup/ursula/blob/master/envs/example/defaults-2.0.yml#L598) overwrites it with empty value. This causes that no ntp
server is configured. I have seen ceph clock skews because of no ntp
server configured.
This patch is to remove ntp server configuration in defaults.yml
=> remove ntp server configuration in defaults.yml

playbooks/tests/tasks/integration.yml
CI keeps on failing FIP check, adding these health checks to ensure guest instance's health before FIP check.
=> Add CI guest instance health checks

playbooks/rhn_unsubscribe.yml, roles/rhn-subscription/tasks/main.yml
See random rhn subscription/un-subscription error due to rhn timeouts. This PR add re-tries option to unsubscribe as well as up's the re-try count to 5 for subscription.
=> add re-try to rhn unsubscribe.

playbooks/tests/tasks/integration.yml
Neutron Metadata fails intermittently, adding this check to ensure metadata is working
Neutron security group creation also fails intermittently, replacing it with openstack CLI
=> Add CI metadata checks and replace sec group

roles/ceilometer-common/tasks/main.yml
net-snmp is installed via ceilometer dependency on controller and compute nodes. The PR ensure that part of ceilometer role  snmpd.conf is adjust to not allow v1,v2 etc.
=> if we're installing snmp, ensure we're not allowing v1,v2 etc

roles/openstack-source/defaults/main.yml, roles/swift-account/tasks/main.yml, roles/swift-common/tasks/main.yml, roles/swift-object/tasks/main.yml
Met many issues when running ci-ceph_swift.
****************
TASK [swift-common : get swifttool repo] ***************************************
Sunday 26 March 2017  05:23:32 +0000 (0:00:00.525)       1:16:54.396 **********
fatal: [swift-0]: FAILED! => {"changed": false, "failed": true, "msg": "unsupported parameter for module: **virtualenv**"}
fatal: [swift-2]: FAILED! => {"changed": false, "failed": true, "msg": "unsupported parameter for module: virtualenv"}
fatal: [swift-1]: FAILED! => {"changed": false, "failed": true, "msg": "unsupported parameter for module: virtualenv"}
****************
TASK [swift-object : swift-object service scripts] *****************************
2017-03-23 09:55:24,395 p=28817 u=ubuntu |  task path: /home/ubuntu/ursula/roles/swift-object/tasks/main.yml:13 …
=> Fix some issues for ci-ceph_swift

roles/inspec/defaults/main.yml
/dev/kvm is not being set to correct permissions. We will skip this
check for now and will continue investigating.
=> Skip inspec checks for /dev/kvm

upgrade.yml
- borrow from the 3.1.x upgrade.yml, bringing in use of
the upgrade fact and env_vars
- handle the large endpoint differences between 1.2.x and 2.1.x
by removing all services/endpoints
- call haproxy upgrade specifically and earlier so keystone-admin
will be accessible to remaining services
- disable horizon after keystone upgrade so keystone API will work until
the horizon bits get updated
- remove and restore all openstack clients
- don't be concerned w/ percona upgrade (no version change)
- comment out the include of site.yml, operator will do this by hand after upgrade is ran
=> upgrade.yml updated to support 1.2.x clouds upgrading to 2.1.x

test/setup
It seems that the security rules have not been taken effect in CI env.
Have rune the following testing 
1. using heat-stack to create ci vm
2. setup listen on port 4444(for mysql xtrabackup) and port (5672) in controller 0
3.try to connect to port 4444 of controller 0 from controller 1
4.try to connect to port 5672 of controller 0 from compute 0
There are 4 failures in 40 testing.  If adding security group touch, there is no failure.
=> workaround defect 344951 by touch security group before running ursula playbook

roles/ceph-defaults/defaults/main.yml
librbd1 version in cloud archive mirror got bumped to 10.2.6. This PR is adjusting our pinned ceph client version to 10.2.6.
=> adjust to bumped librbd1 version in mirror.

playbooks/tests/tasks/ceph.yml
changes: 
1.    
```
tasks:
-    - name: reboot ceph_osds|ceph_monitor nodes
-      shell: (sleep 5 ; shutdown -r now )& 
```
didn't work for rebooting remote node. 
2. fix [sudo: no tty present and no askpass program specified](https://jenkins.ci.blueboxgrid.com/job/Ursula_Test_Ceph_Swift_Rhosp_Master_Nightly/21/console)
=> fix reboot remote ceph node

roles/inspec/defaults/main.yml
The check looks at the config file for snmp even when the snmp service is not enabled. We do not start snmp so the check is not relevant. Also the check fails even when the relevant lines that it is checking for are commented out.
=> skip check for snmp conf file from rhel7-stig

roles/openstack-source/tasks/main.yml
New setuptools version 34.3.3 was released that is still affected by the bug outlined in this PR:
https://github.com/blueboxgroup/ursula/pull/2616
Blocking setuptools 34.x.x until this is resolved upstream.
=> pin setuptools version

roles/aodh/handlers/main.yml, roles/ceilometer-common/handlers/main.yml, roles/cinder-common/handlers/main.yml, roles/glance/handlers/main.yml, roles/heat/handlers/main.yml, roles/ironic-common/handlers/main.yml, roles/keystone-setup/handlers/main.yml, roles/keystone/handlers/main.yml, roles/magnum/handlers/main.yml, roles/neutron-common/handlers/main.yml, roles/nova-common/handlers/main.yml, roles/swift-common/handlers/main.yml
Under normal conditions, `default('True')` will return true as well as `default('arbitrary string')`, even default('False') will also return true.
[line 28](https://github.com/blueboxgroup/ursula/blob/master/roles/cinder-common/handlers/main.yml#L28)
`when: restart|default('True') and swift.enabled|default('False')`
when swift.enabled is undefined, `swift.enabled|default('False')` will return true. 
The correct writing are shown as follows(I have tested it under ansible 2.1.0.0 and ansible 2.1.3.0):
```
xx.enabled|default('True')|bool
xx.enabled|default('False')|bool
xx.enabled|default(True)
xx.enabled|default(False)
```
In order to simplify, we can use later ones.
=> bug default('True') and default('False') modification

envs/example/defaults-2.0.yml, envs/example/mirrors/group_vars/all.yml, roles/common/meta/main.yml, roles/repos/defaults/main.yml
bbg_ubuntu repo is obsolete repo and this PR removes all the references of it from ursula.
=> remove obsolete bbg_ubuntu repo usage.

test/common
jenkins can't display log in realtime and can't find what is real issue from the following log
https://jenkins.ci.blueboxgrid.com/job/Ursula_Test_Ubuntu_Master_PRs/267/console
make sure that jenkins console can display log in realtime.
=> unbuffer ansible to display ansible console log in realtime

requirements.txt, roles/client/defaults/main.yml, roles/client/tasks/main.yml
novalcient 8.0.0 got released today which is breaking calls to nova security group. To unblock CI this PR is pining novaclient to < 8.0.0.
We will remove this pinning once upstream release fix for novaclient.
calls failing:
openstack security group rule list
=> unbreak ci by pining novaclient.

roles/ceph-common/defaults/main.yml
As the old 10.2.3 had been removed from cloud archive repo, we use higher 10.2.6 instead.
=> configure higher ceph client version

roles/aodh/defaults/main.yml, roles/aodh/meta/main.yml, roles/ceilometer-common/defaults/main.yml, roles/ceilometer-common/meta/main.yml, roles/cinder-common/defaults/main.yml, roles/cinder-common/meta/main.yml, roles/client/defaults/main.yml, roles/client/meta/main.yml, roles/client/tasks/main.yml, roles/glance/defaults/main.yml, roles/glance/meta/main.yml, roles/heat/defaults/main.yml, roles/heat/meta/main.yml, roles/horizon/defaults/main.yml, roles/horizon/meta/main.yml, roles/ironic-common/defaults/main.yml, roles/ironic-common/meta/main.yml, roles/keystone-defaults/defaults/main.yml, roles/keystone/meta/main.yml, roles/magnum/defaults/main.yml, roles/magnum/meta/main.yml, roles/neutron-common/defaults/main.yml, roles/neutron-common/meta/main.yml, roles/nova-common/defaults/main.yml, roles/nova-common/meta/main.yml, roles/openstack-meta/defaults/main.yml, roles/openstack-source/tasks/main.yml, roles/swift-common/defaults/main.yml, roles/swift-common/meta/main.yml
This patch makes following changes:
1. restrain pip package version when installing openstack clients
2. pass variables of the same names with openstack-source, so the passed
variables can overwrite the variable in openstack-source role.
3. define openstack.upper_constaints in defaults-2.0.yml, instead of
defining it every where.
4. use `local_constrain` to decide use openstack upper_constraints.txt or local constraints file. Because `upper_constaints|bool` doesn't work, my test shows that `upper_constaints|bool` is false then upper_constraints='https://raw.githubusercontent.com/openstack/requirements/stable/newton/upper-constraints.txt'
=> update openstack-source role

playbooks/tests/tasks/integration.yml
A lot of jobs fails at waiting for timeout. In this PR, ssh will fail fast if key is not injected into vm.
=> fast fail for ssh

playbooks/tests/tasks/main.yml, playbooks/tests/tasks/workaround_network.yml
Since key injection break more than 50% of CI running. It seems that the issue is caused by HA issue.  key injection issues are caused by interface migration between two controller. I  are several way to solve CI HA issue.
1. find the root of HA issue in CI env. It is under investigation and take more times. Further actions:
- check security group
- check keepalive configuration
- check why gratutious arp send from standby router
2. Workaround injected key issues. 
This PR is targeted to workaround key injection issue. The n this PR, the interface in backup router will be shutdown before integration test running and it will not impact other env except ci envs.
=> workaround key injection issues

roles/keystone-defaults/meta/main.yml
keystone-defaults has references to upper_contraints variable in openstack-meta. this PR adds openstack-meta role dependency to keystone-defaults role.
=> add openstack-meta role dependency to keystone-defaults.

roles/ceilometer-common/tasks/main.yml
On ubuntu/centos (i.e non rhops deploys) ceilometer does not pull in snmpd thus this it's config file is not present. This PR adds check for file present before trying to change it.
=> update snmpd.conf only if present.

envs/example/ci-full-centos/group_vars/all.yml
PR fixes ci-full-centos envs for keystone to use upper_contraints rather than local one.
=> use upper_constriants for centos.

playbooks/tests/tasks/integration.yml
In ansible shell, default will use /bin/sh. /bin/sh will not handle this [[ ]] well.  SO force to use /bin/bash
=> use bash instead sh

playbooks/tests/tasks/all.yml, playbooks/tests/tasks/integration.yml
CI has been having intermittent metadata issue and it's caused by haproxy not started properly. Restart haproxy before CI tests to temporarily fix the issue.
=> Temporary CI metadata/haproxy fix

envs/example/ci-ceph_swift/group_vars/all.yml
CI env ci-ceph_swift had swift fqdn that is not matching the self signed cert wildcard domain. Thi PR updates the swift-fqdn for ci-ceph_swift envs.
=> update swift-fqdn to match the self-signed cert.

roles/openstack-setup/tasks/dispersion.yml
custom cafile support for swift-dispersion using self-signed cert is only needed for distro install. On ubuntu swiftclient works fine swift-dispersion --insecure
This PR add's when condition to restrict "custom cafile support swift-dispersion" to distro install method.
=> avoid custom cafile swift-dispersion support for non-distro.

roles/common/tasks/ntp.yml
Ntpd won't start on boot on RHEL if chronyd is enabled. (https://access.redhat.com/solutions/1315793)
=> ntpd start on boot rhel

roles/haproxy/templates/etc/haproxy/haproxy_openstack.cfg
HTTP Strict Transport Security (HSTS) is an opt-in security enhancement that
is specified by a web application through the use of a special response header.
Once a supported browser receives this header that browser will prevent any
communications from being sent over HTTP to the specified domain and will
instead send all communications over HTTPS. It also prevents HTTPS click
through prompts on browsers.
=> add HTTP Strict Transport Security header to Horizon responses

roles/haproxy/templates/etc/haproxy/haproxy_openstack.cfg
X-XSS-Protection header forces the Cross-Site Scripting filter into Enabled mode,
even if disabled by the user.This filter is built into most recent web
browsers (IE 8+, Chrome 4+), and is usually enabled by default.The X-XSS-Protection
header is a best-practice to help prevent reflected Cross-Site Scripting attacks.
=> add X-XSS-Protection header to horizon requests

roles/apache/tasks/main.yml, roles/apache/templates/httpd.conf
Mask the information shown by apache to end users. This includes
information about modules loaded and the version of apache. This
may make it diffcult for an attacker to exploit any known issues
about a module easily.
Disable the HTTP Trace method.
=> fix minor apache security issues

roles/aodh/tasks/main.yml, roles/ceilometer-control/tasks/main.yml
Adjust upstart for aodh-api and ceilometer-api to pass --port which is a change needed for newton.
In addition, remove passing --config-dir to aodh-api.
=> update upstart for aodh-api and ceilometer-api.

roles/horizon/tasks/main.yml
Changing conditional to ensure local_settings.py is linked properly in package and source installs.
=> link horizon local_settings package installs

test/common, test/setup
Followed the rule like "CI_${JOBSHORTNAME}_$BUILDID_${COMMITSHORTNAME}" to keep prefix unique and avoid mysql server starting failure error with "enametoolong":
1. I got the first character of each word from job name as job shorten name and meanwhile removed UT" since "UT" is common for all jobs name, such as "Ursula_Test_Ceph_Swift_Rhosp_Master_Nightly" --> "CSRMN".
2. I also shorten VMs name like changing CONTROLLER_0_NAME="${testenv_instance_prefix}-controller-0" to CONTROLLER_0_NAME="${testenv_instance_prefix}-ctl0".
=> Unique Job names prefix and shorten VMs' name

roles/ceph-osd/tasks/main.yml, roles/ceph-update/tasks/main.yml, roles/openstack-setup/tasks/main.yml
Make 3 small changes:
1. remove ceph-osd tag in roles/ceph-osd/tasks/main.yml, because there is already ceph-osd tag out of ceph-osd role(in site.yml).
2. squash tasks into a loop to save lines
3. change tag from `ceph` to `cinder` for cinder setup tasks.
=> change tags and squash several tags into a loop

roles/preflight-checks/tasks/main.yml
make ursula_os check covering the case that `ursula_os is undefined`.
Also, I notice that we support defined ursula_os in envs file, e.g group_vars/all.yml
Why should we support this feature?
Ursula always run setup to fetch ansible_distribution, then we set ursula_os according to ansible_distribution. May we meet the case that no ansible_distribution exists?
=> ursula should fail is ursula_os is undefined

playbooks/tests/tasks/rally/run.sh
using bash pipeline to install rally is not stable and replace it by downloading install_rally.sh and install
=> install rally through script file

envs/example/ci-full-centos/group_vars/all.yml, envs/example/ci-full-rhel/group_vars/all.yml, envs/example/ci-full-ubuntu/group_vars/all.yml, envs/example/ci-full/group_vars/all.yml, envs/example/defaults-2.0.yml, roles/cinder-common/defaults/main.yml, roles/cinder-common/tasks/main.yml, roles/cinder-common/templates/etc/cinder/cinder.conf, roles/cinder-data/tasks/ceph_integration.yml, roles/cinder-data/tasks/lvm_integration.yml, roles/cinder-data/tasks/main.yml, roles/cinder-data/tasks/volume_group.yml, roles/openstack-setup/tasks/cinder.yml
Cinder is able to use lvm as backend, not only ceph.
So we can enabled cinder service for ci-full envs.
changes:
1. use kvm as accelerator instead of qemu. Otherwise, volume is not able to be attached to VM
2. move ceph integration from cinder-common to cinder-data
3. create LVM volume-type in `openstack-setupt` if lvm is the backend of cinder
=> enabled cinder without ceph in ci-full envs

roles/ceph-osd/tasks/bcache.yml, roles/ceph-osd/tasks/standard.yml
When run_once comes to `when` condition, ansbile checks run_once first.
For example,
inventory:
```
[ceph_osds_ssd]
ceph1
ceph2
ceph3
[ceph_osds_hybrid]
ceph4
ceph5
ceph6
```
play:
```
- name: run_once test
hosts: group['ceph_osds_ssd']:groups['ceph_osds_hybrid']
tasks
- name: run ssd stuff once
debug: msg='ssd task'
when: "'ceph_osds_ssd' in group_names"
run_once: true
- name: run hybrid stuff once
debug: msg='hybrid task'
when: "'ceph_osds_hybrid' in group_names"
run_once: true
```
The first task will run once as expected. But when it comes to second
task. The first host is `ceph1`, it's skipped because the `when`
condition. ceph2 and ceph3 are skipped as well.
Now it comes to ceph4, ansible checks run_once first, and it finds that
ceph4 is not the first host in play_hosts, it skip …
=> replace run_once

roles/inspec/defaults/main.yml
The repo was changed so this updates the reference.
=> Rename inspec-openstack-security to openstack-baseline

playbooks/tests/tasks/ceph.yml
The following check only guaranttee ssh service in deployer is up. 
```
local_action: wait_for port=22 host="{{ ansible_host | default(inventory_hostname) }}"  search_regex=OpenSSH delay=2 timeout
```
ansible_host= localhost.
should check if cpm01 and osd0 is up
=> fix ceph ssh check

roles/rabbitmq/defaults/main.yml, roles/rabbitmq/tasks/main.yml
Currently we are installing latest rabbitmq-server (3.6.9*) and have esl-erlang pinned at 1:18.3. This is causing memory leak which would crash rabbitmq when performing a rally test 20 concurrent VM's. We start seeing crash around 100 VM.
Moving up esl-erlang to 1:19.3 let's us successfully provision upto 900 VM which is max vm limit for the environment. 
This PR pin's rabbitmq-server and esl-erlang to latest tested version. For RHOSP we always install latest as those are tested by redhat before publishing to their repo.
We will cherry pick this fix to RELEASE-3.1.x branch as well.
=> pin rabbitmq-server and esl-erlang versions.

roles/logging/handlers/main.yml, roles/percona-common/tasks/main.yml, upgrade.yml
Adds support for upgrades from Mitaka -> Newton. 
- Removes mysql user as this is handled by install of mysql package. This gets rid of problems of the mysql user's home directory not matching what's in /etc/passwd (created by install of package). 
- We now have mysql behind haproxy running on port 3307. In order for upgrade to work we must change endpoint to use standard port for db_sync commands to work properly. After all db_sync commands are run we revert the endpoint to use haproxy. 
- Put the logging role ahead of common to ensure filebeat is installed (common deps on filebeat package to be installed when the filebeat logging method is set). 
- Ceph OSD's role is run before cinder as it sets facts that are required by cinder
- Add block to upgrade aodh
=> upgrade changes for newton

roles/rabbitmq/defaults/main.yml, roles/rabbitmq/tasks/main.yml
Currently we are installing latest rabbitmq-server (3.6.9*) and have esl-erlang pinned at 1:18.3. This is causing memory leak which would crash rabbitmq when performing a rally test 20 concurrent VM's. We start seeing crash around 100 VM.
Moving up esl-erlang to 1:19.3 let's us successfully provision upto 900 VM which is max vm limit for the environment.
This PR pin's rabbitmq-server and esl-erlang to latest tested version.
=> backport rabbitmq fix from PR 2743.

roles/rabbitmq/tasks/main.yml
Given we are now pining rabbitmq-server and esl-erlang to a tested version we no longer need special handling of rabbitmq-server version bump for update path.
=> remove obsolete task from rabbitmq role.

playbooks/tests/tasks/rally/run.sh
wget is not installed on centos and redhat, so use curl instead to download rally installation file.
=> Use curl to download rally installation file

roles/cinder-data/tasks/lvm_integration.yml, roles/cinder-data/tasks/main.yml
We need package qemu-utils even when lvm not enabled.
=> move cinder-data package installation out from lvm

roles/ceph-defaults/defaults/main.yml
set rbd_max_clone_depth=0 to implement rbd volume full clone.
With this patch, we support two types of clone. They are full clone and copy-on-write clone.
Full clone:
The path is: source_volume -> target_volume
openstack volume create --source <source_volume> --size <size> <target_volume>
copy-on-write clone:
the path is: source_volume -> snapshot -> target_volume.
openstack snapshot create --name <snap_name> <source_volume>
openstack voluem create --snapshot <snap_name> --size <size> <target_volume>
=> support volume full clone

roles/common/defaults/main.yml, roles/common/templates/monitoring/sensu-sudoers, roles/haproxy/tasks/monitoring.yml, roles/nova-control/tasks/monitoring.yml, roles/nova-data/tasks/monitoring.yml, roles/sensu-check/defaults/main.yml
1. Python-dateutil package missing in base venv
2. Some check need be added into shudders after security hardening
3.  Check-cinder-sessions check should be only installed for ceph
disabled and cinder enabled env
4.  Set explicit auto_resolve attribute for  check_nova_services.
=> Monitoring fix for ubuntu release

roles/haproxy/defaults/main.yml
The purpose is to reduce ‘Aborted Connection’ in mysql.err
=> Increase mysql haproxy timeout

roles/ceph-monitor/tasks/main.yml
for release 3.1.x:
user and group of `/var/log/ceph` is not ceph:ceph. This PR fix that.
chanages:
1. user:group change to ceph:ceph.
2. add o+rx.
=> add o+rx permission to directory /var/log/ceph

envs/example/ci-full-rhel/group_vars/all.yml, playbooks/tests/tasks/controller.yml, requirements.txt, test/setup
Backporting novaclient-pin to < 8.0.0 for CI to able to create security groups.
=> backport novaclient pin to rhosp release branch.

roles/heat/templates/etc/heat/policy.json
By default a user with the `admin` role is not allowed to list stacks that do not belong to the admin project. This causes an issue for operators as they cannot see any stacks that are in other projects.
=> Allow admin users to list stacks from all projects

envs/example/defaults-2.0.yml, roles/openstack-setup/tasks/cinder.yml, roles/openstack-setup/tasks/users.yml
Cinder v2 and v3 endpoints were previously being created even when cinder.enabled=false, creating the need for cinderv2.enabled and cinderv3.enabled.
=> add logic for creating cinder endpoints

roles/keystone-defaults/defaults/main.yml, roles/keystone/tasks/saml.yml, roles/keystone/templates/etc/apache2/sites-available/keystone.conf, roles/keystone/templates/etc/keystone/keystone.conf, roles/keystone/templates/etc/shibboleth/attribute-map.xml, roles/keystone/templates/etc/shibboleth/idp_metadata.xml, roles/keystone/templates/etc/shibboleth/shibboleth2.xml
This PR makes the SAML integration more flexible. This PR allows setting a file source for the identity metadata instead of just using a URL. This also enables the auth signing request when the service provider redirects the user to the identity provider.
=> Get Saml IDP metadata from file

roles/cinder-common/templates/etc/cinder/rootwrap.conf
We missed the venv bin dir in rootwrap.conf for source installation method.
I found this when I tried to create an encrapted volume from image.
It said that no privsep-helper, but in fact privsep-helper is in cinder venv bin dir.
=> add cinder rootwrap search dirs

roles/apache/defaults/main.yml, roles/apache/tasks/main.yml, roles/apache/templates/etc/httpd/conf.modules.d/43-mod_proxy_uwsgi.conf, roles/keystone/tasks/main.yml, roles/keystone/templates/etc/apache2/sites-available/keystone.conf, roles/keystone/templates/etc/keystone/uwsgi/keystone-admin.ini, roles/keystone/templates/etc/keystone/uwsgi/keystone-main.ini
This switches from using http to uwsgi between Apache and Keystone.
If the uwsgi port setting is used, then mod_proxy_uwsgi will be used.
Otherwise if the file socket setting is used, then the uwsgi module will be used.
Both Ubuntu and Redhat will be able to use the port setting, but
only Ubuntu can use the file socket setting. The file socket was
previously broken but now will work on Ubuntu with this change.
=> Use uwsgi between Apache and Keystone

roles/haproxy/templates/etc/haproxy/haproxy_openstack.cfg
The "X-Content-Type-Options" header (with the "nosniff" value set) prevents IE, Mozilla and Chrome based browsers from ignoring the Content-Type header of a response.
This action may prevent untrusted content (e.g. user uploaded content) from being executed on the user browser (after a malicious naming, for example).
So add it in the haproxy config for the Horizon dashboard for all outgoing requests.
=> Add X-Content-Type-Options header

roles/cinder-common/templates/etc/cinder/cinder.conf
This PR preserves default_volume_type for ceph when v7K is to be enabled on a cluster that has ceph enabled.
=> Preserve default_volume_type for ceph.

roles/horizon/defaults/main.yml
Latest neutron-lbaas-dashboard is not compatible with newton release. Leverage version 1.0.0 for Newton.
This PR changes were made based on discussion in https://bugs.launchpad.net/neutron-lbaas-dashboard/+bug/1621403
=> use neutron-lbaas-dashboard version 1.0.0 for newton.

library/ceph_pool.py, roles/ceph-defaults/defaults/main.yml, roles/ceph-monitor/tasks/main.yml, roles/ceph-monitor/templates/etc/bbg-ceph-utils/ceph-utils.conf
ceph wants pg number be power of 2(good for cursh).
So if we increase pg number from 1024, the next number will be 2048.
Increasing so many pg numbers will cause much data rebalancing.
This patch is to increase pg number in small step
=> increase pg number in small step

roles/openstack-source/tasks/main.yml
When using "source" type to install some packages from source, pip would install them on src instead of site-packages. That is different from type of "packages" and "distro" and it would prevent some soft links from working. The PR is to sync the installation location to site-packages.
=> disable development mode of pip

roles/cinder-common/meta/main.yml, roles/cinder-common/templates/etc/cinder/cinder.conf, roles/cinder-control/tasks/v7k_integration.yml, roles/cinder-control/templates/etc/v7k/ssh/cinder/id_rsa, roles/cinder-control/templates/etc/v7k/ssh/id_rsa, roles/preflight-checks/tasks/check_items.yml, roles/preflight-checks/tasks/v7k.yml, roles/v7k-defaults/defaults/main.yml
update v7k openstack-envs, the new structure is as the following:
```
v7k:
enabled: True
management_ip: 10.254.66.43
ssh_port: 22
users:
cinder:
name: bbcadmin
password:
ssh_pvt_key: 
ssh_pub_key:
monitoring:
name: bbcmonitor
password:
ssh_pvt_key:
ssh_pub_key:
storage_pools:
- v7k_pool1
```
=> refactor openstack-envs for v7k

roles/common/defaults/main.yml, roles/common/tasks/python.yml
with new request python pkg (2.14) shade install fails with following error
NameError: name 'platform_system' is not defined
This PR bumps the pip version to 9.0.1 which takes care of this issue.
=> Bump pip version to 9.0.1

roles/keystone-setup/tasks/federation.yml
For the federation module keystone_service_provider, the base virtual env was not setup correctly. This sets up the env for it.
=> setup the correct base virtual env for federation sp

envs/example/defaults-2.0.yml, roles/endpoints/defaults/main.yml, roles/haproxy/templates/etc/haproxy/haproxy_openstack.cfg
This PR aligns magnum to be consistent with other openstack project roles on it get's defined in endpoints/defaults. The change will address below deprecation message
TASK [openstack-firewall : permit access to magnum] ****************************
Saturday 06 May 2017  07:24:32 +0000 (0:00:00.382)       1:17:58.685 **********
[DEPRECATION WARNING]: Skipping task due to undefined Error, in the future this
will be a fatal error.: [{u'protocol': u'tcp', u'port': u'{{
endpoints.magnum.port.haproxy_api }}'}]: 'unicode object' has no attribute
'port'.
Soln: Adjust mangum to follow other openstack project roles on it get's deifned in endpoints/defaults
=> avoid deprecation messages from magnum role.

roles/barbican/tasks/main.yml, roles/inspec/tasks/main.yml, roles/keystone/tasks/openidc.yml
This PR addresses following Warning / Deprecation ansible messages
#1:
[WARNING]: While constructing a mapping from /home/nirajdp/deployments/master/ursula/roles/barbican/tasks/main.yml, line 85, column 5, found a duplicate dict key (mode).  Using
last defined value only.
Soln: remove duplicate attribute
#2:
TASK [keystone : create .client file for the IdPs] *****************************
Tuesday 09 May 2017  15:40:59 +0000 (0:00:00.887)       0:03:54.766 ***********
[DEPRECATION WARNING]: Skipping task due to undefined Error, in the future this will be a fatal error.: 'dict object' has no attribute 'providers_info'.
This feature will be
removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
#3:
TASK [inspec : fetch inspec …
=> avoid ansible warning/deprecation messages in ursula.log.

roles/ceph-defaults/defaults/main.yml
As there is a bug of cinder, which doesn't support high concurrency of
volume full clone. So we roll back rbd_max_clone_depth to 5, to use
copy-on-write clone by default.
For these who want to apply full-clone, they can set this variable in
all.yml.
=> roll back rbd_max_clone_depth to 5

roles/barbican/templates/etc/barbican/policy.json
Currently service_admin is using a role that doesnt exitst. Switching it out
to point to role:admin or role:cloud_admin. This can be changed later to more fine
grained access control if needed.
=> Update Policy file for barbican to update servie_admin

roles/keystone-defaults/defaults/main.yml, roles/keystone/templates/etc/keystone/uwsgi/keystone-admin.ini, roles/keystone/templates/etc/keystone/uwsgi/keystone-main.ini
This increases the buffer size for Keystone uwsgi. The default for uwsgi
is 4096. The new size will be 114688 bytes, which will match the default
size limit setting for the oslo 'sizelimit' middleware which exists in
the pipline. This will fix some issues where we get dropped federated
requests to Keystone because of SAML assertion sizes.
=> Increase buffer size for Keystone uwsgi

roles/keystone-defaults/defaults/main.yml, roles/keystone/templates/etc/keystone/uwsgi/keystone-admin.ini, roles/keystone/templates/etc/keystone/uwsgi/keystone-main.ini
This increases the buffer size for Keystone uwsgi. The default for uwsgi
is 4096. The new size will be 114688 bytes, which will match the default
size limit setting for the oslo 'sizelimit' middleware which exists in
the pipline. This will fix some issues where we get dropped federated
requests to Keystone because of SAML assertion sizes.
=> [3.1.x]Increase buffer size for Keystone uwsgi

roles/keystone-setup/tasks/federation.yml
auth_url was pointing to localhost for authentication. Changing it so that it uses the correct authentication URL for keystone
=> Change auth_url to point to the correct URL

roles/keystone/tasks/saml.yml, roles/keystone/templates/etc/shibboleth/shibboleth2.xml
This sets the url as the default Shibboleth metadata provider type. This way we do not have to set the metadata provider type by default.
=> [3.1.x]Set url as default Shibboleth metadata provider type

roles/keystone/tasks/saml.yml, roles/keystone/templates/etc/shibboleth/shibboleth2.xml
This sets a default value for the Shibboleth metadata provider type (file or url). This fixes an issue for when the value is not defined (Keystone is an IdP or when Keystone is an SP and value is not defined.)
=> Set url as default Shibboleth metadata provider type

roles/keystone-setup/tasks/federation.yml
This fixes an issue where we get a 401 unauthorized error. The list
of parameters used for authentication should be the same
as the other federation modules.
=> Fix auth parameters for the service providers module

roles/ceph-config/templates/etc/ceph/ceph.conf
ansible_managed always change, it results in ceph.conf change. Finally
it causes unexpected CEPH service restart.
This patch is to hard code ansible_managed to prevent unexpected CEPH
service restart.
=> hardcode ansible_managed

roles/nova-common/meta/main.yml, roles/nova-common/templates/etc/nova/nova.conf, roles/nova-data/handlers/main.yml, roles/nova-data/tasks/main.yml, roles/nova-data/tasks/v7k.yml, roles/nova-data/templates/etc/multipath.conf, roles/openstack-setup/meta/main.yml, roles/preflight-checks/meta/main.yml, roles/v7k-defaults/defaults/main.yml
multiple path support includes the three parts
- install the package(multipath-tools for ubuntu or  device-mapper-multipath for redhat)
- add etc/multipath.conf 
- add iscsi_use_multipath = True to nova.conf
=>  provide multipath support for V7K

envs/example/ci-ceph-redhat/heat_stack.yml, envs/example/ci-ceph-swift-rhel/heat_stack.yml, envs/example/ci-ceph-swift-ubuntu/heat_stack.yml, envs/example/ci-ceph-ubuntu/heat_stack.yml, envs/example/ci-full-centos/heat_stack.yml, envs/example/ci-full-rhel/heat_stack.yml, envs/example/ci-full-ubuntu/heat_stack.yml, envs/example/defaults-2.0.yml, roles/endpoints/defaults/main.yml, roles/haproxy/templates/etc/haproxy/haproxy_openstack.cfg, roles/keystone/tasks/main.yml, roles/keystone/templates/etc/init/keystone.conf, roles/keystone/templates/etc/keystone/uwsgi/keystone-admin.ini, roles/keystone/templates/etc/keystone/uwsgi/keystone-main.ini, roles/keystone/templates/usr/lib/tmpfiles.d/openstack-keystone.conf, roles/nova-common/defaults/main.yml, roles/nova-common/handlers/main.yml, roles/nova-common/meta/main.yml, roles/nova-common/templates/etc/nova/nova.conf, roles/nova-control/meta/main.yml, roles/nova-control/tasks/main.yml, roles/nova-control/templates/etc/init/nova-placement-api.conf, roles/nova-control/templates/etc/nova/uwsgi/placement.ini, roles/nova-control/templates/usr/lib/tmpfiles.d/openstack-nova-placement-api.conf, roles/nova-data/tasks/main.yml, roles/openstack-meta/defaults/main.yml, upgrade.yml
Enables nova-placement-api using uwsgi. 
Most of the work came from PR https://github.com/blueboxgroup/ursula/pull/2733.
port 8778 is the default openstack port for nova-placement-api. currently ursua uses 8778 for cinde volume backend port. This PR also switches cinder volume backend port to 9776 and nova-placement-api uses 8778 as it's frontend port.
Our upgrade.yml handles cinder controller services before it will upgrade nova so 8778 will be released in time for nova to use it when enabling nova-placement service.
=> nova-placement-api enablement.

roles/cinder-control/tasks/monitoring.yml, roles/cinder-control/tasks/v7k-monitoring.yml, roles/cinder-control/templates/etc/v7k/ssh/monitoring/id_rsa, roles/common/templates/monitoring/sensu-sudoers
add v7k monitoring
- Canister check
- Canister metrics, the following mertics can be collected.  The metrics can be used to draw graph and we can see system health according graph.
```
root@ds0054:~# ssh -i /etc/cinder/v7k/ssh/monitoring/id_rsa  openstackuser@10.254.66.43 lsnodecanisterstats
node_id node_name stat_name          stat_current stat_peak stat_peak_time
1       node1     compression_cpu_pc 0            0         170504005353
1       node1     cpu_pc             2            3         170504005323
1       node1     fc_mb              0            0         170504005353
1       node1     fc_io              0            0         170504005353
1       node1     sas_mb             0            570       170504005018
1       node1     sas_io             0            2272 …
```
=> v7k monitoring

envs/example/ci-ceph-swift-ubuntu/group_vars/all.yml, envs/example/ci-full-ubuntu/group_vars/all.yml, envs/example/defaults-2.0.yml, roles/inspec/tasks/main.yml, roles/neutron-common/defaults/main.yml, roles/neutron-control/tasks/main.yml, roles/neutron-data-network/tasks/main.yml, roles/neutron-data/tasks/main.yml, roles/openstack-meta/defaults/main.yml
- enable barbican for ci-full-ubuntu and ci-ceph-swift-ubuntu
- enable inspec for ci-full-ubuntu and ci-ceph-swift-ubuntu
- enable keystone.uwsgi.port for ci-ceph-swift-ubuntu
- clean up neutron.service.envs to be consistent with nova-compute
=> misc cleanups.

upgrade.yml
Part of upgrade flow in clients pretask ensure we are removing all 31x openstack clients.
=> remove all 31x openstack client in upgrade flow.

roles/keystone-setup/tasks/federation.yml
The keystone endpoint version is hardcoded. Replace this with
a variable which would be easy to modify in the future.
=> replace hardcoded v3 with variable for keystone v3

roles/ceph-osd/tasks/main.yml, roles/ceph-osd/tasks/pool_names.yml, upgrade.yml
pool_names.yml has all tasks those populate vars, so we use
pool_names.yml to populate vars instead of using ceph-osd role.
Also prevent running pool_names.yml more than one time.
=> use pool_names.yml to populate vars in upgrade.yml

ansible.cfg
When templating files with {{ ansible_managed }} inside the template, the file is considered changed every time ansible runs because the default ansible_managed contains a timestamp that always changes (and other bits that often change, i.e. when deploying from different machines/users).
This PR defines a static constant value for ansible_managed thus avoiding unnecessary service restarts when config files have not changed.
=> Use static ansible_managed line.

roles/ceph-osd/tasks/main.yml, roles/ceph-osd/tasks/pool_names.yml
Ansible passes the parent condition to every sub task in included yml
file. In following example, `ssd_pool is undefined` is passed to be condition of every task in pool_names.yml.
So we have to defined the flag at the end of the yml file, to make sure
all tasks in the yml file is executed.
```
- include: pool_names.yml
delegate_to: "{{ groups['ceph_monitors'][0] }}"
when:
- inventory_hostname == play_hosts[0]
- ssd_pool is undefined
```
=> set pool_names completed flag at the end of pool_name.yml

site.yml
cleaning up duplicate variable warning message.
=> site.yml duplicate variable cleanup.

roles/cinder-common/defaults/main.yml, roles/nova-common/defaults/main.yml
In 4.0.0.0c we have added new openstack service endpoints like barbican, cinderv3, placement in defaults-2.0.yml. These new endpoints are not defined in back releases (example 3.1.x) thus will break ursula run when using common defaults-2.0.yml.
This PR adds the flags that will help maintain backward compatibility in defaults-2.0.yml for 3.1.x release.
=> flags for defaults-2.0.yml backward compatibility to 3.1.x.

roles/ceph-monitor/tasks/main.yml
pip install may fails for the first time, so adding retry.
=> add retry for pip install bbg-ceph-utils

roles/client/tasks/main.yml
current monitoring runs in base venv, and some checks need related openstack component clients. most of them are installed by shade, but heat client isn't. so need to install heatclient as extra packages in base venv.
=> base virtualenv need heatclient for monitoring

roles/openstack-meta/defaults/main.yml, roles/openstack-setup/tasks/flavors.yml
if cloud users have added their own flavors, adding the default flavors may not be needed.  if any flavors are present, no default flavors will be created.
=> add logic for adding flavors to skip when flavors are already present

roles/ceph-config/tasks/main.yml, roles/ceph-monitor/tasks/main.yml
1. Remove the task which changes owner of admi keyring file.
It was used for upgrading from hammer to Jewel.
2. Add run_once for task which changes cap of CEPH users.
3. Fix `default('True')|bool`
=> some tiny fixes of ceph

roles/common/templates/etc/hosts
It's try to resolve a regression defect for live migration, to let source/target computes can know each other by long hostname or short hostname.
=> fix live migration

roles/nova-data/tasks/main.yml
upstart_service and systemd library handles updating the service config. This PR removes unwanted code to recreate service where we wanted to just update existing service.
=> cleanup nova-compute service update code.

roles/keystone/templates/etc/apache2/sites-available/keystone.conf
The apache site config for keystone was pointing to an incorrect socket location for the uwsgi method socket. This change fixes the location of the uwsgi socket in the config.
=> fix apache keystone.conf for uwsgi method socket

envs/example/ci-ceph-swift-ubuntu/group_vars/all.yml, envs/example/ci-ceph-ubuntu/group_vars/all.yml, envs/example/ci-full-ubuntu/group_vars/all.yml
In ubuntu switching to uswgi method port where apache uses mod_proxy_uwsgi plugin is causing intermittent 502 - Bad Gateway errors when hitting keystone apis concurrently.
Further debug from apache log shows segementation faults happening under high concurrency at mod_proxy_uwsgi module.
In past releases, for ubuntu we used method socket for uwsgi and mod_uwsgi plugin.
This PR is switching back ubuntu cluster to use uwsgi socket method.
=> switch uwsgi method socket for keystone - ubuntu.

envs/example/defaults-2.0.yml, requirements.txt, roles/client/defaults/main.yml, roles/client/tasks/main.yml, roles/openstack-meta/defaults/main.yml, roles/openstack-source/files/constraints.txt, roles/openstack-source/tasks/main.yml
This PR vendor's upper_contriants taking upstream upper_constraints.txt as of 05/19/2017 from https://github.com/openstack/requirements/blob/stable/newton/upper-constraints.txt with gitsha - e61e123c867d23ea1d341f9d1f04435bd5074257 and making following changes
Changes to upper_contraints.txt:
oslo.middleware===3.19.1  (originally was 3.19.0)
pyOpenSSL===16.2.0  (originally was 16.1.0)
cryptography===1.8.1 (originally was 1.5)
- To fix neutron rootwrapd performances issue
before:
user    0m0.297s
sys     0m0.049s
after:
real    0m0.155s
user    0m0.070s
sys     0m0.029s
- To fix security vunl around leaking sensitive information in logs when exception is raised
https://github.com/openstack/oslo.middleware/commit/6c0f50c1f5f4122b31dbfe25aacdce596bf4b648  (is already in newton/stable but …
=> vendored upper_contrain to fix performance issues.

roles/ceph-defaults/defaults/main.yml
Once any osd is down, CEPH will set these OSD out after interval.
We increase osd out interval so that the ops will have more time before
osd out.
=> increase osd out interval

roles/ceph-defaults/defaults/main.yml, roles/nova-common/defaults/main.yml
- ceph client version have been updated to version 10.2.7-0ubuntu0.16.04.1~cloud0
pin ceph client to new version(10.2.7-0ubuntu0.16.04.1~cloud0)
- pin libvirt-bin version to libvirt-bin_1.3.1-1ubuntu10.9~cloud0_i386.deb
=> pin ceph client and libvirt-bin/qemu to new version 

roles/ceph-common/defaults/main.yml, roles/nova-common/defaults/main.yml
ceph-client, libvirt-bina dn qemu-kvm version got bumped in upstream cloudarchive repo. This PR is to adjust the defaults to new version.
=> adjust to cloudarchive version bump.

roles/inspec/defaults/main.yml, roles/nova-common/defaults/main.yml, roles/nova-data/tasks/libvirt.yml, roles/percona-server/tasks/main.yml
Paired with: https://github.com/blueboxgroup/ursula-inspec/pull/15
This PR:
- adds in permissions/ownership changes for /var/run/mysqld.
- fixes settings in libvirtd.conf and qemu.conf for compliance.
- sets libvirt_sock_group and the user/group for the qemu processes.
=> Fix inspec checks for kvm and mysql

upgrade.yml
For env which didn’t install aodh, should not do related upgrade.
=> Fix-upgrade-aodh

playbooks/cinder-upgrade.yml, playbooks/unit.yml, roles/nova-control/tasks/main.yml
In Ubuntu/Newton as we enabled nova-placement we had to change cinder backend port 9776.
This PR fixes the mitaka to newton upgrade play to update existing haproxy with new cinder port after cinder is staged for upgrade.
Also, nova-cert service is retired in newton, this PR fixes removing nova-cert from nova service so that sensu does not raise false alarm for nova service being down.
=> adjust upgrade flow to account cinder port change.

library/ceph_pool.py, roles/ceph-osd/tasks/bcache.yml, roles/ceph-osd/tasks/standard.yml
According to [ceph docs](http://ceph.com/pgcalc), pgs_per_osd could be
100-300. It was 100 in former releases, we increase it to 200 to get
better PG distribution. We had changed the value of pgs_per_osd in
ceph-defaults role, we make the ceph_pool module use that parameter in
this commit.
=> update the pg per osd

roles/nova-control/tasks/main.yml
removing nova-cert from nova-service list must be only run once.
=> add run_once for removing nova-cert service.

roles/horizon/defaults/main.yml, roles/horizon/tasks/main.yml
Leslie asked me to take a look at this and it was a simple enough fix.
=> compile localized dashboard messages when installing from source/package

roles/client/tasks/main.yml, roles/common/tasks/ssl.yml, roles/rabbitmq/defaults/main.yml
upstream rabbitmq.com repo release 3.6.10-1 on 5.25, This is only version in their repo which now forces us to move to this version.
Also, there is new request package releases which installs certifi that provides Where() for ca bundle to be used for self-signed certs. This new request package calls cetifi where(). Previous requests version were looking up in requests filepath for cacert.pem part of exception handling of import error for certifi. This PR is handling this new requests version of handling lookup of ca bundle by also adding symlink to certifi.
=> move up rabbitmq version to 3.6.10*.

upgrade.yml
This is to fix the issue check-logstash-forwarder-process check still not removed.
This check's name is different from other traditional process check name.
=> Remove check-logstash-forwarder-process check during upgrade

roles/logging/tasks/filebeat.yml
Despite enablement of filebeat service as "enabled=yes", it does not
start on reboot. Adding this additional measure to make sure it starts.
=> Force start of filebeat on reboot

upgrade.yml
glance needs variable defined in pool_names.yml, so pool_names.yml
should go before glance role.
=> run pool_names.yml before glance in upgrade.yml

envs/example/ci-ceph-swift-ubuntu/group_vars/all.yml, envs/example/ci-full-ubuntu/group_vars/all.yml
Given Barbican is still a tech preview this PR is disabling it from the CI envs.
=> disable barbican for ci envs.

roles/neutron-control/templates/check-neutron-l3-routers.sh, roles/sensu-check/defaults/main.yml
Adding "delay_seconds" option to check-neutron-l3-router's template in order to accommodate for 30 second router creation time.
=> adding delay flag to check-neutron-l3-routers

roles/openstack-setup/tasks/cinder.yml
'ceph' was the cinder scheduler service host name. As we add v7k in this
release. So we use new host name for cinder scheduler service. After
upgrade, we can see new scheduler services are up, old service is down.
sensu alert error because of service down. 
This commit is to disable old scheduler service.
=> disable old cinder scheduler service

roles/common/defaults/main.yml, roles/common/tasks/python.yml
The latest test env installed with shade version 1.21.0, which cause some
check has error like below, and another test env with version 1.20.0 no
error.
File
"/opt/openstack/base/local/lib/python2.7/site-packages/shade/_legacy_cli
ents.py", line 64, in neutron_client return
self._create_or_return_legacy_client('neutron', 'network')
AttributeError: 'OpenStackCloud' object has no attribute
'_create_or_return_legacy_client'
=> Restrict shade version to avoid some monitoring check failure.

roles/client/defaults/main.yml, roles/client/tasks/main.yml, roles/common/tasks/ssl.yml, roles/openstack-source/files/constraints.txt
upstream merged few changes to upper_constrains to netwon/stable. This PR is sync'ing up our vendored upper_constrains file.
Also, when installing clients at system level it will enforce use of upper_constrains
=> sync up upper_constrians with upstream.

requirements.txt
setuptool 36.0 is breaking venv creation as it requires six module be already installed. This is a upstream regression caused in setuptools 36.0 - https://github.com/pypa/setuptools/issues/1042
=> add six to requirements.txt.

requirements.txt
Reverts blueboxgroup/ursula#2888
will wait for upstream fix in setuptools - https://github.com/blueboxgroup/ursula-cli/pull/71
For time following workaround can be used when preparing venv
pip install --upgrade "setuptools < 36"
=> Revert "add six to requirements.txt."

test/setup
Recent setuptool 36.0 caused a regression that is breaking CI runs by error'ing out at venv creation.
While we wait for ustream bug fix https://github.com/pypa/setuptools/issues/1042 this pr is downgrading setuptools to < 36.
=> workaround for setuptool regression to unbreak ci.

test/setup
Reverts blueboxgroup/ursula#2890
setuptools 36.0.1 is out that fixes the regression caused in earlier release.
=> Revert "workaround for setuptool regression to unbreak ci."

roles/ceph-defaults/defaults/main.yml
Old minor version of CEPH is removed from repo when new version comes.
Our ursula will fail if we point to the old version of CEPH.
This commit is to replace minor version number with * to "avoid package
not found error".
=> not restrict minor version number of CEPH client

roles/percona-server/templates/etc/my.cnf
MySQL Server crash possibly introduced in InnoDB statistics calculation
for 5.6.35 . https://bugs.mysql.com/bug.php?id=84940
Before we got new persona xtradb cluster version, we need this fix as
workaround to avoid the crash possibility.
=> to workaround mysql bug #84940

roles/common/templates/etc/serverspec/os_spec.rb
After running openstack-ansible-role, some of the checks fail because the openstack-ansible-security put a stricter controls than what ursula does
=> fixup the serverspec checks for ubuntu

roles/ceph-osd/tasks/pool_names.yml
As we check if pool_names_completed is defined on osd nodes, so we
should delegate the variable to all osd nodes. I also delegate the
variable to ceph monitor nodes for potential case.
=> delegate pool_names_completed variable to all ceph nodes

roles/inspec/defaults/main.yml
The Glance inspec check was failing on Ubuntu since the files did not exist.
Changed the attribute glance_config_files to be set based on OS type.
=> Removed glance config files

roles/common/defaults/main.yml, roles/common/handlers/main.yml, roles/common/tasks/chrony.yml, roles/common/tasks/main.yml, roles/common/tasks/monitoring.yml, roles/common/tasks/ntpd.yml, roles/common/templates/etc/chrony.conf, roles/common/templates/etc/ntp.conf, roles/common/templates/monitoring/sensu-sudoers
=> Optionally replace ntpd with chronyd

playbooks/tests/tasks/integration.yml
we've encounter delete security group exception due to server not fully deleted, hence added the check
=> ensure test instance deleted before delete security group

roles/nova-common/defaults/main.yml, roles/nova-common/meta/main.yml, roles/nova-common/templates/etc/nova/nova.conf
Before community provide https://bugs.launchpad.net/nova/+bug/1593155
related fix, we need this workaround to enable disk filter.
=> Workaround for DiskFilter

roles/ceph-defaults/defaults/main.yml
Either ntp or chrony can be used to sync time. We shouldn't install ntp
for ceph if chrony is configured.
=> remove ntp dependency from ceph

envs/example/ci-ceph-swift-rhel/group_vars/all.yml, envs/example/ci-ceph-swift-ubuntu/group_vars/all.yml, envs/example/defaults-2.0.yml
New paramiko 2.2 package is breaking swifttool. This PR points to new swifttool pkg that pins paramiko<2.2
=> bump up swifttool version.

envs/example/ci-ceph_swift/group_vars/all.yml, envs/example/defaults-2.0.yml
New paramiko 2.2 package is breaking swifttool. This PR points to new swifttool pkg that pins paramiko<2.2
=> bump swifttool version.

roles/inspec/defaults/main.yml
Changed the default file in inspec role for horizon group to be
assigned based on OS.
=> Updated inspec horizon group to be based on OS

roles/mongodb-common/defaults/main.yml
for security fix of https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2016-6494
=> upgrade mongodb version from 3.0.6 to 3.0.15

roles/aodh/templates/etc/aodh/aodh.conf
To avoid error like “MissingAuthPlugin: An auth plugin is required to
determine endpoint URL”
=> Replace out-dated aodh conf

roles/ceilometer-common/defaults/main.yml, roles/ceilometer-data/tasks/main.yml
This adds the ceilometer user to the group
that has access to the libvirt socket. This will allow
ceilometer to gain access and prevent an error that shows:
'AttributeError: can't set attribute'
=> Add ceilometer user to libvirt socket group

library/systemd_service.py, library/upstart_service.py, roles/cinder-data/tasks/main.yml
the default nofile limit is 1024, it's not enough for large ceph
cluster. deleting one volume needs osd_num opening files, so if we have
300 osds, we can't deleting 4 volumes at the same time(300*4 > 1024).
We increase the nofile to 16384 in this commit
=> increase nofile for cinder-volume/backup services

roles/neutron-common/defaults/main.yml, roles/neutron-common/templates/etc/neutron/plugins/ml2/ml2_plugin.ini
The current jinja2 template for m12_plugin.ini doesn't allow for extra configurations to be added or for configurations to be moved. For example, if someone wants to not use the vlan tunnel type and configuraton, they don't have the ability to turn it off. This would allow users to overide the m12_plugin jinja2 directly in the ansible inventory for more specialized deployments.
=> Allow for custom m12 configuration

roles/ceph-monitor/tasks/main.yml
ceph-utils was designed to adjust ceph for large cluster as whitewater.
We disable it as it doesn't work well with old env which upgraded from
3.0 or less
1. how to know if an env is old env which upgraded from 3.0 or less?
run following command on a mon node, if the word `default` is in the output, then it's an old env.
```
ceph osd lspools
```
2. how to disable ceph-utils for existing problem envs?
login to the master mon node and follow below steps:
1.1 edit /etc/cron.d/ceph_utils to comment all lines
1.2 find the osds which have `reweight` value less than 1.
```
ceph osd df
ID WEIGHT  REWEIGHT SIZE   USE    AVAIL  %USE VAR  PGS 
1 0.85999  1.00000   883G  1940M   881G 0.21 1.05 178 
2 0.85999  1.00000   883G  1744M   881G 0.19 0.94 152 
3 0.85999  1.00000   883G  1904M   881G 0.21 …
```
=> disable ceph-utils

roles/nova-common/defaults/main.yml, roles/rabbitmq/defaults/main.yml
testing a ci fix which involves updating package versions.  I updated the vars directly in `roles/nova-common/defaults/main.yml`, but can be updated in `envs/example/ci-full-ubuntu/group_vars/all.yml` instead if needed.
=> updated ubuntu package versions for libvirt and qemu and rabbitmq-server

playbooks/security-patches.yml
The result of testing the following 5 CVE's against a host that had already run `security-patches.yml` was that the only remaining package to upgrade was `libcurl3-gnutls`.  
```
CVE-2017-5335
CVE-2017-5336
CVE-2017-5337
CVE-2017-3735
CVE-2017-1000257
```
=> added libcurl3-gnutls to security-patches.yml

roles/ceph-monitor/tasks/monitoring.yml
PagerDuty api has a limit of 1024 in messages and including the osd tree was pushing the messages over that limit so even though critical alerts were being triggered, pagerduty would reject the request.
=> lowering verbosity of ceph status check

roles/aodh/defaults/main.yml, roles/barbican/defaults/main.yml, roles/ceilometer-common/defaults/main.yml, roles/ceph-defaults/defaults/main.yml, roles/cinder-common/defaults/main.yml, roles/common/defaults/main.yml, roles/glance/defaults/main.yml, roles/heat/defaults/main.yml, roles/ironic-common/defaults/main.yml, roles/keystone-defaults/defaults/main.yml, roles/magnum/defaults/main.yml, roles/neutron-common/defaults/main.yml, roles/nova-common/defaults/main.yml, roles/swift-common/defaults/main.yml
csv tags were being interpreted as a single string, so not usable in kibana for filtering. Converted to list values to fix.
=> Fixed log entry tagging bug

roles/ceilometer-data/tasks/main.yml, roles/nova-data/tasks/libvirt.yml
Problem is that the version fails to compile against older libvirt system packages.  See openstack bug # 1753539
=> Specify version 4.0.0 of libvirt-python

roles/openstack-package/tasks/main.yml
Since its only needed for new installs, the 2nd conditional in the task ensures it will only run on Jenkins CI.
=> pin libvirt0 version on jenkins ci

test.sh
Rally has been failing in CI, so we are disabling it during investigation of why.
=> Disable rally testing temporarily

playbooks/tests/tasks/ceph.yml
Increase max timeout and retry count to avoid clock skew during CI
=> increase ceph healthcheck timeout

requirements.txt
Pinning PyYAML to 4.2b4 because of issues deploying filebeat.yml
=> pin PyYAML
