envs/example/defaults.yml
envs/vagrant/defaults.yml
roles/cinder-common/defaults/main.yml
roles/cinder-common/templates/etc/cinder/cinder.conf
roles/glance/defaults/main.yml
roles/glance/templates/etc/glance/glance-api.conf
roles/glance/templates/etc/glance/glance-registry.conf
roles/heat/defaults/main.yml
roles/heat/templates/etc/heat/heat.conf
roles/keystone/defaults/main.yml
roles/keystone/templates/etc/keystone/keystone.conf
roles/neutron-common/defaults/main.yml
roles/neutron-common/templates/etc/neutron/neutron.conf
roles/nova-common/defaults/main.yml
roles/nova-common/templates/etc/nova/nova.conf

Allow setting variables to set debug and verbose logging options across the openstack services.

feature: debug and verbose logging as variables

---

roles/glance/defaults/main.yml

https://bugs.launchpad.net/glance/+bug/1400966

Update glance to fix traversal bug

---

roles/common/tasks/system-tools.yml

* cdpr - cisco discovery protocol - check port connected to.
* sysstat - useful tools such as iostat

Added some useful debugging tool packages

---

playbooks/testenv/tasks/create.yml
playbooks/testenv/tasks/delete.yml
playbooks/testenv/vars/main.yml
playbooks/tests/tasks/controller.yml
test/common
test/setup

test VMs will be prefixed with the branch name or commit id of the current
git repo.  This helps allow us test simultaneous commits / PRs.

Feature:  namespace test VMs

---

test/common
test/run
test/setup

Release 1.0.x backport jenkins bell

---

Vagrantfile
roles/common/tasks/main.yml
roles/common/templates/etc/hosts

* set hostname according to inventory_hostname
* use ansible_nodename in /etc/hosts for localhost

Address hostname issues

---

envs/example/defaults.yml
envs/vagrant/defaults.yml
roles/common/files/sensu_plugins/check-neutron-agents.sh
roles/common/files/sensu_plugins/check-os-api.rb
roles/common/tasks/monitoring.yml
roles/common/templates/etc/sensu/stackrc
roles/glance/tasks/monitoring.yml
roles/heat/tasks/monitoring.yml
roles/keystone/tasks/monitoring.yml
roles/nova-control/tasks/monitoring.yml
site.yml

put stackrc in /etc/sensu and source it in /etc/default/sensu
remove sourcing /root/stackrc from checks

Create monitoring user in openstack admin tenant

---

playbooks/tests/tasks/cleanup.yml
playbooks/tests/tasks/integration.yml

This will create a volume and attach it, then clean it up.

Add cinder integration tests

---

envs/example/defaults.yml
envs/vagrant/allinone/group_vars/all.yml
envs/vagrant/defaults.yml
library/sensu_check
roles/common/defaults/main.yml
roles/common/files/sensu_plugins/check-hostname.sh
roles/common/files/sensu_plugins/check-neutron-fip.py
roles/common/files/sensu_plugins/metrics-neutron-fip.py
roles/common/files/sensu_plugins/metrics-nova-oversub.sh
roles/common/files/sensu_plugins/metrics-nova-state.py
roles/common/files/sensu_plugins/metrics-nova.py
roles/common/tasks/monitoring.yml
roles/monitoring-common/defaults/main.yml
roles/neutron-control/tasks/monitoring.yml
roles/nova-control/tasks/monitoring.yml

Cluster metrics

---

envs/example/defaults.yml
roles/neutron-common/tasks/main.yml
roles/neutron-common/templates/usr/local/bin/neutron-restart-all
roles/neutron-common/templates/usr/local/bin/neutron-start-all
roles/neutron-common/templates/usr/local/bin/neutron-stop-all
roles/neutron-data-network/templates/etc/ipchanged/add_floating_ip

This builds on our existing failover tools and improves upon them.
Better tracking of agent status and neutron restarts.

HA neutron improvements

---

branch-validation.yml
library/neutron_floating_ip
library/nova_compute
library/nova_group

This playbook tests a number of connectivity things with nova and
neutron and instances. It tests instances being on different physical
nodes and being able to ping each other, and tests instances being able
to ping the internet with a floating IP assigned and without.
Some modifications were necessary to nova_group and nova_compute local
modules which should be able to go away if/when we pick up ansible 1.8.
Playbook prompts the user to do some manual action as some of the
testing isn't quite possible in an automated fashion (eg running
commands on an instance that no longer has a floating IP assigned).
The playbook also guides the user through testing HA failover scenarios.

Branch release validation playbook

---

library/cinder_volume_group

Re-write cinder_volume_group in python

---

library/swift_disk

Another task in removing antsy.
Unfortunately I don't believe we test swift in CI, so this will require some
manual testing before accepting.

rewrite swift_disk in python

---

playbooks/ovs_2_ml2_cleanup_remnants.yml

This can stay in the 1.0.x branch, it should not go to master

a playbook to do ml2 migration cleanup

---

test/run
test/setup
tox.ini

A few additional fixes were needed on top of #854.

test: fix tox, test/setup, test/run

---

playbooks/logging.yml
roles/cinder-common/tasks/logging.yml
roles/cinder-common/tasks/main.yml
roles/cleanup/handlers/main.yml
roles/cleanup/tasks/logging.yml
roles/glance/tasks/logging.yml
roles/glance/tasks/main.yml
roles/heat/tasks/logging.yml
roles/heat/tasks/main.yml
roles/ironic-common/tasks/logging.yml
roles/ironic-common/tasks/main.yml
roles/keystone/tasks/logging.yml
roles/keystone/tasks/main.yml
roles/logging-config/handlers/main.yml
roles/logging-config/tasks/main.yml
roles/logging-config/templates/etc/logstash-forwarder.d/template.conf
roles/logging/defaults/main.yml
roles/logging/files/etc/init/logstash-forwarder.conf
roles/logging/files/etc/rsyslog.d/49-haproxy.conf
roles/logging/meta/main.yml
roles/logging/tasks/main.yml
roles/logging/templates/etc/logstash-forwarder.d/main.conf
roles/neutron-common/tasks/logging.yml
roles/neutron-common/tasks/main.yml
roles/nova-common/tasks/logging.yml
roles/nova-common/tasks/main.yml
roles/swift-common/tasks/logging.yml
roles/swift-common/tasks/main.yml

backport #859 - logrotate-compress

---

roles/common/files/sensu_plugins/check-cinder-sessions.py

Fix check-cinder-sessions

---

roles/horizon/defaults/main.yml
roles/horizon/templates/opt/stack/horizon/openstack_dashboard/local/local_settings.py

add variable for horizon timeout, with default value of 1800

add variable for horizon timeout

---

library/sensu_metrics_check
roles/common/files/sensu_plugins/metrics-nova-state.py
roles/common/files/sensu_plugins/metrics-nova.py
roles/common/tasks/monitoring.yml
roles/common/templates/monitoring/sensu-sudoers

* nova using novaclient v3
* neutron fip check not in sudoers
* ensure sensu checks owned by root
* sensu metrics library should only add prefix when it exists

fix known monitoring bugs:

---

roles/security_errata/handlers/main.yml
roles/security_errata/tasks/main.yml

http://www.ubuntu.com/usn/usn-2537-1/

backport 1.1.x - Update to security role in response to openssl

---

roles/security_errata/handlers/main.yml
roles/security_errata/tasks/main.yml

http://www.ubuntu.com/usn/usn-2537-1/

Update to security role in response to openssl

---

roles/apt-repos/defaults/main.yml
roles/apt-repos/tasks/main.yml
roles/common/defaults/main.yml
roles/common/meta/main.yml
roles/common/tasks/hwraid.yml

install storcli,  remove megaraid
use storcli for monitoring check
matching PR for checks - https://github.com/blueboxgroup/ursula-monitoring/pull/1

initial support for storcli

---

envs/vagrant/defaults.yml
envs/vagrant/ironic/group_vars/all.yml
envs/vagrant/swift/group_vars/all.yml
playbooks/logging.yml
roles/ironic-common/defaults/main.yml
roles/ironic-common/meta/main.yml
roles/logging/handlers/main.yml
roles/logging/tasks/main.yml
roles/logging/templates/etc/rsyslog.d/20-ufw.conf
roles/swift-account/templates/etc/swift/account-server.conf
roles/swift-common/defaults/main.yml
roles/swift-common/files/etc/rsyslog.d/10-swift-udp.conf
roles/swift-common/files/etc/rsyslog.d/49-swift.conf
roles/swift-common/handlers/main.yml
roles/swift-common/meta/main.yml
roles/swift-common/tasks/logging.yml
roles/swift-container/templates/etc/swift/container-server.conf
roles/swift-object/tasks/main.yml
roles/swift-object/templates/etc/swift/object-server.conf
roles/swift-proxy/templates/etc/swift/proxy-server.conf

Release 1.1.x backport 893

---

roles/security_errata/tasks/main.yml

Resolve incorrect handler for haproxy.

---

README.md
bin/install-osx
bin/install-ubuntu
doc/dev-test.md

Our docs were a bit out of date around getting a development environment spun up. This PR corrects them.

Update documentation to match current state of play with Ursula.

---

envs/example/defaults.yml
envs/vagrant/defaults.yml

This enables live snapshot, resolves security issues, fixes VENVs to have proper levels of setuptools and pip.

Jump to bbc54 to bring in required fixes

---

playbooks/neutron-ml2-vlan-to-vxlan-migration.yml
playbooks/neutron-ml2-vxlan-kernel-prerequisite.yml

Backporting migration to 1.0.x and refining playbooks.

Refinements to VLAN to VXLAN migration

---

roles/cinder-common/templates/etc/cinder/cinder.conf
roles/nova-common/templates/etc/nova/nova.conf

sql_connection is deprecated, switching to database.connection.

DB connections

---

plugins/callbacks/timestamp.py

```
PLAY RECAP ********************************************************************
Friday 03 April 2015  13:11:49 -0500 (0:00:00.094)       0:00:29.686 **********
===============================================================================
Slowest 25 Tasks
===============================================================================
common | fetch ursula_monitoring when install method is git ------------- 1.82s
common | update ca certificates ----------------------------------------- 1.53s
common | Install prerequisites for acquiring crash dumps ---------------- 0.63s
common | Permit SSH ----------------------------------------------------- 0.62s
common | Enable UFW (after configuring SSH access) ---------------------- 0.62s
common | install sensu …
```

calcs time of each task and reports on slowest25

---

envs/vagrant/defaults.yml
roles/collectd-client/defaults/main.yml
roles/collectd-client/tasks/main.yml
roles/collectd-client/templates/etc/collectd/plugins/sensors.conf
roles/common/handlers/main.yml
roles/common/tasks/system-tools.yml

requires - https://github.com/blueboxgroup/ursula-monitoring/pull/4

collect sensor metrics with collectd

---

site.yml

(cherry picked from commit f05df4fc9c59427790459d576e47d780c1399631)

Remove errant comments on heat conditional (1.2.x)

---

envs/example/defaults.yml
envs/vagrant/defaults.yml

This package doesn't include a lot of external dependencies, so we're
going to rely on ursula to install them.

Bump packages to bbc58

---

Vagrantfile
envs/example/defaults.yml
envs/vagrant/defaults.yml
envs/vagrant/swift/group_vars/all.yml
envs/vagrant/swift/hosts
library/swift_disk
roles/swift-proxy/templates/etc/swift/proxy-server.conf
roles/swift-ring/tasks/main.yml
site.yml

After a series of refactors and rewrites there were a small number of
defects in the Swift code path. Update Ursula to take account for
these changes.

Get Swift working again

---

Vagrantfile
envs/example/defaults.yml
envs/vagrant/defaults.yml
envs/vagrant/swift/group_vars/all.yml
envs/vagrant/swift/hosts
library/swift_disk
roles/swift-proxy/templates/etc/swift/proxy-server.conf
roles/swift-ring/tasks/main.yml
site.yml

After a series of refactors and rewrites there were a small number of
defects in the Swift code path. Update Ursula to take account for
these changes.

Backport Get Swift working again

---

roles/horizon/defaults/main.yml

add increased horizon timeout to master

increase horizon timeout to 90 minutes

---

roles/common/templates/monitoring/sensu-sudoers

Otherwise sensu is not able to run this privileged command.

Add check-storcli to sensu's sudoers

---

roles/glance/tasks/image-sync.yml
roles/glance/templates/etc/cron.d/glance-image-sync
roles/glance/templates/etc/glance/.my.cnf

Write a separate MySQL options file with Glance database credentials and
use that instead.

Avoid passing glance DB credentials as arguments

---

envs/example/defaults.yml
roles/nova-common/templates/etc/nova/nova.conf

Also allow resize to same host.

Turn on ssh for resize/migrate

---

envs/example/defaults.yml
roles/nova-common/defaults/main.yml

Simple PR that gets master passing CI again.

Bump qemu version for VENOM

---

envs/vagrant/defaults.yml

Including a fix for reverting resize/migration attempts.

Bump to bbc64 to pick up nova fixes

---

library/neutron_router_gateway
roles/openstack-setup/tasks/networks.yml

Update neutron_router_gateway from upstream

setup: configure NAT on Neutron router

---

roles/nova-common/defaults/main.yml
roles/nova-data/tasks/libvirt.yml

Update the package, tag the task with security.

VENOM for 1.1.x

---

roles/nova-common/defaults/main.yml
roles/nova-common/templates/etc/nova/nova.conf

Add default_floating_pool to nova config

---

roles/nova-data/tasks/libvirt.yml

But we need this specific version or stuff won't start. YAAAAAY
PACKAGES!

libvirt doesn't express the dep on this library

---

roles/nova-data/tasks/libvirt.yml

We forgot to add librbd for 14.04

Update apt cache and fix 14.04 nova packages

---

envs/vagrant/defaults.yml
roles/cinder-data/tasks/monitoring.yml
site.yml

relies on https://github.com/blueboxgroup/ursula-monitoring/pull/18

add volume group checks for cinder

---

library/nova_group
playbooks/tests/tasks/integration.yml
requirements.txt
roles/client/defaults/main.yml

We were pinning for reasons that are no longer valid. Instead we've pinned ourselves to buggy versions. Remove the pins and see what happens!

Remove novaclient pinnings.

---

roles/percona-arbiter/tasks/main.yml

change garbd start from "enabled=on" to "enabled=yes"

fix typo to enable garbd start on boot

---

library/service

update-rc.d lies, so Ansible no longer believes the lies. This was found
via https://github.com/ansible/ansible-modules-core/issues/90

Manually patch in update-rc.d fix from upstream

---

branch-validation.yml

Move from manual reboot for testing failover to hard reboot via IPMI.

Ipmi reboot

---

roles/apt-repos/defaults/main.yml
roles/common/defaults/main.yml
roles/common/meta/main.yml
roles/common/tasks/hwraid.yml

This reverts commit 44d9e2bd3fa7490ad4aa585abfc2dd1ffe37adb5.
We're running into problems with conflicting storcli packages that need
to be worked out before making this change. Reverting to a previous
working configuration.

Revert "initial support for storcli"

---

roles/common/tasks/monitoring.yml

(cherry picked from commit 965e4ccdadfa17e2c7eb48cbdebecddbc16fc603)

BACKPORT 1.2.x: install libfile-which-perl (cf. blueboxgroup/ursula-monitoring#20)

---

roles/nova-control/files/nova-quota-sync
roles/nova-control/tasks/main.yml

From https://github.com/cernops/nova-quota-sync
Adding this script allows a standard way for support to rebuild damaged nova quotas without delving into the database.

Add nova-quota-sync script that rebuilds quotas.

---

doc/todo.md

Just as the summary says
@paulczar

Add note about adding style docs

---

roles/nova-common/defaults/main.yml
roles/nova-common/tasks/main.yml

Add virt-top to nova roles to assist in diagnostics and troubleshooting.

add virt-top to nova roles

---

Vagrantfile
roles/apt-repos/defaults/main.yml
roles/openstack-package/defaults/main.yml
roles/openstack-package/meta/main.yml

do not merge until packagecloud account is official.

Use packages built and deployed to package-cloud.

---

envs/example/defaults.yml
envs/example/vagrant.yml
roles/neutron-common/defaults/main.yml
roles/neutron-common/templates/etc/neutron/plugins/ml2/ml2_plugin.ini
roles/neutron-common/templates/etc/neutron/plugins/openvswitch/ovs_neutron_plugin.ini
roles/neutron-data/defaults/main.yml
roles/neutron-data/templates/etc/neutron/plugins/openvswitch/ovs_neutron_plugin.ini

Test neutron.tunnel_types length instead.

Neutron: remove enable_tunneling boolean

---

roles/neutron-data-network/tasks/main.yml
roles/openstack-source/handlers/main.yml
roles/openstack-source/tasks/main.yml

We've been marking some tasks where we'd like to use it, so now use it.

Make more use of the omit filter

---

doc/endpoints.md

Greetings,
Please consider this humble documentation update, in the domain of prose many eyes take the place of automated tests and continuous integration :)
Happy hacking,
Eric

Documentation update

---

roles/cinder-common/defaults/main.yml
roles/cinder-common/templates/etc/cinder/cinder.conf
roles/cinder-data/tasks/main.yml
roles/cinder-data/tasks/volume_group.yml
site.yml

Conflicts:
roles/cinder-data/tasks/main.yml
roles/cinder-data/tasks/volume_group.yml
site.yml

cinder override volgroup

---

roles/swift-proxy/templates/etc/swift/proxy-server.conf

Verified that creating container with correct attributes and index.html file, it can be displayed as web page with the changes

Adding the staticweb functionality to Swift

---

roles/swift-object/handlers/main.yml
roles/swift-object/tasks/main.yml
roles/swift-object/templates/etc/swift/object-expirer.conf

Verified that objects set to expire was deleted/cleaned by object expirer

Enable object expiry feature in Swift

---

roles/nova-common/defaults/main.yml
roles/nova-common/templates/etc/nova/nova.conf

Add the ability to reserve nova ram resources. Also, make it such that
we can tune these values.

Add ram reservation for compute nodes

---

roles/swift-object/templates/etc/swift/object-expirer.conf
roles/swift-proxy/templates/etc/swift/proxy-server.conf

Fix memcache configuration in Swift   to include all nodes in cluster

---

library/swift_disk

This patch will fix issue #1127

Partition type needs to be gpt to handle > 2TB disks

---

roles/glance/tasks/monitoring.yml

(cherry picked from commit 66421ec615fc219e85b8093b1c9a19178161bb78)

Add functools32 for glance-store-check (1.2.x)

---

roles/cinder-control/tasks/main.yml
roles/glance/tasks/main.yml
roles/heat/tasks/main.yml
roles/ironic-control/tasks/main.yml
roles/keystone/tasks/main.yml
roles/neutron-control/tasks/main.yml
roles/nova-control/tasks/main.yml

add tags so that database migration can be skipped via '--skip-tags db-migrate'

Optional db migration

---

roles/swift-proxy/templates/etc/swift/proxy-server.conf

Add formpost to proxy server pipeline

---

roles/common/templates/monitoring/sensu-sudoers
roles/neutron-data-network/tasks/monitoring.yml

added bits for l3 router check: https://github.com/blueboxgroup/ursula-monitoring/pull/25

add l3-router sensu check

---

roles/ceph-common/LICENSE
roles/ceph-common/defaults/main.yml
roles/ceph-common/handlers/main.yml
roles/ceph-common/meta/main.yml
roles/ceph-common/tasks/main.yml
roles/ceph-common/templates/etc/ceph/ceph.conf

Let's try this again.. This time adding only the ceph-common role.
I took out the Red Hat references, styled it the Ursula way (I hope),
and fixed some of the issues from the other day. It'll likely still
need work but wanted to get initial feedback.
@lyandrew

Add ceph-common role

---

bootstrap.sh

Derped previous PR and didn't add bootstrap.sh

Workstation

---

roles/ceph-osd/LICENSE
roles/ceph-osd/defaults/main.yml
roles/ceph-osd/meta/main.yml
roles/ceph-osd/tasks/main.yml

Initial commit for ceph-osd role.

Add ceph-osd role

---

roles/openstack-package/defaults/main.yml

(cherry picked from commit f646dcc2df45a027ae5e133c35c6b6d483094e72)

Use bbc115 which undoes (some of) our forks (1.3.x)

---

roles/openstack-source/tasks/main.yml
roles/swift-common/handlers/main.yml
roles/swift-common/meta/main.yml

Added keystonemiddleware as dependency in Python and added restart swift services handler

Changes to get Swift source install working 

---

roles/horizon/tasks/main.yml

Fixing css loading for package install

---

envs/example/defaults.yml
envs/example/standard/hosts
roles/cinder-common/meta/main.yml
roles/cinder-common/tasks/ceph_integration.yml
roles/cinder-common/tasks/main.yml
roles/cinder-common/templates/etc/ceph/secret.xml
roles/cinder-common/templates/etc/cinder/cinder.conf
roles/glance/meta/main.yml
roles/glance/tasks/ceph_integration.yml
roles/glance/tasks/main.yml
roles/glance/templates/etc/glance/glance-api.conf
site.yml

This isn't finished yet, but wanted to get feedback on how best to integrate this piece.

Ceph integration

---

library/ceph_pool.py

This module automates the creation of the ceph pool and PG count.
PG count depends largely on the number of OSDs and the number of
copies.

Add custom module ceph_pool

---

envs/example/defaults.yml
envs/vagrant/defaults.yml

Fixes issue with snapshotting the only instance on a HV

Bump to bbc117

---

roles/ceph-common/defaults/main.yml
roles/ceph-common/templates/etc/ceph/ceph.conf
roles/ceph-monitor/defaults/main.yml
roles/ceph-monitor/tasks/main.yml
roles/ceph-osd/tasks/main.yml

Adding the hook for `ceph_pool`, which automates pool creation and
pg count.

ceph_pool integration

---

roles/ceph-common/meta/main.yml
roles/ceph-monitor/tasks/main.yml
roles/ceph-monitor/tasks/monitoring.yml

Adding Sensu monitoring task for Block Storage (Ceph) nodes.
IDS Epic:
https://hub.jazz.net/ccm08/quickplanner/jazzhub.html#items:projectId=_MM_y5SldEeWSQOc0JZWznA&serverId=hub.jazz.net&planType=allwork&allIterations=true&itemId=97391
Story: https://hub.jazz.net/ccm08/quickplanner/jazzhub.html#items:projectId=_MM_y5SldEeWSQOc0JZWznA&serverId=hub.jazz.net&planType=allwork&allIterations=true&itemId=104679

Monitoring for ceph

---

roles/neutron-data-network/tasks/monitoring.yml

Add ansible tasks for gateway ip duplicate check using arping

gateway ip duplicate check

---

library/ceph_disks.py

Adding ceph disk_detection functionality
Story: https://hub.jazz.net/ccm08/quickplanner/jazzhub.html#items:projectId=_MM_y5SldEeWSQOc0JZWznA&serverId=hub.jazz.net&planType=allwork&allIterations=true&itemId=104678
IDS Epic: https://hub.jazz.net/ccm08/quickplanner/jazzhub.html#items:projectId=_MM_y5SldEeWSQOc0JZWznA&serverId=hub.jazz.net&planType=allwork&allIterations=true&itemId=97391

disk_detection for ceph nodes

---

roles/swift-proxy/meta/main.yml
roles/swift-proxy/tasks/main.yml

This is to fix the issue #1231

Use Ursula memcached role instead of installing package on Swift nodes

---

envs/example/standard/hosts
roles/ceph-common/defaults/main.yml
roles/ceph-common/templates/etc/ceph/ceph.conf
roles/ceph-osd/defaults/main.yml
roles/ceph-osd/tasks/main.yml

This changeset allows switching between two osd scenarios:
1/ raw multi journal
2/ journal collocation

Support for journal collocation

---

roles/common/tasks/kernel-tuning.yml

Add option to limit available CPUs via grub config

add optional CPU limit

---

roles/swift-proxy/defaults/main.yml
roles/swift-proxy/templates/etc/swift/proxy-server.conf

Note project_admin/cloud_admin roles are added as part of PR #1222 
Defect 106713 in IDS

Adding support for project_admin and cloud_admin roles in Swift

---

library/swift_disk.py
roles/swift-object/tasks/main.yml

Fixing the library issue
Changes to format specific partition
Consider lvm partitions for Swift in local
Change name for OS shared partition var
Fix the syntax issues

Modify library to accept partition path

---

doc/endpoints.md

Added Ceilometer Ports To Endpoint Documentation

Added MongoDB & Ceilometer Ports To Endpoint Documentation

---

roles/glance/tasks/main.yml

These changes will make glance techspec compliant per our discussions about the techspec document.

Make glance techspec compliant 

---

roles/keystone/tasks/logging.yml
roles/keystone/tasks/main.yml
roles/keystone/templates/etc/keystone/keystone.conf

We are implementing the Technical Specifications in Ursula. We are using Keystone as an example. We want to show you the changes we are making as the rest of the components will have similar changes. We are not intending to merge this change as of now, but we looking for feedback prior to moving forward since the rest of the of tech specs will be modeled off this one. Thanks!

Keystone techspec

---

roles/mongodb-common/tasks/main.yml

This will change the mongodb conf file permissions to be techspec compliant

Make mongodb techspec compliant

---

envs/example/defaults.yml
roles/ceph-common/templates/etc/ceph/ceph.conf

Use undercloud_cidr for ceph

---

roles/cinder-common/defaults/main.yml
roles/horizon/defaults/main.yml

Without this pin, glance client is not able to get full image info.

Pin requests inside horizon.

---

roles/horizon/defaults/main.yml
roles/horizon/templates/etc/openstack-dashboard/local_settings.py

This is WIP, flag it off for now.

Feature flag horizon customization

---

playbooks/bootstrap_ml2_vxlan.yml
roles/cinder-common/meta/main.yml
roles/cinder-common/tasks/main.yml
roles/cinder-common/templates/etc/cinder/cinder.conf
roles/common/meta/main.yml
roles/common/tasks/main.yml
roles/common/tasks/ssl.yml
roles/endpoints/defaults/main.yml
roles/glance/meta/main.yml
roles/glance/tasks/main.yml

Fixing issues we found in denali deployment.

Incremental denali updates

---

roles/swift-account/tasks/main.yml
roles/swift-common/tasks/logging.yml
roles/swift-common/tasks/main.yml
roles/swift-container/tasks/main.yml
roles/swift-object/tasks/main.yml
roles/swift-proxy/tasks/main.yml

Change the permissions of swift logs and swift config files to be in
compliance with the techspec document

Make swift techspec compliant

---

roles/neutron-common/tasks/main.yml
roles/nova-common/tasks/main.yml

Make the nova and neutron policy files 644 so that horizon can check
the permissions. The changes can be found in:
roles/neutron-common/tasks/main.yml
roles/nova-common/tasks/main.yml

 Make nova and neutron policy files 644.

---

roles/rabbitmq/tasks/main.yml

This change will allow rabbitmq to be techspec compliant

Make rabbitmq techspec compliant

---

roles/cinder-data/tasks/monitoring.yml

VG-metric was being run with illegal --scheme  option, fixed

Vg-metric fix on run command

---

roles/swift-common/defaults/main.yml
roles/swift-common/tasks/main.yml

http://docs.openstack.org/developer/swift/deployment_guide.html#general-system-tuning

Swift tuning according to deployment guide

---

roles/percona-server/tasks/logging.yml
roles/percona-server/tasks/main.yml
roles/percona-server/tasks/monitoring.yml
roles/percona-server/templates/etc/my.cnf

Delete test database after installation
Setup logrotation
Fix the location of general and error log files for mysql
Fix a typo in monitoring.yml

Make mysql techspec compliant 

---

roles/endpoints/defaults/main.yml
roles/mongodb-common/tasks/main.yml

Also fixed ceilometer service type in endpoints role.

Added Ownership of mongod.conf To MongoDB User

---

playbooks/logging.yml
roles/horizon/defaults/main.yml
roles/horizon/meta/main.yml
roles/horizon/tasks/logging.yml
roles/horizon/tasks/main.yml

remove TODO
customization flag off

Add horizon logs to logstash

---

roles/neutron-common/tasks/main.yml
roles/neutron-common/templates/usr/local/bin/neutron-reset

authored by @dlundquist, this utility has been used several times to good effect

neutron-reset utility

---

roles/glance/templates/etc/glance/glance-api.conf

Fix for Issue #1349 
Couple of parameters were missing and others were not configured correctly

Correctly configure glance to use swift as store

---

branch-validation.yml
envs/example/defaults.yml
playbooks/tests/tasks/cleanup.yml
playbooks/tests/tasks/controller.yml
playbooks/tests/tasks/integration.yml
playbooks/update-provider-admin-password.yml
roles/client/templates/root/stackrc
roles/haproxy/templates/etc/haproxy/haproxy_openstack.cfg
roles/heat/tasks/main.yml
roles/horizon/templates/etc/openstack-dashboard/local_settings.py
roles/neutron-common/tasks/main.yml
roles/openstack-network/tasks/main.yml
roles/openstack-setup/tasks/cinder.yml
roles/openstack-setup/tasks/images.yml
roles/openstack-setup/tasks/networks.yml
roles/openstack-setup/tasks/users.yml
upgrade.yml

remove provider_admin user in favor of admin
remove customization flag

change default role to _member_, remove provider_admin

---

envs/example/defaults.yml
roles/common/defaults/main.yml
roles/common/tasks/ntp.yml

Variable-ize ntpd nameservers

---

roles/heat/defaults/main.yml
roles/heat/templates/etc/heat/heat.conf

Make Heat plugin_dirs an optional config item.

Support Heat plugin_dirs

---

roles/common/tasks/main.yml
roles/common/tasks/networking.yml
roles/common/tasks/password-policy.yml
roles/common/tasks/ssh.yml
roles/common/tasks/system-file-permissions.yml
roles/common/tasks/system-tools.yml
roles/common/templates/etc/sshd_config

This is a work-in-progress. Please provide feedback! thanks

Make OS techpec compliant

---

roles/common/tasks/ntp.yml

Saw this in sitecontroller today, thought it'd be good here.
Also, wanted to fix the task name as they are not nameservers.

Add iburst to ntp.conf

---

roles/swift-common/defaults/main.yml
roles/swift-container/defaults/main.yml

Can be turned off in an env config if desired.

Default to allowing swift versions

---

envs/example/allinone/group_vars/all.yml
envs/example/ci/group_vars/all.yml
envs/example/defaults.yml
roles/heat/defaults/main.yml
roles/neutron-common/templates/etc/neutron/neutron.conf

Heat by default, l3ha gets you overlapping IPs.

Adjust feature flags.

---

roles/ceph-monitor/tasks/monitoring.yml
roles/heat/tasks/monitoring.yml
roles/neutron-control/tasks/monitoring.yml
roles/nova-control/tasks/monitoring.yml

-Added check to see if lbaas is active
-deleted unwanted characters

Adding remaning checks for SLA-metrics

---

roles/endpoints/defaults/main.yml
roles/keystone/templates/etc/keystone/keystone-paste.ini

Make sure that keystone.jellyroll is treated as a boolean and add
memcache_servers parameter to the keystone-paste.ini via endpoints.

Minor changes to jellyroll implementation

---

envs/example/swift/group_vars/all.yml
envs/example/vagrant.yml
roles/ceph-common/templates/etc/ceph/ceph.conf
roles/common/tasks/ufw.yml
test/setup

This will add the ability to list multiple CIDRs. In order to make it pass we had to add Jesse's PR #1389. If it fails, try running it again after it gets merged, I need to change one line in it.

Add multi cidr support

---

roles/horizon/templates/etc/openstack-dashboard/local_settings.py

Added cinder features to local_settings to enable backup from horizon

---

roles/glance/tasks/monitoring.yml

Disable glance-store monitor when images stored in ceph or swift

---

roles/security_errata/tasks/main.yml

ii dpkg 1.17.5ubuntu5.5 amd64 Debian package management system
showing proper ver in vagrant allinone

explicitly patch dpkg per CVE

---

roles/common/tasks/monitoring.yml

Will work with Sam to deploy this out

disable unwanted sensu monitors per craig and jlk, requested by support

---

roles/swift-common/tasks/main.yml
roles/swift-common/templates/etc/update-motd.d/99-swift-motd

Changing the path of the motd file swift writes to

Fix Swift's motd

---

roles/common/tasks/main.yml
roles/common/templates/etc/update-motd.d/90-ursula-motd
roles/common/templates/etc/ursula-release

Make ursula-relase yaml, so that more than just a human can read it.
Then fix update-motd so *that* a human *can* read it.

Fix up ursula-release...make it yaml

---

roles/cinder-common/meta/main.yml
roles/common/tasks/password-policy.yml
roles/common/tasks/system-tools.yml
roles/glance/meta/main.yml
roles/haproxy/meta/main.yml
roles/heat/meta/main.yml
roles/horizon/tasks/main.yml
roles/ironic-common/meta/main.yml
roles/keystone-setup/tasks/main.yml
roles/keystone/tasks/main.yml
roles/neutron-common/meta/main.yml
roles/neutron-control/tasks/main.yml
roles/neutron-data-network/tasks/monitoring.yml
roles/openstack-network/meta/main.yml
roles/swift-common/meta/main.yml

This will fix the ansible-lint complaints brought up in issue #615. I ran ansible-lint against the latest site.yml. I'm still working on a few things, but here it is so far.

WIP Fix ansible-lint complaints

---

roles/neutron-data-network/tasks/ipchanged.yml

[WIP] Fix ipchanged scripts for controllers that are not acting as gateway

---

roles/glance/templates/etc/glance/glance-api.conf
roles/glance/templates/etc/glance/glance-swift-store.conf

Use config for glance swift store to not reveal service password

---

roles/common/templates/etc/sshd_config

Should replace PR https://github.com/blueboxgroup/ursula/pull/1458

Make MaxAuthTries configurable in sshd_config

---

roles/common/tasks/ssh.yml
roles/common/templates/etc/sshd_config

Use templates to setup sshd_config rather than using `lineinfile`.

Template out sshd_config

---

roles/client/defaults/main.yml
roles/percona-arbiter/tasks/main.yml

This rolls in PR #1507 to fix neutron client and it pulls in a fix for garbd
starting

Fix builds from master

---

requirements.txt

No longer needed / that commit doesn't even exist.

Remove ansible-lint from reqs

---

roles/common/defaults/main.yml

Otherwise we pull master and things go awry.

Pin ursula-monitoring to the release branch

---

test/setup

Let's install a specific version of pip instead of latest until
https://github.com/pypa/pip/issues/3384 gets addressed

Pin pip to work around distutils issue

---

roles/glance/meta/main.yml
roles/heat/meta/main.yml
roles/keystone/meta/main.yml
roles/magnum/meta/main.yml
site.yml

...not an explict call on play (follows convention)

'openstack-database' role invocation as role dependency

---

roles/ceilometer-common/defaults/main.yml
roles/ceilometer-common/templates/etc/ceilometer/ceilometer.conf
roles/cinder-common/defaults/main.yml
roles/cinder-common/templates/etc/cinder/cinder.conf
roles/heat/defaults/main.yml
roles/heat/templates/etc/heat/heat.conf
roles/ironic-common/defaults/main.yml
roles/ironic-common/templates/etc/ironic/ironic.conf
roles/magnum/defaults/main.yml
roles/magnum/templates/etc/magnum/magnum.conf
roles/neutron-common/defaults/main.yml
roles/neutron-common/templates/etc/neutron/neutron.conf
roles/nova-common/defaults/main.yml
roles/nova-common/templates/etc/nova/nova.conf

This adds the heartbeat_timeout_threshold parameter to the configurations that have rabbit.  Rabbit options have also been moved into the oslo_messaging_rabbit section for Kilo.

WIP: Add oslo heartbeat timeout

---

roles/logging/defaults/main.yml

Updated file mirror for logstash forwarder

---

roles/keystone/tasks/main.yml

UFW should allow access to legacy keystone port

ufw needs to expose keystone legacy port

---

roles/apt-repos/defaults/main.yml
roles/common/meta/main.yml
roles/logging/defaults/main.yml
roles/logging/meta/main.yml
roles/logging/tasks/main.yml
roles/openstack-package/defaults/main.yml
roles/openstack-package/meta/main.yml

Just simply everything to not need that mirror.

Get rid of old bbg_ubuntu mirror

---

roles/percona-backup/templates/percona-xtrabackup.sh

Backport to fix shebang in PErcona backup script

Fix percona-xtrabackup.sh template shebang

---

roles/swift-proxy/meta/main.yml
roles/swift-ring/meta/main.yml

Fix for issue https://github.com/blueboxgroup/ursula/issues/1566

Add swift-common dependency to all swift roles

---

roles/openstack-package/tasks/main.yml
roles/openstack-source/tasks/main.yml

If an operator passes "-e upgrade=true", then the symlink task will
trigger.
Also update tasks I'm touching to the desired format, and use the stat
module to check the link status.

Ensure the symlink target also on upgrade

---

roles/client/defaults/main.yml
roles/common/defaults/main.yml
roles/common/tasks/pip.yml
roles/nova-common/defaults/main.yml

Old tree, need old clients. New versions were incompatible with our
other pinnings.

Pin some clients due to recent updates breaking (1.2.x)

---

roles/ceilometer-common/defaults/main.yml
roles/ceilometer-control/tasks/monitoring.yml
roles/ceph-common/defaults/main.yml
roles/ceph-monitor/tasks/monitoring.yml
roles/cinder-common/defaults/main.yml
roles/cinder-control/tasks/monitoring.yml
roles/common/defaults/main.yml
roles/common/tasks/monitoring.yml
roles/glance/defaults/main.yml
roles/glance/tasks/monitoring.yml
roles/heat/defaults/main.yml
roles/heat/tasks/monitoring.yml
roles/horizon/defaults/main.yml
roles/horizon/tasks/monitoring.yml
roles/keystone-defaults/defaults/main.yml
roles/keystone/tasks/monitoring.yml
roles/memcached/defaults/main.yml
roles/memcached/tasks/monitoring.yml
roles/neutron-common/defaults/main.yml
roles/neutron-data-network/tasks/monitoring.yml
roles/neutron-data/tasks/monitoring.yml
roles/nova-common/defaults/main.yml
roles/nova-control/tasks/monitoring.yml
roles/percona-server/defaults/main.yml
roles/percona-server/tasks/monitoring.yml
roles/rabbitmq/defaults/main.yml
roles/rabbitmq/tasks/monitoring.yml
roles/swift-common/defaults/main.yml
roles/swift-common/tasks/monitoring.yml

We'll now have the ability to set the alert level of each sensu check

[WIP] Add criticality variable to all sensu checks

---

roles/nova-data/meta/main.yml
roles/nova-data/tasks/main.yml
roles/nova-data/tasks/serverspec.yml
roles/nova-data/templates/etc/serverspec/kvm_spec.rb

WIP: Add the kvm serverspec

---

roles/common/tasks/ssl.yml
roles/common/templates/etc/hosts
roles/nova-common/templates/etc/nova/nova.conf
roles/nova-data/tasks/libvirt.yml
roles/nova-data/tasks/main.yml
roles/nova-data/tasks/ssh.yml
roles/nova-data/templates/root/ssh/known_hosts
roles/nova-data/templates/var/lib/nova/ssh/known_hosts

This builds on top of Paul D's already working pull request and adds another commit to simplify it a bit.

Live migration using SSH for cinder-backed instances

---

roles/rabbitmq/meta/main.yml
roles/rabbitmq/tasks/main.yml
roles/rabbitmq/tasks/serverspec.yml
roles/rabbitmq/templates/etc/serverspec/rabbitmq_spec.rb

WIP: Add the rabbitmq serverspec

---

roles/cinder-data/tasks/monitoring.yml

(cherry picked from commit 39716ed2e4656bab69cf1ff6b4b7eac5b19f3415)

Don't install vg-metrics check when not using vg (2.0.x)

---

roles/glance/templates/etc/glance/policy.json

(cherry picked from commit e80e2fa98b4016fad91f6c1772f0b8313ffb5f0c)

allow cloud_admin to publicize images (2.0.x)

---

envs/example/defaults-2.0.yml

It's under a lot of pressure and needs some time off to sort through its
life.

Stop using bluebox gem mirror for now

---

site.yml

fail on any errors

---

roles/common/defaults/main.yml
roles/common/tasks/monitoring.yml

Dependency on pr : https://github.com/blueboxgroup/ursula/pull/1624

Sensu check for static route multi subnet

---

envs/example/defaults-2.0.yml
envs/example/standard/hosts
library/ceph_bcache.py
roles/ceph-common/defaults/main.yml
roles/ceph-osd/tasks/bcache.yml
roles/ceph-osd/tasks/main.yml
roles/ceph-osd/tasks/standard.yml

This PR adds support for a Bcache Ceph cluster.

ceph osd bcache

---

roles/common/tasks/monitoring.yml

Reviewed in https://github.com/blueboxgroup/ursula/pull/1665

Force enable sensu-client

---

roles/horizon/tasks/main.yml

(cherry picked from commit 8351f1365839c692a5dbf939ab77c3585579dcd3)

Enable force copy for custom horizon logo images

---

roles/neutron-data-network/tasks/main.yml

This one is related to l3ha, gotta axe it to get it to come up with new
code.
(cherry picked from commit faafab27f83a3350e6a8eeb4b687932b0e0e233f)

Kill another neutron process on upgrade (2.0.x)

---

roles/neutron-data-network/tasks/main.yml

This one is related to l3ha, gotta axe it to get it to come up with new
code.

Kill another neutron process on upgrade

---

roles/apache/meta/main.yml
roles/apache/tasks/serverspec.yml
roles/keystone/meta/main.yml
roles/keystone/tasks/serverspec.yml

These got missed in the big change earlier.

Remove keystone and apache role deps on serverspec

---

roles/openstack-setup/tasks/images.yml

Wanted to do this via os_image but hit a bug and wanted to get this in before I'm out for medical early next week
comments in https://github.com/blueboxgroup/ursula/pull/1680

Fixes glance image download only when needed

---

envs/example/defaults-2.0.yml
library/keystone_federation_mapping.py
library/keystone_federation_protocol.py
library/keystone_group.py
library/keystone_identity_provider.py
library/keystone_role.py
roles/client/defaults/main.yml
roles/client/tasks/main.yml
roles/horizon/defaults/main.yml
roles/horizon/tasks/main.yml
roles/horizon/templates/etc/openstack-dashboard/local_settings.py
roles/keystone-defaults/defaults/main.yml
roles/keystone-setup/tasks/federation.yml
roles/keystone-setup/tasks/main.yml
roles/keystone/tasks/federation.yml
roles/keystone/tasks/main.yml
roles/keystone/templates/etc/apache2/sites-available/keystone.conf
roles/keystone/templates/etc/keystone/keystone-paste.ini
roles/keystone/templates/etc/keystone/keystone.conf
roles/keystone/templates/etc/keystone/sso_callback_template.html

Rebase of https://github.com/blueboxgroup/ursula/pull/1658 in @lihkin213's absence.

Federation rebase

---

roles/common/tasks/kernel-tuning.yml

set permissions of /var/crash to 0775

---

roles/horizon/tasks/main.yml
roles/keystone-defaults/defaults/main.yml
roles/keystone-setup/tasks/federation.yml
roles/keystone-setup/tasks/main.yml

Non-critical, will just make the Ansible 2.0 move easier.

Formatting fixes from keystone federation changes

---

roles/common/defaults/main.yml
roles/common/templates/etc/serverspec/os_spec.rb
roles/keystone/templates/etc/keystone/uwsgi/keystone-admin.ini
roles/keystone/templates/etc/keystone/uwsgi/keystone-main.ini
roles/nova-data/templates/etc/serverspec/kvm_spec.rb
roles/rabbitmq/templates/etc/serverspec/rabbitmq_spec.rb

So that we can get this through CI quicker.

Roll up all the existing un-rebased spec fixes into one PR

---

roles/heat/templates/etc/heat/policy.json

fixes defect where admin could not list services

updated heat policies as per kilo/stable

---

roles/rabbitmq/templates/etc/serverspec/rabbitmq_spec.rb

Fixing rabbitmq serverspec

---

roles/client/defaults/main.yml

(cherry picked from commit 679bf5e57d27a3fe0ee9d2bc7406c3e5949c2f7e)

Pin ironic/heat client versions (2.0.x)

---

library/ceph_bcache.py

Set check_rc to True for early failure detection.

Set check_rc to True

---

roles/cinder-common/templates/etc/cinder/cinder.conf

host = cinder is needed in cinder.conf

add parameter 'host' in cinder.conf

---

roles/cinder-common/defaults/main.yml
roles/cinder-common/templates/etc/cinder/cinder.conf

We don't want this on upgrade just yet.

Feature flag common cinder volume name

---

roles/keystone/tasks/main.yml
roles/keystone/templates/etc/apache2/sites-available/keystone.conf

Added keystone-federation tag to update apache keystone conf

Enable the update of the OIDCSSLValidateServer for OIDC federation

---

roles/common/tasks/main.yml
roles/common/tasks/system-tools.yml

(cherry picked from commit ef2e742159f62abc00eddaa118701ab3bc7594c5)

prevents hwraid and mcelog from attempting install on ppc64el

---

library/os_subnet.py

We need an updated os_subnet, and getting it into our fork of ansible
modules core is just too much to deal with at this point. Just vendoring
the damn thing.

Fix subnet updating

---

roles/common/tasks/monitoring.yml
roles/monitoring-common/defaults/main.yml

This patch changes the parameters for the sensu CPU check to be
variable controlled rather than hardcoded and increases the crit
level for the sensu CPU check from 90 to 99.

update cpu check

---

roles/ceph-compute/tasks/main.yml

These files do not need to be world readable.

Hide ceph secrets from the world

---

roles/endpoints/defaults/main.yml
roles/haproxy/templates/etc/haproxy/haproxy_openstack.cfg

Fix OpenID Connect handshake redirection issue backport to 2.1.x

---

roles/common/templates/etc/serverspec/os_spec.rb

Added serverspec entry for UMASK value

Added server spec for UMASK Value

---

playbooks/neutron-l3-noha-to-ha.yml

Change the 'ha' property to be true on existing routers

WIP: playbook for l3-nonha-to-ha migration

---

roles/logging/tasks/main.yml
roles/nova-data/tasks/libvirt.yml
roles/openstack/tasks/main.yml
share/common
site.yml

Adding hard pip dependencies so that we can create a new 1.0 node.

Add some hard pip dependencies

---

roles/mongodb-common/tasks/main.yml
roles/mongodb-common/tasks/serverspec.yml
roles/mongodb-common/templates/etc/serverspec/mongodb_spec.rb

MongoDB tech spec did not have a corresponding server spec check. This adds that.

Add ServerSpec check for mongodb

---

roles/glance/defaults/main.yml

The client is needed in the virtualenv.

Make sure glance + swift still works

---

site.yml

Instead of running on "all", which would loop multiple times, only do it
for host localhost.

Force gathering of facts only once

---

plugins/vars/default_vars.py

Defaults file was not getting loaded correctly since tuple was being returned

load_config_file now returns tuple

---

playbooks/neutron-l3-noha-to-ha.yml

(cherry picked from commit 619fa5b47af11fa749d0ce5b2b94faa91aec30aa)

Playbook for l3-nonha-to-ha migration

---

roles/nova-common/templates/etc/nova/nova.conf

use ansible_processor fact in place of ansible_processor_vcpus

---

roles/ceilometer-control/tasks/main.yml
roles/ceilometer-data/tasks/main.yml
roles/cinder-control/tasks/main.yml
roles/cinder-data/tasks/main.yml
roles/glance/tasks/main.yml
roles/heat/tasks/main.yml
roles/horizon/tasks/main.yml
roles/ironic-control/tasks/main.yml
roles/keystone/tasks/main.yml
roles/magnum/tasks/main.yml
roles/neutron-control/tasks/main.yml
roles/neutron-data-network/tasks/main.yml
roles/neutron-data/tasks/main.yml
roles/nova-control/tasks/main.yml
roles/nova-data/tasks/ssh.yml
roles/openstack-package/tasks/main.yml
roles/openstack-source/tasks/main.yml
roles/stop-services/tasks/main.yml
roles/swift-account/tasks/main.yml
roles/swift-container/tasks/main.yml
roles/swift-object/tasks/main.yml
roles/swift-proxy/tasks/main.yml
upgrade.yml

Need to gather the facts correctly
Work around Ansible bug of set_fact + run_once as first task
Need to handle services that may not be present
Use a better setup for validating nova ssh
Add code to upgrade ceilometer

Improve upgrades with packages

---

roles/nova-data/tasks/ssh.yml
upgrade.yml

- Work around ansible bug with role parents getting variables
- Deal with root ssh known_hosts being a symlink

Additional fixes for upgrades

---

roles/swift-common/defaults/main.yml
roles/swift-common/handlers/main.yml

Add the install type handler for swifttool
Remove swifttool outside of venv

Changes to install swifttool in venv

---

envs/example/defaults-2.0.yml
library/keystone_service.py

Our module was bad, and it should feel bad.

Make keystone service addition idempotent again.

---

roles/nova-common/defaults/main.yml

remove ec2 support

---

roles/swift-account/handlers/main.yml
roles/swift-account/tasks/main.yml
roles/swift-container/handlers/main.yml
roles/swift-container/tasks/main.yml
roles/swift-object/handlers/main.yml
roles/swift-object/tasks/main.yml
roles/swift-proxy/handlers/main.yml
roles/swift-proxy/tasks/main.yml

Attemp to start services only when service ring file exists. The error was hidden until following PR #1868 was merged.

Attempt to start services when required ring file exists

---

requirements.txt

Point at master branch of CLI

---

library/keystone_service.py
library/rabbitmq_user.py
library/sensu_check.py
library/sensu_metrics_check.py
roles/neutron-common/defaults/main.yml

Something broke in Ansible 2.1.0.0 and this is both the work around, and
the suggested way to handle boolean choices.

Fixes for Ansible 2.1

---

roles/neutron-common/defaults/main.yml
roles/neutron-common/templates/etc/neutron/dhcp_agent.ini
roles/neutron-common/templates/etc/neutron/l3_agent.ini
roles/neutron-common/templates/etc/neutron/metadata_agent.ini
roles/neutron-common/templates/etc/neutron/neutron.conf
roles/neutron-common/templates/etc/neutron/plugins/ml2/ml2_plugin.ini

Initial PR for fixing neutron configurations for migration to Mitaka.

Updated neutron configs for mitaka

---

roles/glance/templates/etc/glance/policy.json

Pulled in community's changes for Mitaka

updated glance policy with mitaka community rules

---

roles/neutron-common/templates/etc/neutron/policy.json

Also cleaned up our custom rules for readability and consistency.

WIP: updated neutron policy with mitaka community rules

---

library/ceph_bcache.py

Make sure disks is a list

---

roles/percona-server/templates/etc/serverspec/mysql_spec.rb

mysql serverspec

---

roles/ceph-monitor/tasks/main.yml
roles/ceph-osd/tasks/bcache.yml
roles/ceph-osd/tasks/main.yml
roles/ceph-osd/tasks/standard.yml
roles/ceph-osd/tasks/system_tuning.yml

Fix Ansible Deprecated Messages

---

library/sensu_check_dict.py
roles/logging/meta/main.yml
roles/logging/tasks/checks.yml
roles/logging/tasks/main.yml
roles/sensu-check/defaults/main.yml
roles/sensu-check/handlers/main.yml
roles/sensu-check/tasks/main.yml

This should allow for more easily customized sensu checks without needing to modify ursula itself.
This pattern has been previously implemented elsewhere and is in production.

sensu_check_dict - data driven sensu check configurations

---

library/lvol.py
roles/manage-disks/tasks/main.yml

Vendor in the latest upstream lvol module, as it adds a toggle for
shrinking. We don't want our volumes to shrink. This is mostly due to
this issue: https://github.com/ansible/ansible-modules-extras/issues/428
This vendored module can go away when Ansible 2.2 is out and we update
our requirements.

Prevent volume shrinkage

---

playbooks/ci-allinone/tasks/create.yml
playbooks/ci-allinone/tasks/delete.yml
playbooks/neutron-l3-noha-to-ha.yml
roles/ceph-osd/tasks/bcache.yml
roles/common/tasks/networking.yml
roles/rabbitmq/tasks/cluster.yml

This took a lot of regex. :)
`with(?!_fileglob)[\w_]+: (?!"\{\{.*\}\}")(.*)`

[WIP] Fix possible loop deprecation warnings

---

roles/common/templates/etc/sshd_config

Rebased PR #1912
Please close #1912 when merged

Use secure Cipers and MACs for ssh

---

upgrade.yml

When upgrading major versions, hit rabbit too.

Upgrade rabbit for security

---

roles/horizon/defaults/main.yml
roles/horizon/tasks/main.yml

Put custom icons in the right path
Pull in customization module for source installs.

A couple fixes for horizon

---

envs/example/ci-full/group_vars/all.yml
envs/example/ci/group_vars/all.yml
roles/horizon/templates/etc/openstack-dashboard/local_settings.py
roles/keystone-defaults/defaults/main.yml
roles/keystone-setup/tasks/ldap.yml
roles/keystone-setup/tasks/main.yml
roles/keystone/tasks/ldap.yml
roles/keystone/tasks/main.yml
roles/keystone/templates/etc/keystone/domains/keystone.domain.conf
roles/keystone/templates/etc/keystone/keystone.conf

LDAP will not function without keystone/domain file in place

Keystone multiple domains

---

roles/ceilometer-common/defaults/main.yml
roles/cinder-common/defaults/main.yml
roles/heat/defaults/main.yml
roles/horizon/defaults/main.yml
roles/keystone-defaults/defaults/main.yml
roles/magnum/defaults/main.yml
roles/neutron-common/defaults/main.yml
roles/nova-common/defaults/main.yml
roles/swift-common/defaults/main.yml

Upper constraints will keep us safe.
Change-Id: I7913c9430f2c395126061c1edc5304e257e9367c

Drop all the pinned requirements

---

site.yml

First pass, others may get the same treatment.
Change-Id: Iacfbca1f1743379dc1824c8cb932477fdb4f8d65

Use free strategy where possible

---

roles/common/defaults/main.yml
roles/common/tasks/monitoring.yml

Fixed the input to match Craig's requests for the python sensu script.
This is paired with Ursula-Monitoring PR#81 - https://github.com/blueboxgroup/ursula-monitoring/pull/81

Change LRO Sensu Input To Boolean

---

roles/memcached/tasks/monitoring.yml

@j2sol sorry man, forgot this gem install after doing a double-check of my work.

retry on gem install

---

roles/neutron-data/tasks/main.yml

Change-Id: Ia064ff439fb451dbaa447e33ba3ac37c012d0303

Install ebtables for linuxbridge

---

envs/example/defaults-2.0.yml

2.2.1 release, independent of ursula release.

Change monitoring to 2.2.1 release

---

upgrade.yml

Change-Id: I2a8b4c59f5b20812f7f841bff28becaf8987e10a

Kill more clients, because its fun!

---

roles/swift-common/defaults/main.yml

Bump swifttool version default

---

roles/openstack-setup/tasks/main.yml
upgrade.yml

Fix ring def perms during upgrade and run swift dispersion during upgrade

Issue where dispersion sensu check failed

---

test/setup

passthrough arguments for test/setup

---

roles/keystone/templates/etc/keystone/policy.json

Allow user to update its own properties in identity

---

playbooks/cinder-upgrade.yml
upgrade.yml

(cherry picked from commit 45d9c87938aaf670815c3abe814bc0e4fea8f5d2)

conditionally upgrade cinder (3.0.x)

---

roles/common/templates/etc/serverspec/os_spec.rb

(cherry picked from commit 81425531d831177c01fa249cbcab6dcf6ba7fa88)
Change-Id: Ibbe109b5ade52677590e2f8f70c477a296dfa497

updated os serverspec (3.0.x)

---

envs/example/ci-full/group_vars/all.yml
roles/neutron-data-network/files/etc/neutron/lbaas_templates/haproxy.loadbalancer.j2
roles/neutron-data-network/files/etc/neutron/lbaas_templates/haproxy_base.j2
roles/neutron-data-network/files/etc/neutron/lbaas_templates/haproxy_proxies.j2
roles/neutron-data-network/tasks/main.yml
roles/neutron-data-network/templates/etc/neutron/neutron_lbaas.conf

This backports the various commits required to increase the connection limits for load balancers.

Increase lbaas connection limit (3.0.x)

---

roles/cinder-data/tasks/monitoring.yml

disable cinder-vg-metrics" check if ceph is enabled and ceph is a cinder backend

disable cinder-vg-metrics" check 

---

envs/example/defaults-2.0.yml
playbooks/tests/tasks/ironic.yml
playbooks/tests/tasks/main.yml
site.yml

Basic test to verify ironic api and conductor services are running.

add ironic test

---

.gitignore
library/cinder_volume_type.py

Two commits from arrrsula
One trivial commit to the gitignoree
One that enahnces the cinder volume type module

Arrrsula unfork

---

roles/haproxy/templates/etc/haproxy/haproxy_openstack.cfg
roles/horizon/templates/etc/openstack-dashboard/local_settings.py
roles/keystone-defaults/defaults/main.yml
roles/keystone/tasks/openidc.yml
roles/keystone/templates/etc/apache2/openidc/metadata/template.client
roles/keystone/templates/etc/apache2/openidc/metadata/template.conf
roles/keystone/templates/etc/apache2/openidc/metadata/template.provider
roles/keystone/templates/etc/apache2/sites-available/keystone.conf
roles/keystone/templates/etc/keystone/keystone.conf

Added functionality for federating with multiple OIDC Providers.

Added feature for multiple oidc federation

---

roles/serverspec/defaults/main.yml

fixes defect https://jazzop27.rtp.raleigh.ibm.com:9443/ccm/web/projects/BlueBox%20Cloud#action=com.ibm.team.workitem.viewWorkItem&id=212317

Update to later matching versions of rspec and rspec-core 

---

envs/example/defaults-2.0.yml

Testing a mirror change for Myles
Change-Id: I9cad6cbe3f2b3039e880371c98cf66e429f3e32f

Change ubuntu mirror url

---

roles/ceph-common/tasks/main.yml
roles/ceph-common/tasks/upgrade_flags.yml
roles/ceph-compute/meta/main.yml
roles/ceph-osd/tasks/main.yml

`upgrade_flags.yml` should be run once against each host

detecting ceph upgrade should be executed only once

---

roles/keystone/tasks/monitoring.yml
roles/nova-control/tasks/monitoring.yml
roles/swift-common/tasks/monitoring.yml

These add a few plugins created in https://github.com/blueboxgroup/ursula-monitoring/pull/96 to report various data into graphite.

Add new cloud metrics plugins

---

roles/common/tasks/hwraid-ppc.yml
roles/common/tasks/main.yml
roles/common/templates/monitoring/sensu-sudoers

Add hwraid utilities for ppc, and their associated sudoers rules.

Enable hwraid for ppc

---

roles/endpoints/defaults/main.yml

This may be better than just hitting /
Change-Id: I363b6019d2174129b8dfe179e247a9833e1318c2

Use healthcheck for keystone haproxy checking

---

playbooks/reboot_cluster.yml

Add reboots of ceph and swift nodes, and breakout reboots of controllers and compute nodes.

[WIP] refactor cluster reboot playbook

---

roles/common/tasks/monitoring.yml
roles/monitoring-common/defaults/main.yml

All the disks we care about will be watched individually.
Change-Id: I41d92c997d3599cb67aa6b525e7297b7fb6ebc46

Drop the global disks check

---

roles/nova-common/defaults/main.yml

Change-Id: I503fbe64b24fe64493738bb9c84e7de24c9b1e53

libvirt bumped, we gotta bump here too

---

roles/keystone/tasks/ldap.yml

Change-Id: I8b311568901c5c97cdc2a9104f0f9b119faef10f

Use correct name for keystone handler

---

roles/percona-server/handlers/main.yml
roles/percona-server/tasks/main.yml

Change-Id: Ie3661c0ea47c136c23702dded6681789358f2566

Restart mysql on replication changes

---

roles/glance/defaults/main.yml
roles/glance/templates/etc/collectd/plugins/glance.conf
roles/glance/templates/etc/cron.d/glance-image-sync
roles/glance/templates/etc/glance/glance-api-paste.ini
roles/glance/templates/etc/glance/glance-api.conf
roles/glance/templates/etc/glance/glance-registry-paste.ini
roles/glance/templates/etc/glance/glance-registry.conf
roles/glance/templates/etc/glance/glance-swift-store.conf
roles/glance/templates/etc/glance/glance_api_audit_map.conf
roles/glance/templates/etc/glance/policy.json
roles/glance/templates/etc/rsyncd.conf
roles/glance/templates/etc/serverspec/glance_spec.rb

Add ansible_managed headers to all config files
Remove deprecated config entry for showing image locations
Change-Id: Iffc4f84ba0ae3a9f4c419b78ba2782191f0798f7

Update glance for Newton

---

roles/heat/templates/etc/heat/heat.conf
roles/heat/templates/etc/heat/policy.json

- Add toggle for volume backups
- Update policy files from upstream (requires keystone change)
Change-Id: Iaf6af76edfb163a6a84765f9f6f901a3021f6f8e

Update heat for Newton

---

roles/keystone-defaults/defaults/main.yml
roles/keystone/templates/etc/keystone/keystone.conf
roles/keystone/templates/etc/keystone/policy.json

- Use pyldap instead of python-ldap (py3 compat)
- Configure admin_project_[name,domain_name]
- Update database connection config section
- Update policy file from upstream
Change-Id: I58c6c8461f9c31e2d9f36665f8e6f16be40b047b

Keystone updates for Newton

---

requirements.txt

Change-Id: I4639126c04aa2127b06e231f4669369fe6624d60

Looks like Ansible 2.2 has broken us somewhere

---

plugins/vars/default_vars.py

`group_vars` is not defined anymore
`inv_vars` is the new variable set

change return from group_vars to inv_vars

---

playbooks/reboot_cluster.yml

increase timeout for reboots, delay healthchecks and retry less

increase timeout for reboot, and streamline healthchecks

---

roles/aodh/tasks/main.yml

cherry pick from master branch

add a ufw allow rule for aodh port

---

roles/common/defaults/main.yml
roles/common/tasks/main.yml

backport for https://github.com/blueboxgroup/ursula/pull/2311

set baud rate for main serial port

---

roles/neutron-common/defaults/main.yml
roles/neutron-common/templates/etc/neutron/neutron.conf

Make max_subnet_host_routes configurable during deployment.

Make max_subnet_host_routes configurable

---

roles/keystone/tasks/monitoring.yml

cherry pick from https://github.com/blueboxgroup/ursula/pull/2317 to release 3.1.x branch

update keystone-token-expire check interval

---

roles/percona-server/templates/etc/serverspec/mysql_spec.rb

- no serverspec scan for gcache related files
- restart mysql

fix mysql serverspec to avoid gcache.page by:

---

roles/horizon/templates/etc/openstack-dashboard/local_settings.py

Fix typo in local_settings.py for SECURE_PROXY_SSL_HEADER

---

roles/preflight-checks/tasks/network.yml
roles/preflight-checks/tasks/subnet.yml

Change preflight check to skip new networks and subnets yet to be created.

Fix neutron preflight check

---

library/sensu_check_dict.py

new added ucarp_node_only should be type of bool

fix sensu_check_dict.py ansible library

---

roles/common/tasks/networking.yml
roles/common/templates/etc/ucarp/vip-nnn.conf
roles/neutron-data-network/tasks/main.yml
roles/neutron-data-network/templates/usr/local/libexec/ucarp-vip-down
roles/neutron-data-network/templates/usr/local/libexec/ucarp-vip-up

Ubuntu's ucarp implementation automatically does this, and some of our tooling is dependent on it.

[WIP] add :ucarp label to ucarp address on CentOS

---

envs/example/allinone-centos/group_vars/all.yml

[WIP] Add all-in-one CentOS env w/ Cinder.  

---

roles/neutron-data-network/tasks/main.yml

neutron typo fix

---

roles/audit/defaults/main.yml
roles/audit/handlers/main.yml
roles/audit/tasks/main.yml
roles/audit/templates/etc/audisp/plugins.d/syslog.conf
roles/audit/templates/etc/audit/rules.d/audit_default.rules
site.yml

Add configuration to set up audit with rules
and send audit events to syslog.

Setup auditd

---

roles/common/tasks/networking.yml

- writes network config templates 
- supports Redhat/CentOS and Ubuntu

Add RHOSP network template automation

---

roles/audit/defaults/main.yml
roles/audit/handlers/main.yml
roles/audit/tasks/main.yml
roles/audit/templates/etc/audisp/plugins.d/syslog.conf
roles/audit/templates/etc/audit/rules.d/audit_default.rules
site.yml

Add configuration to set up audit with rules
and send audit events to syslog.

Setup auditd for RELEASE-3.1.x

---

roles/common/defaults/main.yml
roles/common/tasks/networking.yml
roles/common/tasks/ucarp.yml
roles/common/templates/usr/local/libexec/ucarp-vip-down
roles/common/templates/usr/local/libexec/ucarp-vip-up

sets up and enables ucarp
only required for RHOSP

Add RHOSP ucarp automation

---

envs/example/ci-full-rhel/group_vars/all.yml
envs/example/ci-full-rhel/group_vars/ceph_monitors.yml
envs/example/ci-full-rhel/group_vars/ceph_osds.yml
requirements.txt
roles/common/tasks/main.yml
roles/rhn-subscription/defaults/main.yml
roles/rhn-subscription/tasks/main.yml
site.yml

A new role to handle host subscription to RHN.

Host Subscription to RHN.

---

envs/example/vagrant.yml
roles/horizon/defaults/main.yml
roles/horizon/meta/main.yml
roles/horizon/tasks/main.yml
roles/horizon/templates/etc/httpd/conf.d/openstack-dashboard.conf
roles/horizon/templates/etc/openstack-dashboard/local_settings.py
roles/memcached/tasks/main.yml
roles/memcached/templates/etc/sysconfig/memcached

Configure horizon to work with OSP packages.

enable horizon for OSP packages

---

roles/cinder-data/tasks/main.yml

Removed duplicate code for start cinder-volume

---

roles/horizon/tasks/main.yml

When condition was missing "and" which was breaking the play. In addition, fixed syntax on other when conditions to make it more readable.

Fix when condition for custom logo.

---

envs/example/allinone-centos/group_vars/all.yml
envs/example/ci-full-centos/group_vars/all.yml
envs/example/ci-full-rhel/group_vars/all.yml
roles/common/defaults/main.yml
roles/common/tasks/monitoring.yml
roles/common/tasks/python.yml
roles/common/tasks/system-tools.yml
roles/repos/tasks/yum.yml

Intention behind this refactoring of common role defaults was to reduce input needed for Centos/RHOSP in all.yml

Refactor common default based on ansible_os_family dict.

---

roles/common/tasks/ssl.yml

Refresh ca trust on rhel/centos.

Update ca trust on rhel/centos.

---

envs/example/defaults-2.0.yml
roles/horizon/defaults/main.yml
roles/horizon/templates/etc/openstack-dashboard/local_settings.py
roles/keystone-defaults/defaults/main.yml
roles/keystone/templates/etc/keystone/keystone-paste.ini
roles/keystone/templates/etc/keystone/keystone.conf

This commit enables the Keystone security compliance
feature for password complexity, strengthens the default passwords,
removes the jellyroll password validator from the pipelines, and adds the
horizon validator.

Enable Password Complexity Compliance

---

envs/example/defaults-2.0.yml

pull in the inspec sensu plugin.

Pull in  the latest ursula-monitoring plugins

---

envs/example/allinone-rhel/group_vars/all.yml
envs/example/allinone-rhel/hosts
envs/example/allinone-rhel/playbooks
envs/example/allinone-rhel/vagrant.yml

Add working configs for rhel based allinone

Add allinone-rhel env

---

envs/example/defaults-2.0.yml

Remove dups from defaults-2.0.yml

---

roles/neutron-data-network/tasks/monitoring.yml

adding rhel case for sensu check-ucarp-failover

---

envs/example/defaults-2.0.yml
roles/apache/defaults/main.yml
roles/apache/tasks/main.yml
roles/client/templates/root/stackrc
roles/common/tasks/ssl.yml
roles/glance/tasks/main.yml
roles/heat/tasks/main.yml
roles/keystone-defaults/defaults/main.yml
roles/keystone/templates/etc/apache2/sites-available/keystone.conf
roles/logging/meta/main.yml
roles/logging/tasks/filebeat.yml
roles/nova-data/tasks/main.yml
roles/percona-common/tasks/main.yml
roles/repos/defaults/main.yml

Fixes ubuntu CI after centos -> master merge.

fix ubuntu CI

---

roles/ceilometer-common/defaults/main.yml
roles/ceilometer-common/templates/etc/ceilometer/ceilometer.conf

backport of https://github.com/blueboxgroup/ursula/pull/2447

Metering.sample queues grows in a larger environment.

---

roles/ceilometer-common/tasks/main.yml

Ensure changes to config files are picked up by the ceilometer services.

Trigger ceilometer service restart on config change.

---

playbooks/tests/tasks/integration.yml

Reverts blueboxgroup/ursula#2464

Revert "Fix Google Ping Test"

---

playbooks/rhn_unsubscribe.yml

infra for ci so we can clean up after ourselves. tested in tardis, looks good.

Add unsubscribe playbook for ci

---

roles/apache/defaults/main.yml
roles/apache/tasks/main.yml
roles/keystone/templates/etc/apache2/sites-available/keystone.conf

Added start service with enabled: True to ensure service is enabled to auto-start on reboot.
Also, cleaned up variable to be more scope specific in defaults.

Enable apache to auto-start on reboot.

---

roles/neutron-common/tasks/main.yml
roles/neutron-data-network/tasks/main.yml
roles/neutron-data/tasks/main.yml

TLDR; yes, we need all these packages.

Address package FIXME comments in Neutron roles

---

envs/example/allinone-rhel/group_vars/all.yml
envs/example/ci-full-centos/group_vars/all.yml
envs/example/ci-full-rhel/group_vars/all.yml
roles/common/tasks/python.yml
roles/common/tasks/ssl.yml
roles/keystone-setup/tasks/ldap.yml

this also sets up the base venv for all OS's.

Force SSL certs for RHEL

---

roles/common/defaults/main.yml
roles/neutron-data-network/tasks/main.yml

moving packages to common system-tools. also alphabetical order.

---

roles/haproxy/defaults/main.yml
roles/haproxy/templates/etc/haproxy/haproxy_openstack.cfg
roles/haproxy/templates/etc/haproxy/haproxy_swift.cfg

Increase global maxconn and parameterize existing defaults and mysql setting for performance tunning.

haproxy performance tunning for global maxconn.

---

README.md
coding.md

Please do comment if you disagree on any of the standards. This is a chance for discussion.

Add the start of a coding guideline file.

---

roles/apache/meta/main.yml
roles/apache/tasks/main.yml
roles/ceilometer-common/tasks/main.yml
roles/cinder-common/tasks/main.yml
roles/glance/tasks/main.yml
roles/heat/tasks/main.yml
roles/horizon/tasks/main.yml
roles/horizon/templates/etc/openstack-dashboard/local_settings.py
roles/keystone/tasks/main.yml
roles/neutron-common/tasks/main.yml
roles/nova-common/tasks/main.yml
roles/openstack-meta/defaults/main.yml

Refactored the creation on /etc/openstack-dashboard
copy templates from services to /etc/openstack-dashboard

Added policy files to openstack-dashboard from services

---

roles/aodh/defaults/main.yml
roles/aodh/handlers/main.yml
roles/aodh/meta/main.yml
roles/aodh/tasks/main.yml
roles/aodh/templates/etc/aodh/aodh.conf
roles/ceilometer-common/defaults/main.yml
roles/ceilometer-common/handlers/main.yml
roles/ceilometer-common/meta/main.yml
roles/ceilometer-common/templates/etc/ceilometer/api_paste.ini
roles/ceilometer-control/tasks/main.yml
roles/ceilometer-data/tasks/main.yml
roles/mongodb-common/tasks/main.yml
roles/mongodb-common/templates/etc/mongodb/mongod.conf
roles/openstack-meta/defaults/main.yml

PR enables deployment of mongdb, ceilometer and aodh on rhel/centos hosts.

enable mongodb, ceilometer and aodh for rhosp.

---

roles/rabbitmq/defaults/main.yml
roles/rabbitmq/tasks/main.yml

see: http://rabbitmq.com/install-rpm.html

use systemd to increase rabbit limits

---

roles/ceilometer-common/tasks/main.yml
roles/cinder-common/tasks/main.yml
roles/glance/tasks/main.yml
roles/heat/tasks/main.yml
roles/horizon/tasks/main.yml
roles/keystone/tasks/main.yml
roles/neutron-common/tasks/main.yml
roles/nova-common/tasks/main.yml

This updates the ownership and permissions for OpenStack
services conf files. This is to match the OpenStack security
guidelines.

Update ownership and permissions for OpenStack conf files

---

roles/common/tasks/python.yml

remove duplicate and un-used code.

python.yml code cleanup.

---

test/run

Add 'rhn_unsubscribe' action in test/run.

Add 'rhn_unsubscribe' action in test/run

---

roles/logging/templates/etc/filebeat/filebeat.yml

from filebeat 5.0,  change tls to ssl in conf

fix-filebeat-config

---

roles/glance/templates/etc/glance/glance-api.conf
roles/glance/templates/etc/glance/glance-registry.conf
roles/inspec/defaults/main.yml
roles/neutron-common/templates/etc/neutron/neutron.conf
roles/nova-common/templates/etc/nova/nova.conf

This adds more inspec openstack check for glance, neutron, and nova.
This includes making sure that TLS connections are used between
services.

Add more inspec openstack checks for glance, neutron, and nova

---

roles/common/tasks/networking.yml

Add automation to support mulit-pod deployment for RHOSP

Add RHOSP multi-pod initial changes

---

library/ceph_bcache.py
roles/ceph-osd/tasks/bcache.yml

1.The previous PR is https://github.com/blueboxgroup/ursula/pull/2472
2. Apply previous code to master.

Ceph NVMe Support

---

roles/aodh/defaults/main.yml
roles/cinder-common/handlers/main.yml
roles/common/defaults/main.yml
roles/common/tasks/monitoring.yml
roles/common/tasks/python.yml
roles/common/tasks/system-tools.yml
roles/glance/defaults/main.yml
roles/glance/handlers/main.yml
roles/glance/tasks/image-sync.yml
roles/glance/tasks/main.yml
roles/ironic-common/defaults/main.yml
roles/magnum/defaults/main.yml
roles/nova-common/tasks/main.yml

This PR addresses misc FIXME. There is no functional changes part of this PR.

misc fixme cleanup.

---

envs/example/ci-full-centos/heat_stack.yml

replace hardcoded ci_compute_standard az with heat parameter.

parameterized az for ci-full-centos.

---

roles/swift-common/tasks/monitoring.yml

need to use swift cmd to check, not service name

fix swift process check

---

roles/logging/tasks/checks.yml
roles/logging/tasks/logstash.yml
roles/logging/tasks/main.yml
roles/logging/tasks/monitoring.yml
roles/sensu-check/defaults/main.yml

add sensu-check for filebeat process.

add sensu-check for filebeat process

---

roles/nova-data/tasks/monitoring.yml

it's a defect in Mitaka, Add this check to notify operator to take
action.

add check for nova compute data out of sync

---

roles/common/defaults/main.yml

since check-glance-store need this package.

add python-dateutil pip package for base venv

---

envs/example/defaults-2.0.yml

Do not allow grub config update by openstack-ansible-security.

update the openstack-ansible-security overrides for grub config

---

roles/aodh/tasks/main.yml

Setup the ownership and permissions for aodh as per the security checklist.

set file ownership and permission for aodh as per security guide

---

envs/example/ci-ceph-redhat/group_vars/ceph_osds.yml
envs/example/ci-ceph-swift-rhel/group_vars/ceph_osds_ssd.yml
envs/example/ci-full-rhel/group_vars/ceph_osds.yml
roles/rhn-subscription/defaults/main.yml

Part of switching to new rhn account we also have different subscription pool name to attach to. This PR is adjusting our defaults to align with new pool name.

Switch to new rhn account and subscription pool.

---

roles/common/templates/monitoring/sensu-sudoers
roles/swift-common/defaults/main.yml
roles/swift-common/tasks/monitoring.yml

It's related to a defect in backlog.
1. add insecure option for client self sign cert
2. add criticality option
and it depends on https://github.com/blueboxgroup/ursula-monitoring/pull/140

fix swift dispersion  check

---

playbooks/tests/tasks/ceph.yml
playbooks/tests/tasks/integration.yml

changes:
1. restart ceph services and make sure it comes back to HEALTH_OK
2. reboot ceph osd node, and make sure it comes back to HEALTH_OK
3. create volume
4. attach volume to VM and write to volume in VM
5. detach volume from VM
At last , delete all created resources .

fix ceph unit test

---

roles/common/templates/etc/sysctl.d/60-tcp-tuning.conf
roles/inspec/defaults/main.yml

This fixes 2 inspec check failures that are critical and skips 4 additional checks.

fix additonal inspec checks

---

playbooks/tests/tasks/integration.yml

VM failing ping from dhcp, adding debug outputs

WIP: Add CI debugging  log

---

roles/nova-common/defaults/main.yml

PR adjust to librbd1 version bump in cloud archive mirror.

adjust to bumped librbd1 version in mirror.

---

test.sh

Our Ursula_Test_Ceph_Swift_Ubuntu_Package_Branch_Weekly now depends on this script being present in Ursula.

Backport test.sh to RELEASE-3.1.X for CI job

---

playbooks/tests/tasks/integration.yml

This PR to make the following changes
1. add some check between volume detach and volume deletion. Volume deletion will fail if volume is used and in the progress of detaching.

add delay between detach volume and deleting volume

---

test/common

rollback this change to fix CI broken issue
https://jenkins.ci.blueboxgrid.com/job/Ursula_Test_Rhosp_Master_PRs/297/console

rollback pythonnobuffer

---

test/setup

after novaclient is upgraded, nova secgroup doesn't wok well. replace it by openstack command

use openstack command

---

roles/nova-common/defaults/main.yml

Leverage latest qemu-kvm version from canonical cloud_archive repo for ubuntu clouds.

Use latest qemu-kvm from cloud_archive for ubuntu.

---

roles/common/tasks/ssl.yml

PR fixes missing check around handling of self-signed cert.

fixes from initial ubuntu based deploy.

---

playbooks/tests/tasks/integration.yml

add 60s timeout for ssh to avoid timeout failure

add 60s timeout for ssh

---

roles/common/tasks/ntp.yml

Cherry pick from https://github.com/blueboxgroup/ursula/pull/2709

ntpd start on boot rhel

---

playbooks/tests/tasks/rally.yml

rally installation  will fail under interactive. In this PR, add env noninteractive

fix rally installation

---

playbooks/tests/tasks/rally.yml
playbooks/tests/tasks/rally/bbc-cloud-validate-ceph.yml
playbooks/tests/tasks/rally/bbc-cloud-validate.yml
playbooks/tests/tasks/rally/run.sh
test/common

Fix defect 384858:
https://jazzop27.rtp.raleigh.ibm.com:9443/ccm/web/projects/BlueBox%20Cloud#action=com.ibm.team.workitem.viewWorkItem&id=384858
Includes:
1. Fixed issue in task "neutron-control : sync neutron database for lbaas" by changing cmd to "neutron-db-manage --subproject neutron-lbaas --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_plugin.ini upgrade head".
2. Synced rally related tasks with master branch.
3. Synced testenv_instance_prefix in test/common with master branch.
Job ran locally passed.

Fix issues of ubuntu branch weekly job on RELEASE-3.1.x

---

playbooks/ci-ceph-redhat/tasks/pre-deploy.yml
playbooks/ci-ceph-swift-rhel/tasks/pre-deploy.yml
playbooks/ci-full-rhel/tasks/pre-deploy.yml

Update device eth0 interface configuration, prevent networkmanager from controlling eth0

prevent networkmanager from controlling eth0

---

test/run
test/setup

sometimes, meet intermit issues to interact with tardis, this PR to make change to reduce unnecessary dependency on tardis

 remove unnecessary dependency on tardis

---

playbooks/tests/tasks/integration.yml
tmp/.gitignore

wait for volume to be available before attach volume to server

check volume available before attach

---

playbooks/tests/tasks/rally/run.sh
roles/nova-common/defaults/main.yml

1. cherry pick the two commits
e9c5cb6
8538d69
2. update kvm version

fix  nighty build of branch3.1

---

roles/swift-common/tasks/main.yml

fix the description of swift-common

fix playbook description

---

roles/openstack-network/handlers/main.yml

floating ip can't be pingable. Found that the traffic is NAT in controller node.

fix floating ping issue

---

roles/common/tasks/monitoring.yml
roles/common/templates/monitoring/sensu-sudoers
roles/monitoring-common/defaults/main.yml
roles/sensu-check/defaults/main.yml

It will be configurable for each env:
— enable/disable check
— threshold for warning/critical
— subdue for time windows

add network traffic monitoring back

---

.gitignore
plugins/vars/default_vars.py

refer to ursula-flotsam/ursla-cleversafe, if  default variable can't be found , print related log

add debug when default variable is not found

---

upgrade.yml

Remove Logstash-forwarder after filebeat is installed from mitaka -> Newton

uninstall logstash-forwarder during upgrade

---

envs/example/defaults-2.0.yml
roles/cinder-common/templates/etc/cinder/cinder_api_audit_map.conf
roles/endpoints/defaults/main.yml

expose endpoints for cinder api v3, update default endpoint to v3.

Expose cinder api v3

---

envs/example/ci-full-ubuntu/group_vars/all.yml

fix  logging configuration in ci-full-ubuntu to avoid ci failure in local env

fix logging configuration

---

envs/example/defaults-2.0.yml
library/mongodb_replication.py
roles/mongodb-arbiter/tasks/main.yml
roles/mongodb-common/defaults/main.yml
roles/mongodb-common/tasks/main.yml
roles/mongodb-common/templates/etc/mongodb/mongod.conf
roles/mongodb-server/tasks/auth_initialization.yml
roles/mongodb-server/tasks/main.yml
roles/mongodb-server/tasks/primary.yml

Enable auth for mongodb

---

roles/keystone-defaults/defaults/main.yml
roles/keystone/tasks/saml.yml
roles/keystone/templates/etc/keystone/keystone.conf
roles/keystone/templates/etc/shibboleth/attribute-map.xml
roles/keystone/templates/etc/shibboleth/idp_metadata.xml
roles/keystone/templates/etc/shibboleth/shibboleth2.xml

This adds more SAML configurations:
1. Make signing auth requests for SAML
2. Add file source for SAML metadata provider
3. Add the name format for the SAML mapping attributes

3.1.x Add additional SAML configurations

---

roles/ceph-monitor/tasks/main.yml
roles/ceph-osd/tasks/main.yml

correct ceph log owner for existing envs

correct ceph log permission on mon/osd nodes

---

roles/repos/defaults/main.yml

Pull Filebeat from our own repo.

change filebeat mirror

---

envs/example/ci-full-centos/group_vars/all.yml
envs/example/ci-full-rhel/group_vars/all.yml
envs/example/defaults-2.0.yml

- Ensure key repos are listed in defaults-2.0.yml
- Enable lbaas for centos and rhel to be consistent with ci-full-ubuntu

Add missing repos to envs and enable lbaas.

---

envs/example/defaults-2.0.yml
roles/cinder-common/templates/etc/cinder/cinder.conf
roles/cinder-control/tasks/main.yml
roles/cinder-control/tasks/v7k_integration.yml
roles/cinder-control/templates/etc/v7k/ssh/id_rsa
roles/openstack-setup/tasks/cinder.yml

V7K configuration

---

envs/example/defaults-2.0.yml

There were couple comments provided in PR 2792 and this PR was merged before I could address those comments. 
This PR is made to address following 2 comments
1: use https for new repos
2: point chef repo to apt-mirror like other repos.

address comments provided in PR 2792.

---

roles/monitoring-common/defaults/main.yml
roles/sensu-check/defaults/main.yml

remove subdue as our sensu infrastructure does not support it yet

Remove subdue for sense-check

---

roles/keystone/tasks/openidc.yml
roles/keystone/templates/etc/apache2/sites-available/keystone.conf

Adding support for OpenID Connect federation to RHEL. Changed the code base to support both ubuntu and RHEL federation integration in Ursula.

support for openidc on rhel and ubuntu

---

playbooks/logging.yml
roles/barbican/defaults/main.yml
roles/barbican/meta/main.yml
roles/barbican/tasks/logging.yml
roles/barbican/tasks/main.yml
roles/barbican/tasks/monitoring.yml

The changes cover:
1.remove redundant system dependencies
2.add monitoring for process check and api check
3.add logging

Barbican monitoring and logging

---

roles/ceph-defaults/defaults/main.yml
roles/ceph-monitor/templates/etc/bbg-ceph-utils/ceph-utils.conf

1. Add tuning configuration for bbg-ceph-utils
2. Decrease max backfills to 1 from 2

CEPH backfill tuning

---

library/ceph_bcache.py

Remove redundant code in ceph_bcache module

remove duplicated code in ceph_bcache module

---

roles/cinder-control/tasks/v7k-monitoring.yml

make sure all disk under configured v7k storage pool are online status

add disk check for v7k

---

site.yml

add environment for roles in playbook site.yml so the http proxy can work with private repository

add environment to all roles in playbook

---

playbooks/tests/tasks/barbican.yml
playbooks/tests/tasks/main.yml

Added the tests which will run after Ursula to check if the
barbican service is installed and works as intended.

Added unit test for Barbican service in Ursula

---

roles/common/templates/monitoring/sensu-sudoers

add check-v7k-drive to sensu-sudoers

add check-v7k-drive to sensu-sudoers

---

roles/neutron-common/templates/etc/neutron/rootwrap-ursula.d/ursula.filters

- Allow permission to for neutron-l3-agent to kill keepalived-state-change process
- Fix router/namespace deletion issue

Fix neutron rootwrap

---

roles/keystone/templates/etc/cron.d/drop-expired-keystone-tokens

grep command is under /bin, need to include it.

Correct PATH for cron job running

---

roles/aodh/defaults/main.yml
roles/aodh/tasks/monitoring.yml

Add aodh check-os-api

---

roles/aodh/defaults/main.yml

there is one regression defect on PR2837, this PR is try to resolve it.

Regression fix for PR2837

---

envs/example/defaults-2.0.yml
roles/openstack-meta/defaults/main.yml
roles/openstack-setup/meta/main.yml
roles/openstack-setup/tasks/flavors.yml

Move nova flavor definition out of defaults-2.0.yml to openstack-meta role defaults.

move nova flavors definition to openstack-meta role defaults.

---

roles/openstack-setup/tasks/users.yml

fix regression caused by PR https://github.com/blueboxgroup/ursula/pull/2781

honor feature enabled flag when creating service endpoints.

---

roles/horizon/defaults/main.yml
roles/horizon/templates/etc/openstack-dashboard/local_settings.py

This PR make some key horizon defaults settings override-able via envs.
example: ability to customize max dropdown items.

make some key horizon attributes tunnable via envs.

---

envs/example/defaults-2.0.yml

use filebeat 5.x version from elastic_5_x repo.

use elastic_5_x repo for filebeat.

---

roles/keystone/tasks/monitoring.yml
roles/nova-control/tasks/monitoring.yml

Keystone related uwsgi process is larger than 10, no need to increase it.

Fix keystone process check threshold

---

roles/logging/tasks/filebeat.yml
roles/logging/tasks/logstash.yml
roles/logging/tasks/monitoring.yml

to cover scenarios about upgrade from logstash-forwarder to filebeat

Remove logstash-forwarder process check

---

envs/example/allinone-rhel/group_vars/all.yml
envs/example/ci-ceph-redhat/group_vars/all.yml
envs/example/ci-ceph-swift-rhel/group_vars/all.yml
envs/example/ci-ceph-ubuntu/group_vars/all.yml
envs/example/ci-full-centos/group_vars/all.yml
envs/example/ci-full-rhel/group_vars/all.yml
envs/example/ci-full-ubuntu/group_vars/all.yml

forward.port have been defined in logging roles as 4561. Should not overwrite this port by 4560

use default filebeat  port 4561

---

envs/example/ci-ceph_swift
playbooks/ci-ceph_swift

remove two symbol links(  envs/example/ci-ceph_swift and  playbooks/ci-ceph_swift).
Since jenkins job have been updated

remove symbol link

---

roles/client/tasks/main.yml
roles/rabbitmq/defaults/main.yml

Back port PR - https://github.com/blueboxgroup/ursula/pull/2879

rabbitmq version bump and self-signed cert handling fix.

---

roles/client/tasks/main.yml

This PR fixes ansible error trying to create symlink in dir that might not exist.

check certifi exists.

---

roles/openstack-setup/tasks/cinder.yml

remove old cinder backup service

remove old cinder backup service

---

roles/common/templates/monitoring/sensu-sudoers

Add check-ilmt-lockstate to sudoer

Add check-ilmt-lockstate to sudoer

---

roles/mongodb-common/tasks/main.yml

The files within this folder were assigned nogroup.

Assign mongodb group ownership to /var/lib/mongodb folder

---

playbooks/install_deb_package.yml

This playbook will install a package to target hosts.
It's immediate use will be for updating the kernel package.

playbook to install a deb package

---

envs/example/ci-ceph-swift-rhel/group_vars/all.yml
envs/example/ci-ceph_swift/group_vars/all.yml
envs/example/defaults-2.0.yml
roles/common/tasks/ssl.yml

New paramiko 2.2 package is breaking swifttool. This PR points to new swifttool pkg that pins paramiko<2.2

bump up swifttool version.

---

roles/mongodb-common/defaults/main.yml

to fix: https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2016-6494

upgrade mongodb for security issue

---

playbooks/tests/tasks/all.yml

nonexistent typo

---

roles/neutron-common/defaults/main.yml
roles/neutron-common/templates/etc/neutron/plugins/ml2/ml2_plugin.ini

cf. https://github.com/blueboxgroup/ursula/pull/2923#issuecomment-316552997

correctly spell ML2

---

playbooks/security-patches.yml

new PR for security updates to address psirt issues

---

roles/rabbitmq/defaults/main.yml

New version for rabbitmq in apt mirror.

Bump rabbitmq server to 3.6.15*

---

playbooks/security-patches.yml

- apt was failing without `http_proxy`
- use service module
- only restart haproxy where needed
- also restart ssh server post-update

some tweaks to security-updates.yml

---

roles/haproxy/templates/etc/haproxy/haproxy_swift.cfg

it may be as simple as this

---

README.md

added Mac OS X specific installation instructions to the top-level README.md file.

README.md updates for Mac Installs

---

roles/keystone/templates/etc/keystone/keystone.conf

This replaces the broken home-baked functionality that worked in previous versions.  Per https://docs.openstack.org/keystone/pike/admin/identity-security-compliance.html

Add password complexity requirements

---

roles/repos/tasks/apt.yml

This tag will allow us to limit a run to just adding new repos/keys

add apt tags
