blueboxgroup/ursula

roles/cinder-common/templates/etc/cinder/cinder.conf

Explicitly define the glance endpoint for Cinder to support creating a volume block from an image on the compute hosts which are not running a local `glance-api` service.

cinder: explicitly define glance host

---

roles/nova-common/defaults/main.yml
roles/nova-data/tasks/libvirt.yml

Specified versions of various packages were valid only for precise, so
this adds support for trusty as well.

Fix nova-compute packages on trusty

---

envs/vagrant/defaults.yml

As Vagrant is really only a test environment, there is no need to use
more than 1 worker where possible.

Update Vagrant evnironments to only have 1 worker

---

playbooks/testenv/tasks/delete.yml

local group doesn't exist at this point, so just call localhost
explicitly since you can do that. Also override the ansible python
interpreter for those that are running a non-standard one.

Make the clean up work again

---

upgrade.yml

Common stuff got upgraded too, so we should run that before any specific
role upgrades.

Gotta run common before the roles

---

roles/neutron-data/tasks/main.yml

OTherwise we may have a cluster that has vxlan as a type but not the
default type. Wouldn't want to fall into that trap.

Check tunnel_types for vxlan

---

roles/cinder-control/tasks/main.yml
roles/glance/tasks/main.yml
roles/ironic-control/tasks/main.yml
roles/keystone/tasks/main.yml
roles/neutron-control/tasks/main.yml
roles/nova-control/tasks/main.yml

Without run_once, all controllers would attempt to sync the db, which
would cause a collision.

Only sync databases once

---

roles/common/tasks/ipmi.yml
roles/common/tasks/kernel-tuning.yml
roles/common/tasks/main.yml
roles/common/tasks/serial-console.yml
roles/common/templates/etc/init/tty_console.conf

Combine with IPMI serial over LAN, adding all serial consoles to the
kernel command line.

Enable serial console on ttyS0

---

roles/common/tasks/ipmi.yml
roles/common/tasks/kernel-tuning.yml
roles/common/tasks/main.yml
roles/common/tasks/serial-console.yml
roles/common/templates/etc/init/tty_console.conf

Combine login getty logic with IPMI serial over LAN, adding all serial
consoles to the kernel command line.
Backporting for upgrades to existing customers with serial consoles.
Conflicts:
roles/common/tasks/main.yml

Backport: Enable serial console on ttyS0

---

roles/glance-common/defaults/main.yml
roles/glance-common/tasks/main.yml

https://bugs.launchpad.net/glance/+bug/1400966
Since stable/havana is dead upstream we had to fork glance and restore
the branch so that we could backport the fix. Manually tested.
(cherry picked from commit bfb0788837c0478afbe14934c58804c4f8bdf1ec)

Update glance to fix directory traversal flaw (0.9.x)

---

roles/glance/defaults/main.yml
roles/glance/tasks/main.yml

https://bugs.launchpad.net/glance/+bug/1400966
Since stable/havana is dead upstream we had to fork glance and restore
the branch so that we could backport the fix. Manually tested.

Update glance to fix directory traversal flaw (1.0.x)

---

roles/glance/defaults/main.yml

This fully fixes the directory traversal bug by addressing the
filesystem:// protocol as well.

Pull in even newer glance stable/juno for security

---

roles/cinder-common/defaults/main.yml
roles/cinder-common/templates/etc/cinder/cinder.conf

enabled_backends and default_backend use broken logic. These should be
unset by default and we should check for None instead of 'is defined'.

Fix enablement of backends accidentally

---

envs/example/defaults.yml
envs/vagrant/defaults.yml
roles/keystone-setup/tasks/main.yml
roles/keystone/templates/etc/keystone/keystone-paste.ini
roles/keystone/templates/etc/keystone/keystone.conf
site.yml

This removes the hard coded static admin_token that we have been leaving enabled in our deploys. Instead it generates a psuedorandom token to be used during a bootstrap of keystone, provided keystone hasn't already been bootstrapped. Then the admin_token_auth method is only enabled long enough to bootstrap.

Utilize a temporary admin_token during bootstrap

---

glance-OSSA-2014-041.1.yml

Not exactly DRY, however this is the safest way to just do the required
parts for mitigating the traversal bug.

Add playbook for glance security fix

---

playbooks/bootstrap_ml2_vxlan.yml

As @j2sol mentioned in https://github.com/blueboxgroup/ursula/pull/740, we don't need this because the neutron-data role handles installing the BlueBox PPA and iproute2.

bootstrap for vxlan doesn't need to install iproute2

---

roles/horizon/defaults/main.yml

The logo needs to be sized different for horizon in icehouse and above.
This new url has the right sized image.

Update horizon logo URL for juno

---

roles/keystone-setup/tasks/main.yml

This is bad, and I should feel bad, but without this we could attempt to
use keystone before it is ready.

Wait for keystone to be happy again after restart

---

roles/keystone-setup/tasks/main.yml

Not sure how this snuck in, but this conditional will always be "true"
because the exists key exists. We need to run it as a bool to check the
/value/ of the key instead so that keystone setup will actually run.

Fix keystone setup false positive

---

roles/cinder-common/handlers/main.yml
roles/cinder-common/meta/main.yml
roles/cinder-control/tasks/main.yml
roles/client/handlers/main.yml
roles/client/meta/main.yml
roles/glance/handlers/main.yml
roles/glance/meta/main.yml
roles/glance/tasks/main.yml
roles/heat/handlers/main.yml
roles/heat/meta/main.yml
roles/heat/tasks/main.yml
roles/horizon/handlers/venv.yml
roles/ironic-common/handlers/main.yml
roles/ironic-control/meta/main.yml
roles/ironic-control/tasks/main.yml
roles/keystone-setup/tasks/main.yml
roles/keystone/handlers/main.yml
roles/keystone/meta/main.yml
roles/keystone/tasks/main.yml
roles/neutron-common/handlers/main.yml
roles/neutron-common/meta/main.yml
roles/neutron-control/tasks/main.yml
roles/nova-common/handlers/main.yml
roles/nova-common/meta/main.yml
roles/nova-control/tasks/main.yml
roles/openstack-source/handlers/main.yml
roles/swift-common/meta/main.yml
roles/swift-common/tasks/main.yml
upgrade.yml

First off, how databases get synced chnaged and so the upgrade script needed to be changed as well. The other commits come from acceptance criteria for the upgrade playbook story.
This has been tested some on a cloud on a cloud scenario.

Improvements to the havana -> icehouse upgrade playbook

---

playbooks/tests/tasks/network.yml

test instances are namespaced now, so we need to just use the ansible
variable for the hostname.

Put networking on the right host

---

playbooks/tests/tasks/controller.yml
playbooks/tests/tasks/network.yml
roles/haproxy/templates/etc/haproxy/haproxy_openstack.cfg
roles/neutron-common/tasks/main.yml
roles/neutron-common/templates/etc/neutron/neutron.conf
roles/openstack-setup/tasks/cinder.yml
roles/openstack-setup/tasks/images.yml
roles/openstack-setup/tasks/networks.yml
roles/openstack-setup/tasks/users.yml

Use provider_admin user for internal actions since customer may change admin user credentials.

Use provider admin

---

library/sensu_check

rewrite of the sensu_check ansible library to python.   
This was done to get an idea of how much work it would be to rewrite the various libraries that use antsy.
I skipped the env_vars portion because we're not actually using it ( that I can see )   but it wouldn't be hard to add it in.

rewrite sensu_check into python

---

roles/neutron-data-network/tasks/main.yml

This will protect against upgrading a cluster that is not ready for
vxlan.

Add vxlan support assertions

---

library/cinder_volume_group

This is to remove dependency on Antsy
While porting this, I've dropped support for pointing
cinder_volume_group at an existing device. Ansible already has a module
for creating volume groups from devices.
Encryption support has been carried forward, although it's preferred to
use built in nova+cinder encryption rather than encrypting a file.

Re-write cinder_volume_group in python

---

roles/common/tasks/monitoring.yml
roles/memcached/defaults/main.yml
roles/memcached/tasks/main.yml
roles/memcached/tasks/monitoring.yml

* memcached gem has no deps, so pull it directly from url.  This means
we don't need to mirror rubygems just to get a single gem.

Sensu should use own embedded ruby

---

playbooks/logging.yml
roles/logging-config/handlers/main.yml
roles/logging-config/meta/main.yml
roles/logging-config/tasks/main.yml
roles/logging/tasks/main.yml

Need a more surgical approach to deploying updates to logging on existing clusters. This playbook facilitates that.
It should probably be extended to also handle logrotate and other logging related items, but this is a start to handle the log shipping.

logging: add surgical playbook

---

ansible.cfg

This uses a single ssh connection per task rather than 3. Could save us
some time.

Enable ssh pipelining in Ansible

---

roles/common/tasks/system-tools.yml

Nothing else will use this so remove the install.
This needs to merge after #791 #790 and #787

Remove antsy install

---

roles/common/tasks/system-tools.yml

Add mcelog for monitoring hardware ECC type errors

system tools: add mcelog

---

site.yml

The iptables role is a fix for UDP checksums on DHCP packets, it should be applied to the network nodes which run neutron DHCP agent rather than the controller nodes. This only affects stacks which are running non-collapsed roles.

iptables: apply iptables DHCP checksum fix to network nodes

---

roles/common/tasks/kernel-tuning.yml

Disable GRUB OS prober so we don't try to boot instance's cinder volumes.

Disable GRUB OS prober

---

playbooks/testenv/tasks/pre-deploy.yml
playbooks/tests/tasks/network.yml

More network role specific tasks miss-categorized as controller.

testenv: move network specific tasks to network nodes

---

envs/example/defaults.yml
envs/vagrant/defaults.yml
roles/keystone/tasks/main.yml
roles/keystone/templates/etc/keystone/keystone.conf

PKI tokens are actually slower and are more complex. A better system
might be coming with kilo, but in the short term there is not a strong
reason to move away from UUID.
This should be backported to 1.1.x as well.

Revert "Enable PKI tokens for keystone"

---

library/cinder_volume_group
roles/cinder-data/tasks/main.yml

Turns out that hd doesn't like it if the device passed in as a
parameter doesn't exist. So, consolidate the is_luks and is_lvm_pm
logic into _is_device_type and add a leading conditional that checks
for the device path's existence.

Fix missing device bug in cinder_volume_group

---

roles/neutron-common/templates/etc/neutron/metadata_agent.ini

Docs say default is 2, but actually its getting NCPUs. 32 is far too
many.

Hard set the supposed metadata agent workers

---

roles/client/defaults/main.yml

This avoids getting 404s on volume attach:
https://bugs.launchpad.net/nova/+bug/1423695
Can be removed when something newer than 2.21.0 ships. Fix is merged to
master but no new pip yet.

Temporarily pin the version of python-novaclient

---

roles/neutron-common/defaults/main.yml
roles/neutron-common/templates/etc/neutron/metadata_agent.ini

The default is not 2 as documented, but NCPUs which can be... large.
Some evidence shows a lot of metadata workers can overwork neutron, so
limit them down.

Limit neutron metadata workers

---

roles/nova-common/templates/etc/nova/nova.conf

This matches the upstream default and does drastically reduce neutron
interface timeouts on builds.

Increase neutron vif plugging timeout to 300

---

library/cinder_volume_group

Don't fail automatically if the cinder-volumes backing file already exists.

allow-previous-cinder-volumes-store

---

roles/common/files/sensu_plugins/check-cinder-sessions.py
roles/nova-data/tasks/monitoring.yml

We want to know when an instance that expects a volume to be mounted
for some reason (netsplit, etc) fails to iscsi mount/loses a mount to
a volume.

Add a cinder sessions check for sensu

---

roles/neutron-common/templates/etc/neutron/metadata_agent.ini

A later PR added configurable metadata_workers and we want to use that
one instead of the hard set 2.

Remove hard set metadata_workers

---

roles/haproxy/defaults/main.yml
roles/haproxy/templates/etc/haproxy/haproxy_openstack.cfg

In larger capacity environments it's possible to have nova generate
requests to neutron that are larger than the haproxy allowed default of
1/2 bufsize (since it has to rewrite). Tuning this up will consume more
memory and reduce capacity though, so it should only be done on larger
systems. This provides an easy way to bump it up from the default when
deemed necessary.

Allow tuning haproxy bufsize

---

roles/cinder-common/templates/etc/cinder/cinder.conf

When a Nimble device sans 2 networks we need to tell it which subnet
to use for the volume's provider_location. This options provides for
that ability.

Set Nimble subnet label when appropriate

---

playbooks/monitoring/tasks/compute.yml
roles/common/files/sensu_plugins/check-cinder-sessions.py

We want to know when an instance that expects a volume to be mounted
for some reason (netsplit, etc) fails to iscsi mount/loses a mount to
a volume.
Conflicts:
roles/nova-data/tasks/monitoring.yml

Backport 1.0 - Add a cinder sessions check for sensu

---

roles/horizon/templates/opt/stack/horizon/openstack_dashboard/local/local_settings.py

For those wanting Keystone v3, we need to set OPENSTACK_API_VERSIONS

Keystone v3 needs to set OPENSTACK_API_VERSIONS

---

envs/example/defaults.yml
envs/vagrant/defaults.yml
roles/nova-common/defaults/main.yml
roles/nova-common/templates/etc/nova/nova.conf

Without reserving space an user could easily exhaust all the space on a
host leading to difficult situations. Instead of hardcoding at 50G this
is configurable with a default, and set to much smaller for our test and
CI environments.

Reserve disk space for nova hosts

---

envs/example/defaults.yml
roles/client/templates/root/stackrc
roles/common/templates/etc/sensu/stackrc
roles/neutron-common/templates/etc/neutron/neutron.conf
roles/openstack-setup/tasks/cinder.yml
roles/openstack-setup/tasks/images.yml
roles/openstack-setup/tasks/networks.yml
roles/openstack-setup/tasks/users.yml
roles/swift-common/templates/etc/swift/dispersion.conf

This is one way of exposing the v3 API by way of the catalog. The
api-paste already exposes the v3 API, but it wasn't advertised anywhere.
Clients still won't automatically use the v3 API as nothing really looks
for this service name/type, however users who wish to manually make use
of the v3 API can discover it by way of the catalog.
This change also removes long form reference to the auth_uri and
instead makes use of the variable, which will help if we ever change
versions exposed.

Add keystonev3 service to the catalog

---

roles/cinder-common/templates/etc/cinder/cinder.conf
roles/haproxy/defaults/main.yml
roles/haproxy/templates/etc/haproxy/haproxy_openstack.cfg
roles/neutron-common/defaults/main.yml
roles/neutron-common/templates/etc/neutron/metadata_agent.ini
roles/nova-common/templates/etc/nova/nova.conf

These are high level things discovered during 1.1.x customer validation in scenarios other than those we normally test for. They are high value enough to warrant a backport to 1.1.x for any future new installs on 1.1.x or for fixing existing 1.1.x installs.

Backports various fixes for 1.1.x discovered during validation

---

envs/example/defaults.yml
roles/client/templates/root/stackrc
roles/common/templates/etc/sensu/stackrc
roles/nova-common/templates/etc/nova/nova.conf

nova-api filters cinder endpoints by "volume" and "volumev2", but needs
a further hint to actually use volumev2 from the catalog to use the v2
API. cinderclient also expects the endpoint to be volumev2 when asked to
use the v2 API. This commit adds the new endpoint in. The v1 endpoint is
left in place so that cinderclient continues to work without end users
needing to add the forced switch to v2, however we DO put that switch
into our stackrc.

Add cinder v2 endpoint to catalog

---

roles/nova-common/templates/etc/nova/nova.conf

There is a workarounds option to enable/disable live snapshots. It
defaults to disabling so we need to explicitly enable it. The code that
will read this is on master nova and in a bbg fork of stable/juno.

Allow live snapshots in nova

---

roles/common/files/sensu_plugins/metrics-nova.py

The metric should only be the shortname... because
of graphite dot pathing.

nova hypervisor can be shortname or fqdn

---

envs/example/defaults.yml
envs/vagrant/defaults.yml
library/neutron_subnet
roles/openstack-setup/tasks/networks.yml

This will allow instances to use a external nameserver whose IP will not
change when migrating the DHCP namespaces between network nodes on
failover.

Neutron: define name servers for subnets

---

playbooks/logging.yml
roles/cinder-common/tasks/logging.yml
roles/cinder-common/tasks/main.yml
roles/cleanup/handlers/main.yml
roles/cleanup/tasks/logging.yml
roles/glance/tasks/logging.yml
roles/glance/tasks/main.yml
roles/heat/tasks/logging.yml
roles/heat/tasks/main.yml
roles/ironic-common/tasks/logging.yml
roles/ironic-common/tasks/main.yml
roles/keystone/tasks/logging.yml
roles/keystone/tasks/main.yml
roles/logging-config/meta/main.yml
roles/logging-config/templates/etc/logstash-forwarder.d/template.conf
roles/logging/defaults/main.yml
roles/logging/files/etc/init/logstash-forwarder.conf
roles/logging/files/etc/rsyslog.d/49-haproxy.conf
roles/logging/tasks/main.yml
roles/logging/templates/etc/logstash-forwarder.d/main.conf
roles/neutron-common/tasks/logging.yml
roles/neutron-common/tasks/main.yml
roles/nova-common/tasks/logging.yml
roles/nova-common/tasks/main.yml
roles/swift-common/tasks/logging.yml
roles/swift-common/tasks/main.yml
test/run
test/setup
tox.ini

To better handle logs when logrotate was not previously configured and reduce overall disk usage, compress logs after rotation.
`zgrep` and other tools easily handle searching compressed logs anyway.

logrotate: compress log after rotation

---

envs/example/defaults.yml
library/cinder_volume_group
roles/cinder-common/templates/etc/cinder/cinder.conf
roles/cinder-data/tasks/main.yml
roles/horizon/templates/etc/openstack-dashboard/local_settings.py
roles/nova-common/templates/etc/nova/nova.conf

No longer support LUKS encrypted loop back LVM device for a cinder volume group. Instead use OpenStack's method of encrypting on a per-volume basis on the front end (nova). Requires separation of nova-compute from cinder-volume store.

Cinder volume encryption by way of Openstack

---

envs/example/defaults.yml
envs/vagrant/defaults.yml
playbooks/monitoring/files/sensu_plugins/check-neutron-agents.sh
playbooks/monitoring/files/sensu_plugins/check-os-api.rb
playbooks/monitoring/tasks/main.yml
playbooks/monitoring/templates/etc/sensu/stackrc

put stackrc in /etc/sensu and source it in /etc/default/sensu
remove sourcing /root/stackrc from checks
Conflicts:
envs/example/defaults.yml
envs/vagrant/defaults.yml
roles/common/tasks/monitoring.yml
roles/glance/tasks/monitoring.yml
roles/heat/tasks/monitoring.yml
roles/keystone/tasks/monitoring.yml
roles/nova-control/tasks/monitoring.yml
site.yml

Backport 1.0: Create monitoring user in openstack admin tenant

---

roles/common/files/sensu_plugins/check-cinder-sessions.py
roles/nova-data/tasks/monitoring.yml

We want to know when an instance that expects a volume to be mounted
for some reason (netsplit, etc) fails to iscsi mount/loses a mount to
a volume.

Backport 1.1 - Add a cinder sessions check for sensu

---

roles/horizon/defaults/main.yml
roles/horizon/templates/etc/openstack-dashboard/local/local_settings.py

Backporting variable Horizon timeout setting so that we can increase the timeout on request.

backport variable Horizon timeout

---

roles/common/defaults/main.yml
roles/neutron-data-network/tasks/main.yml

Fix two items found during IPv6 testing:
* UFW didn't permit SSH over IPv6
* Neutron L3 agent requires radvd for DHCP stateless and SLAAC

IPv6 support

---

roles/nova-common/defaults/main.yml

fixes CVE-2015-0259 for source based installs. Packaging installs will
be fixed with newer packages.

Pull newer nova for vnc websocket vuln. for src

---

nova-CVE-2015-0259.yml
roles/nova-common/defaults/main.yml

This updates the version of stable/juno we pull in, and adds a playbook
that can be used to fix JUST this nova issue.
Resolves CVE-2015-0259

Update nova for vnc websocket vuln.

---

roles/rabbitmq/defaults/main.yml
roles/rabbitmq/tasks/cluster.yml
roles/rabbitmq/tasks/main.yml
roles/rabbitmq/templates/etc/rabbitmq/rabbitmq.config
site.yml

This may not be necessary,  but wanted to put it here to reference later.
this sets the nodename so that the two (unclustered) rabbit services
are named based on the hostname to make it easier for monitoring and/or
alerting to determine what is going on.

WIP    Always use rabbitmq envs config

---

roles/nova-common/defaults/main.yml
roles/nova-common/meta/main.yml

This switches to the blueboxgroup git mirror of nova, the juno-bbg
branch and the commit that brings back the ability for nova to do live
snapshots. This will read the config file added earlier for enabling
live snapshots.

Enable nova live snapshots for source installs

---

roles/common/tasks/kernel-tuning.yml

Install requires packages to acquire and analyse crash dumps. Configure
system to reserve 128M - 256MB for crash dump kernel. Enable NMI
watchdog timer to detect infinite loop type lock ups. Reorder console so
current VTY is /dev/console. Move kernel configuration into
GRUB_CMDLINE_LINUX so it is applied to all boot options, rather than
just the default.

Enable kernel dump on crash

---

envs/example/defaults.yml
envs/vagrant/defaults.yml
roles/cinder-common/defaults/main.yml
roles/cinder-common/templates/etc/cinder/cinder.conf
roles/glance/defaults/main.yml
roles/glance/templates/etc/glance/glance-api.conf
roles/glance/templates/etc/glance/glance-registry.conf
roles/heat/defaults/main.yml
roles/heat/templates/etc/heat/heat.conf
roles/ironic-common/defaults/main.yml
roles/ironic-common/templates/etc/ironic/ironic.conf
roles/neutron-common/defaults/main.yml
roles/neutron-common/templates/etc/neutron/neutron.conf
roles/nova-common/defaults/main.yml
roles/nova-common/templates/etc/nova/nova.conf

Pointing to the env's cert file works for self-signed certs where the
file is actually both the CA and the cert. For real certs the CA exists
elsewhere, like in the system CA bundle. For that reason we need to
template out where we point to find this.

Template the cafile location for services

---

roles/common/tasks/kernel-tuning.yml

Install requires packages to acquire and analyse crash dumps. Configure
system to reserve 256MB for crash dump kernel. Enable NMI watchdog timer
to detect infinite loop type lock ups. Reorder console so current VTY is
/dev/console. Move kernel configuration into GRUB_CMDLINE_LINUX so it is
applied to all boot options, rather than just the default.

Backport 1.1.x: Enable kernel dump on crash

---

roles/common/tasks/kernel-tuning.yml

Install requires packages to acquire and analyse crash dumps. Configure
system to reserve 256MB for crash dump kernel. Enable NMI watchdog timer
to detect infinite loop type lock ups. Reorder console so current VTY is
/dev/console. Move kernel configuration into GRUB_CMDLINE_LINUX so it is
applied to all boot options, rather than just the default.
Conflicts:
roles/common/tasks/kernel-tuning.yml

Backport 1.0.x: Enable kernel dump on crash

---

roles/nova-data/tasks/libvirt.yml

nova-compute will call this in order to make the config drive. Without
this the instance will fail with No such file or directory.

Add genisoimage to libvirt hosts for config-drive

---

roles/neutron-common/templates/etc/neutron/dhcp_agent.ini
roles/neutron-common/templates/etc/neutron/l3_agent.ini
roles/neutron-data/tasks/main.yml

This was disabled by default upstream due to a bug in iproute2, but
we're installing a version of iproute2 that has this bug resolved. Now
we'll install that version all the time  not just for vxlan, and we'll
enable deletino of l3 and dhcp namespaces.

Enable neutron namespace deletion

---

roles/collectd-client/tasks/main.yml
roles/haproxy/meta/main.yml
roles/haproxy/tasks/monitoring.yml
roles/haproxy/templates/etc/collectd/plugins/haproxy.conf
roles/haproxy/templates/etc/haproxy/haproxy_openstack.cfg

requires https://github.com/blueboxgroup/ursula-monitoring/pull/3
```
$ /etc/sensu/plugins/check-haproxy.rb -c 100 -S /var/run/haproxy/stats.sock -A
CheckHAProxy OK: UP: 100% of 24 // services
$ /etc/sensu/plugins/check-haproxy.rb -c 100 -S /var/run/haproxy/stats.sock -A
CheckHAProxy OK: UP: 100% of 24 // services
root@allinone:~# service nova-api stop
nova-api stop/waiting
$ /etc/sensu/plugins/check-haproxy.rb -c 100 -S /var/run/haproxy/stats.sock -A
CheckHAProxy CRITICAL: UP: 91% of 24 // services, DOWN: allinone, BACKEND
$ service nova-api start
nova-api start/running, process 6485
$ /etc/sensu/plugins/check-haproxy.rb -c 100 -S /var/run/haproxy/stats.sock -A
CheckHAProxy OK: UP: 100% of 24 // services
```

sensu checks and stats for haproxy

---

envs/example/defaults.yml
envs/vagrant/defaults.yml
roles/nova-data/tasks/libvirt.yml

pip module was re-creating the venv, triggering a bug on some ubuntu
installs that would put pip 1.1 into the venv rather than what's on the
system. All sorts of things went wrong.

Switch to command to pip install inside package

---

upgrade.yml

This is a new endpoint with 1.2.x and needs to be explicitly ensured.
This would normally come in via the setup tasks, but we skip those tasks
in upgrades to existing clouds.

Explicitly add cinderv2 endpoint

---

upgrade.yml

This avoids running the heat role when it shouldn't be ran.

Check heat enable as a bool

---

upgrade-db-cluster.yml

If the config doesn't get put in place during the upgrade.yml run then
it'll change during the site.yml run which will cause a restart when we
really don't want/need one. Do the templates early. There is no role
default data to worry about in percona-server role.

Ensure latest mysql configs before upgrade

---

roles/nova-common/templates/etc/nova/nova.conf

This is what happens by default anyway, but we want to be explicit in
case that changes or for easier reading.

Explicitly fall back to host-model cpu_mode

---

roles/common/tasks/ipmi.yml
roles/common/tasks/kernel-tuning.yml
roles/common/tasks/main.yml
roles/common/tasks/networking.yml
roles/common/tasks/serial-console.yml

Tag for items which should be updated before a reboot. Intention is that
this can be run from -master or other more recent branch on an existing
stack before scheduled reboots occur on that stack.

Add prereboot tag

---

roles/collectd-client/tasks/main.yml
roles/common/tasks/monitoring.yml
roles/haproxy/templates/etc/haproxy/haproxy_openstack.cfg
roles/haproxy/templates/etc/haproxy/haproxy_swift.cfg

sensu check needs write perm to haproxy socket for some reason.
Add monitor group, add sensu/collectd to that
monitor group owns socket and has write access.
by default the socket can't write anything harmful
```
- "operator" is the default level and fits most common uses. All data can
be read, and only non-sensitive changes are permitted (eg: clear max
counters).
```

haproxy socket perms

---

roles/common/tasks/ipmi.yml
roles/common/tasks/kernel-tuning.yml
roles/common/tasks/main.yml
roles/common/tasks/networking.yml
roles/common/tasks/serial-console.yml

Tag for items which should be updated before a reboot. Intention is that
this can be run from -master or another recent branch on an existing
stack before scheduled reboots occur on that stack.
In Precise grub-common includes an automatic crashkernel config, but it
isn't large enough for our updater kernels and configurations. Rather
than removing grub-common or backporting from a later release, just fix
the size of the crashkernel reservation to 256M.

Backport 1.2: Add prereboot tag and workaround grub-common crashkernel config

---

roles/common/tasks/ipmi.yml
roles/common/tasks/kernel-tuning.yml
roles/common/tasks/main.yml
roles/common/tasks/networking.yml
roles/common/tasks/serial-console.yml

Tag for items which should be updated before a reboot. Intention is that
this can be run from -master or another recent branch on an existing
stack before scheduled reboots occur on that stack.
In Precise grub-common includes an automatic crashkernel config, but it
isn't large enough for our updater kernels and configurations. Rather
than removing grub-common or backporting from a later release, just fix
the size of the crashkernel reservation to 256M.
Conflicts:
roles/common/tasks/kernel-tuning.yml

Backport 1.1: Add prereboot tag and workaround grub-common crashkernel config

---

roles/common/tasks/ipmi.yml
roles/common/tasks/kernel-tuning.yml
roles/common/tasks/main.yml
roles/common/tasks/networking.yml
roles/common/tasks/serial-console.yml

Tag for items which should be updated before a reboot. Intention is that
this can be run from -master or another recent branch on an existing
stack before scheduled reboots occur on that stack.
In Precise grub-common includes an automatic crashkernel config, but it
isn't large enough for our updater kernels and configurations. Rather
than removing grub-common or backporting from a later release, just fix
the size of the crashkernel reservation to 256M.
Conflicts:
roles/common/tasks/kernel-tuning.yml
roles/common/tasks/main.yml

Backport 1.0: Add prereboot tag and workaround grub-common crashkernel config

---

upgrade.yml

1.0.x to 1.2.x upgrades rabbit, which can cause some services to stop
working until they are restarted. By doing the rabbit upgrade first
before picking it up in site.yml we can ensure services come back to
working after they are restarted as part of their upgrade.

Upgrade rabbit before openstack services

---

upgrade.yml

1.0.x to 1.2.x upgrades rabbit, which can cause some services to stop
working until they are restarted. By doing the rabbit upgrade first
before picking it up in site.yml we can ensure services come back to
working after they are restarted as part of their upgrade.
(cherry picked from commit 97a593564e8101a0ff9b3e2b4a415152cb193501)

Upgrade rabbit before openstack services (backport)

---

playbooks/bootstrap_ml2_vlan.yml
playbooks/bootstrap_ml2_vxlan.yml
upgrade.yml

We've been testing this kernel since b851042a in CI, but none of these files are covered in CI so merge at will.

Backport 1.2: upgrade Kernel to 3.13

---

roles/neutron-data/meta/main.yml

Neutron-data often relies on iproute2, which comes from our ppa, but
there was nothing in place to enforce this dependency and thus the role
could fail. This now explicitly adds the repo.
(cherry picked from commit 73e15e794d80c5256981b0a4a6f6d135cf6cddae)

Explicitly get bbg-ppa for neutron-data (backport)

---

roles/neutron-data/meta/main.yml

Neutron-data often relies on iproute2, which comes from our ppa, but
there was nothing in place to enforce this dependency and thus the role
could fail. This now explicitly adds the repo.
This will need to be backported to RELEASE-1.2.x as well.

Explicitly get bbg-ppa for neutron-data

---

roles/nova-common/defaults/main.yml

So we need to bump it here too. One day this won't be so explicit...

Cloud archive bumped libvirt version

---

site.yml

Swift HAproxy was being done twice and that's not necessary.

Remove dup swift ha proxy role application

---

roles/nova-common/defaults/main.yml

So we need to bump it here too. One day this won't be so explicit...
(cherry picked from commit 823872bc5e41b1e4d03ff767fac7a736828aafd6)

Backport Cloud archive bumped libvirt version

---

bin/run_vagrant

The controlmasters directory (~/.ssh/controlmasters) apparently
used to be created by something, but now it's not so it all fails
on a virgin install. This corrects that my creating the directory
if it does not exist.

Ansible needs a controlmasters directory to function.

---

Vagrantfile
bin/run_vagrant

Turns out, virtualbox doesn't work on my machine because I alredy
run KVM instances for other reasons. This adds support for using
the libvirt provider to fix that.
How to use:
Install the vagrant libvirt provider plugin
(see https://github.com/pradels/vagrant-libvirt - install deps first!)
Install the vargant mutate plugin:
vagrant plugin install vagrant-mutate
Download the existing virtualbox image
Use vagrant mutate on the existing box image:
vagrant mutate ursula-precise libvirt
Run as normal!
Really, that's it. The rest of the changes are covered by this
commit. Everything _seems_ to work for now, and it makes life
better for non-Mac people :D

Add support for vagrant libvirt provider

---

roles/common/templates/monitoring/sensu-sudoers

Otherwise sensu is not able to run this privileged command.
(cherry picked from commit f2acbcd1ba30783903866044441dc9813d4c62d4)

Backport: Add check-storcli to sensu's sudoers

---

envs/example/defaults.yml
envs/vagrant/defaults.yml

Horizon will not show ports to attach floating IPs to if the user is a
non-admin and the network is an admin shared network. Upstream fix is in
the 62 build.

Bump package to pick up horizon port fix

---

envs/example/defaults.yml
envs/vagrant/defaults.yml

Horizon will not show ports to attach floating IPs to if the user is a
non-admin and the network is an admin shared network. Upstream fix is in
the 62 build.
(cherry picked from commit d38750ff0b9fd8df518b97a62b1b08a7df663282)

Backport: Bump package to pick up horizon port fix

---

roles/nova-common/defaults/main.yml
roles/nova-common/templates/etc/nova/nova.conf
roles/nova-data/tasks/libvirt.yml

By default the disk was allocated on-demand. This could lead to a
scenario where space usage was not accounted for properly and space is
exhausted if instances start filling up their local disks. Changing data
within instances could be slower too due to copy on write happening vs
just writing to the already allocated space.
util-linux is required to get the fallocate utility which is used to
allocate the space.

Fully allocate instance disks at launch

---

roles/client/defaults/main.yml

this has to do with openstack not understanding the x-forwarded-for
header and thus responding with a http link rather than a https.

cinderclient 1.2.1 causes issues with cinder behind haproxy

---

Vagrantfile
bin/run_vagrant
envs/example/defaults.yml
envs/vagrant/cinder/group_vars/all.yml
envs/vagrant/cinder/hosts
envs/vagrant/cinder/playbooks
envs/vagrant/defaults.yml
library/cinder_volume_type
roles/cinder-common/templates/etc/cinder/cinder.conf
roles/cinder-data/tasks/main.yml
roles/cinder-data/tasks/volume_group.yml
roles/cinder-data/templates/etc/cinder/cinder.encryption.conf
roles/nova-common/templates/etc/nova/nova.conf
roles/nova-data/tasks/main.yml
roles/nova-data/templates/etc/nova/nova.cinder_encryption.conf
roles/openstack-setup/tasks/cinder.yml
roles/openstack-setup/tasks/main.yml

allow use of device for cinder-volume
* move encryption key to own file so that we only write it on nodes that
are involved in encryption
* allow for deviced backed volume group as well as file backed
* add cinder env for vagrant for easy testing
* fix cinder_volume_type library and create type if missing for encrypted type.
* style cleanup of cinder tasks in openstack-setup

standalone cinder node

---

roles/neutron-data/tasks/main.yml
roles/neutron-data/templates/etc/cron.daily/cleanup-neutron-interfaces

Upstart logs state changes when each tap interface comes up, since a
running cluster could have a very large number of instances created and
destroy purge these files daily.

Cleanup neutron interface logs

---

envs/example/defaults.yml
roles/nova-data/templates/var/lib/nova/ssh/known_hosts

This is silly, but ssh refuses the key otherwise. Ansible fact doesn't
put this little header in place, we have to put it in manually.
Also turn ssh back on

Add the key type to the known_hosts file

---

roles/client/defaults/main.yml
roles/nova-common/defaults/main.yml
roles/nova-data/tasks/libvirt.yml

This adds a security tagged task to update qemu-kvm package. It also backports a cinderclient fix to pass CI.

VENOM for 1.2.x

---

playbooks/reboot_cluster.yml

Sometimes we need to reboot a cluster e.g. when deploying a new kernel.

Utility: reboot playbook

---

plugins/filters/ipv6_slaac.py

Jinja2 filter to compute SLAAC address.
Usage:
```
{{ '2db8::/64' | slaac(ansible_eth0.macaddress) }}
```

IPv6 SLAAC address computation filter

---

upgrade.yml

The package role will not update the symlink if it already exists. For
upgrades that's no good, we want a new symlink. This removal will force
the symlink to be re-created.
Also use the new suggested task format since it's required for some of
our tasks. max_fail_percentage is set to 0 because that was more
appropriate than 1.

Explicitly remove package symlink on upgrade

---

envs/example/defaults.yml
envs/vagrant/cinder/group_vars/all.yml
envs/vagrant/defaults.yml
roles/cinder-common/defaults/main.yml
site.yml

Allow for cinder disablement.
It will be enabled by default which matches the current behavior.

cinder can be disabled

---

roles/rabbitmq/tasks/monitoring.yml

I've been observing this check error out at times if there is load upon the controller.
By setting this to 2 sec (instead of the default 1 sec) we will be getting less noise and will actually be allowing the check to run like it was intended to.

rabbitmq-numqueues check timeout can be 2 seconds

---

roles/glance/defaults/main.yml
roles/glance/templates/etc/glance/glance-api.conf

This is necessary to add support for https://github.com/blueboxgroup/ursula-monitoring/pull/11 and fix the current sensu glance image issue.

glance: configure show_multiple_locations

---

roles/common/files/etc/sysctl.d/10-disable-ipv6-default.conf
roles/common/tasks/networking.yml

By default IPv6 assigns link-local addresses to all up interfaces
including bridge, tun and veth interfaces thus exposing the host IPv6
services to the tenant networks. Resolve this by disabling IPv6 on all
interfaces by default, and explicitly enabling it on specific
interfaces. This brings IPv6 in to parity with IPv4 so the protocol is
only active on interfaces that have been explicitly configured. To
configure IPv6 on an additional interface `sysctl
net.ipv6.conf.$IFACE.disable_ipv6=0`.

network: lock down physical host access via IPv6

---

envs/example/defaults.yml
envs/vagrant/defaults.yml
roles/openstack-package/defaults/main.yml

Sites can override the variable which will be used in the apt call to
install the packages. Keeps our versioning in a single place to update
as master moves along.

Set a default for openstack_package_version

---

roles/common/files/etc/sysctl.d/10-disable-ipv6-default.conf
roles/common/tasks/networking.yml

By default IPv6 assigns link-local addresses to all up interfaces
including bridge, tun and veth interfaces thus exposing the host IPv6
services to the tenant networks. Resolve this by disabling IPv6 on all
interfaces by default, and explicitly enabling it on specific
interfaces. This brings IPv6 in to parity with IPv4 so the protocol is
only active on interfaces that have been explicitly configured. To
configure IPv6 on an additional interface `sysctl
net.ipv6.conf.$IFACE.disable_ipv6=0`.

Backport 1.2.x: lock down physical host access via IPv6

---

roles/cinder-data/tasks/main.yml

qemu-img, in the qemu-utils package, is used to convert qcow(2) images
to a cinder volume. Used when say making volumes from glance images.
With cinder-volume now potentially stand alone this package needs to be
explicitly added.

Cinder volume needs qemu-img

---

roles/nova-common/templates/etc/nova/nova.conf

We want to set this so that resize/migration activities know which IP
address to use to connect to a given hypervisor. Without this set some
socket work is done which many actually pick the external floating IP
address by mistake, which will break migrations.

Hard set hypervisor ssh access IP

---

playbooks/bootstrap.yml
roles/apt-repos/defaults/main.yml
roles/collectd-client/defaults/main.yml

Retrieving APT keys which support it over HTTPS to increase confidence
that these are the key we think they are.

Use HTTPS retrieve APT keys

---

roles/cinder-common/templates/etc/cinder/rootwrap.conf
roles/ironic-common/templates/etc/ironic/rootwrap.conf
roles/neutron-common/templates/etc/neutron/rootwrap.conf
roles/nova-common/templates/etc/nova/rootwrap.conf

Since our paths can be from virtualenvs we need to provide this path to
rootwrap config.
Also update neutron's rootwrap.conf from upstream.

Provide path data to rootwrap

---

roles/cinder-common/templates/etc/cinder/rootwrap.conf
roles/ironic-common/templates/etc/ironic/rootwrap.conf
roles/neutron-common/templates/etc/neutron/rootwrap.conf
roles/nova-common/templates/etc/nova/rootwrap.conf

Since our paths can be from virtualenvs we need to provide this path to
rootwrap config.
Also update neutron's rootwrap.conf from upstream.
(cherry picked from commit cf1f37718f6aee68d613a2357034317593f4b0c8)

Backport 1.2.x: Provide path data to rootwrap

---

roles/rabbitmq/tasks/monitoring.yml

We added a 2 second timeout for checking number of queues, but didn't
add one for the general queue check. This adds it to keep things
consistent and to keep sensu/pager duty quiet.

Add a 2 second timeout to the other rabbit check

---

branch-validation.yml

We need to give these tests a few tries to complete. As a starting point
trying 5 attempts with one second between each attempt. May need to
tweak after this, but it's a good starting point. Also making all of the
loops consistent.

Add until loops for ping tests

---

playbooks/tests/tasks/integration.yml

Ansible modules allow more robust extraction of instance floating IP and
network ID.

Use ansible modules for integration test

---

roles/security_errata/tasks/main.yml

Anything that uses requests > 2.5.3 will complain if there is no true
SSL context capability on the host. Add these 3 python modules for
making such a context available.

Add a true SSL context for python clients/requests

---

bin/install-osx
bin/install-ubuntu

The osx installer was missing a $BINDIR definition, and both had "pip -r -U <file>" instead of "pip -U -r <file>".  Verified osx installer works now, didn't test ubuntu but it should work fine.

fixed installers

---

roles/apt-repos/defaults/main.yml
roles/common/defaults/main.yml
roles/common/meta/main.yml
roles/common/tasks/hwraid.yml

This reverts commit 44d9e2bd3fa7490ad4aa585abfc2dd1ffe37adb5.
We're running into problems with conflicting storcli packages that need
to be worked out before making this change. Reverting to a previous
working configuration.
(cherry picked from commit 57e3f5da9af4283b4f7013b6b71fd41e269fb3e4)

Revert "initial support for storcli"

---

roles/keystone/tasks/main.yml
roles/keystone/templates/etc/cron.d/drop-expired-keystone-tokens
roles/keystone/templates/etc/cron.hourly/drop-expired-keystone-tokens

Once an hour isn't enough, too big of a batch. Every 5 minutes will lead
to smaller batches and a more flushed system. A happy system is a
flushed system.

Flush keystone tokens every 5 minutes

---

roles/keystone/tasks/monitoring.yml

This check comes from ursula-monitoring and will exit non-zero if the
expired token count goes above the high watermark (1K).
Sudo is required to run it so that logging can be written out should
something go wrong with the script.
Requires https://github.com/blueboxgroup/ursula-monitoring/pull/21

Turn on keystone token checking

---

roles/openstack-package/defaults/main.yml

This build of the package just gets python-swiftclient into swift's venv
so that dispersion works once more.

Bump package for python-swiftclient in swift venv

---

envs/example/defaults.yml
library/neutron_floating_ip
library/neutron_subnet
library/nova_compute
playbooks/tests/tasks/integration.yml
playbooks/tests/tasks/network.yml
roles/openstack-setup/tasks/networks.yml

Configure a dual stack tenant network in testenv. Update neutron_subnet
module to support IPv6 addressing options (changes accepted upstream).

testenv: enable IPv6 tenant networks

---

roles/nova-data/tasks/main.yml

Ref: http://docs.openstack.org/admin-guide-cloud/content/section_ts_failed_attach_vol_no_sysfsutils.html and ticket C013EA - if this package is not installed, customers will get the error "systool is not installed" in their nova-compute.logs when trying to attach volumes to running instances.

Add missing sysfsutils package to data nodes

---

roles/nova-common/templates/etc/nova/nova.conf

Add pinning of CPU for nodes with AMD processors.  4 CPUS will be reserved on compute/controller nodes, and 1 will be reserved on compute-only nodes.

Add cpu pinning for AMD nodes

---

envs/example/defaults.yml

Preallocating images does not work for vagrant setup because of limited disk space. Need to set preallocate_images to false in order to boot instances

Setting preallocate_images in nova for vagrant

---

roles/openstack-network/tasks/main.yml

simple installs like allinone only has a single network
and therefore does not have an external network and thus
fails the tasks that try to set up the external network.

only do external network tasks when > 1 network

---

envs/example/defaults.yml

The correct value as documented by Openstack is none

Switching false to none for preallocate_images

---

roles/neutron-common/defaults/main.yml
roles/neutron-common/templates/etc/neutron/plugins/ml2/ml2_plugin.ini
roles/neutron-data/defaults/main.yml
roles/neutron-data/templates/etc/neutron/plugins/ml2/ml2_plugin_dataplane.ini

To support non-multicast environment enabled L2 population and VXLAN
over unicast. Note that this significantly reduces interoperability
with other VXLAN enabled devices, since Neutron itself provides the L2
learning mechanism rather than traditional flooding of unknown unicast
frames. Any additional devices participating the VXLAN virtual network
must coordinate with Neutron to populate their L2 addresses and VTEPs.
Additionally HA configurations utilizing a shared/floating MAC address
may not work, unless they also coordinate with Neutron when the MAC
address moves between active interfaces.
This requires 3.11 or later kernel for VXLAN edge replication functionality.

Neutron L2 population for VXLAN over unicast

---

roles/client/templates/usr/local/bin/migrate_neutron_services
roles/neutron-common/templates/etc/neutron/neutron.conf

Provides additional redundancy, and prevents breaking instance's
nameservers where moving single DHCP namespace between controllers on
failover.

Neutron: schedule two DHCP servers on each network

---

requirements.txt

Point to a 1.2.x branch of ursula-cli so that master of ursula-cli can
move forward to working with Ansible 1.9.x

Update the requirement on ursula-cli

---

roles/neutron-common/defaults/main.yml
roles/neutron-common/templates/etc/neutron/plugins/ml2/ml2_plugin.ini
roles/neutron-data/defaults/main.yml
roles/neutron-data/templates/etc/neutron/plugins/ml2/ml2_plugin_dataplane.ini
roles/nova-common/defaults/main.yml

To support non-multicast environment enabled L2 population and VXLAN
over unicast. Note that this significantly reduces interoperability
with other VXLAN enabled devices, since Neutron itself provides the L2
learning mechanism rather than traditional flooding of unknown unicast
frames. Any additional devices participating the VXLAN virtual network
must coordinate with Neutron to populate their L2 addresses and VTEPs.
Additionally HA configurations utilizing a shared/floating MAC address
may not work, unless they also coordinate with Neutron when the MAC
address moves between active interfaces.
Linux 3.11 is recommended for proper replication of broadcast and
multicast frames egressing VXLAN interface.

Backport 1.2: Neutron L2 population for VXLAN over unicast

---

roles/horizon/templates/etc/apache2/sites-available/openstack_dashboard.conf

Changing Directory path to include horizon to fix new apache2 version for horizon static items issue

Resolving apache2 horizon issue

---

envs/example/allinone/group_vars/all.yml
envs/example/vagrant.yml
roles/nova-common/defaults/main.yml

RetryFilter: Filters out hosts that have already been attempted for scheduling purposes. If the scheduler selects a host to respond to a service request, and the host fails to respond to the request, this filter prevents the scheduler from retrying that host for the service request.
AvailabilityZoneFilter: Filters hosts by availability zone. You must enable this filter for the scheduler to respect availability zones in requests.
RamFilter: Only schedules instances on hosts that have sufficient RAM available.
ComputeFilter: Passes all hosts that are operational and enabled.
CoreFilter: Only schedules instances on hosts if sufficient CPU cores are available.
ComputeCapabilitiesFilter: Matches properties defined in extra specs for an instance type against compute capabilities. …

update default filters

---

roles/nova-data/tasks/main.yml

This code had been added for use on a firewalled stack, but it is not
appropriate for general consumption of Ursula stacks.

Do not open VNC ports by default

---

roles/nova-common/templates/etc/nova/nova.conf

As there is no need for VNC to listen on all interfaces, we should
restrict VNC to the primary_ip for nova-vncproxy access.

Make sure VNC listens on primary_ip

---

envs/example/defaults.yml
envs/example/jeofd/group_vars/all.yml
envs/example/jeofd/hosts
envs/example/jeofd/playbooks
envs/example/jeofd/vagrant.yml
plugins/callbacks/timestamp.py
roles/cinder-control/tasks/main.yml
roles/cinder-data/tasks/main.yml
roles/common/meta/main.yml
roles/common/tasks/main.yml
roles/glance/tasks/main.yml
roles/haproxy/defaults/main.yml
roles/haproxy/tasks/main.yml
roles/haproxy/templates/etc/haproxy/haproxy_openstack.cfg
roles/haproxy/templates/etc/haproxy/haproxy_swift.cfg
roles/heat/tasks/main.yml
roles/horizon/tasks/main.yml
roles/keystone/tasks/main.yml
roles/memcached/tasks/main.yml
roles/neutron-control/tasks/main.yml
roles/neutron-data-network/tasks/main.yml
roles/neutron-data/tasks/main.yml
roles/nova-common/tasks/main.yml
roles/nova-control/tasks/main.yml
roles/nova-data/tasks/main.yml
roles/openstack-setup/tasks/main.yml
roles/percona-server/tasks/main.yml
roles/rabbitmq/tasks/main.yml
roles/swift-common/tasks/main.yml
site.yml

* feature flags to allow disabling of logging/monitoring
* ensure feature flags for cinder etc work as expected
* example of using those flags in envs/example/jeofd to install
a minimal openstack footprint.
(jeofd = just enough openstack for docker)

feature flags added to allow a very minimal install

---

requirements.txt

We pin novaclient and neutronclient to keep working with the ansible
modules we've got housed here in 1.2.x, and oslo.utils bumped upstream
into an incompatible version. So pin oslo.utils to the last version that
works for us in this dead end tree of code.

Pin oslo.utils to stay compatible

---

roles/glance/defaults/main.yml
roles/glance/templates/etc/glance/glance-api.conf

Enhance glance Ursula so that it leverages swift when present, ceph when present (but not swift), or default local file system when neither swift nor ceph are enabled. To enable ceph, set glance.store_ceph to True.

Adding functionality for ceph backend in glance

---

roles/common/tasks/kernel-tuning.yml

Avoids having our nics change names on trusty
(cherry picked from commit a15ec41d45f815958887041420c5805ec58c3c75)

Add biosdevname=0 to kernel options (master)

---

roles/common/tasks/kernel-tuning.yml

Avoids having our nics change names on trusty

Add biosdevname=0 to kernel options

---

roles/cinder-common/defaults/main.yml

We were relying on an env setting for this, but we really should have a
default in the role. File is the safe default.
(cherry picked from commit a7060d71da926d9afb44fd9fadf6fa46a75f0f1f)

Set a default volume type for cinder (1.2.x)

---

roles/cinder-common/defaults/main.yml

We were relying on an env setting for this, but we really should have a
default in the role. File is the safe default.

Set a default volume type for cinder

---

playbooks/reboot_cluster.yml

Otherwise we could break the cluster. The service module should be able
to wait until the mysql daemon fully joins the cluster.

Ensure mysql is running after reboot

---

upgrade.yml

Tiny window while some service is still running but gives us a good
going back spot.

Dump various openstack dbs on upgrade

---

roles/common/tasks/kernel-tuning.yml

This was done on some hosts for a time, but as part of the upgrade we
want the new kernel.

Remove any hard-coded kernel default

---

roles/common/tasks/kernel-tuning.yml

This was done on some hosts for a time, but as part of the upgrade we
want the new kernel.
(cherry picked from commit 5df0a05cad12efde9b2d7d596acbf4880867e9e1)

Remove any hard-coded kernel default (1.2.x)

---

roles/percona-arbiter/tasks/main.yml

(cherry picked from commit 531bc60fe1b84579fa678805fee418ec26cf04f9)

fix typo to enable garbd start on boot (1.2.x)

---

upgrade.yml

This directory already exists and it's the more appropriate location to stash the dumps.

Move mysql dumps to /backup

---

roles/glance/tasks/main.yml

Wrong Glance haproxy https port being opened up in ufw. Changed it from 9293 to 9393.

change ufw port for glance to 9393 from 9293.

---

roles/horizon/defaults/main.yml
roles/horizon/meta/main.yml
roles/horizon/tasks/main.yml

Updates to kilo-bbg Horizon branch to support a working dashboard have been merged. We can now enable them here in the kilo ursula branch.

Update git references to our forked Horizon

---

roles/common/tasks/monitoring.yml

When launched through upstart at boot, the PATH doesn't contain /usr/local folders, which is where OpenStack clients reside, causing check-os-api to fail.

ensure sensu PATH contains /usr/local/bin for keystone &c

---

roles/neutron-common/templates/etc/neutron/metadata_agent.ini

Avoids having to introduce an additional firewall rule for Neutron
metadata proxy to function.

Neutron: Use HTTPS to connect to Nova metadata

---

library/neutron_floating_ip
library/nova_compute
library/nova_group
playbooks/tests/tasks/integration.yml
roles/client/defaults/main.yml
roles/nova-common/defaults/main.yml
test/common

Updated `qemu_kvm_version` however there were some other problems going on with CI which I also fix here:
1. CI was using nova command and awk to try and test for floating_ip etc and it was failing due to awk positionals.   I changed them to use the ansible modules instead.
2. the older nova client pinned version was having dependency issues with one or more of the newer clients and not working.   removed the pinnings.

update pinned libvirt version

---

upgrade.yml

Tiny window while some service is still running but gives us a good
going back spot.
(cherry picked from commit ec27daee0d958e37c9fd6b80d9c71ff38635a48c)

Dump various openstack dbs on upgrade (1.2.x)

---

playbooks/reboot_cluster.yml

This should be on 1.2.x for rebooting 1.2.x and earlier clusters. Master
is moving beyond what is appropriate to push to <1.2.x clusters.

Backport the cluster reboot playbook

---

envs/example/defaults.yml
library/keystone_user.py
roles/haproxy/templates/etc/haproxy/haproxy_openstack.cfg
roles/heat/tasks/main.yml
roles/heat/templates/etc/heat/heat.conf

This request added the "trusts" deferred_auth_method support. 
1. The keystone_user.py change is from ansible-modules-core/cloud/openstack/keystone_user.py. The fix has been pulled into ansible-modules-core. Put in library for now and need to remove it when latest ansible-modules-core is updated in ursula.
https://github.com/ansible/ansible-modules-core/pull/1926
2. Added the  "trusts" deferred_auth_method support. 
3. Switch the standard ports to haproxy.
4. Added more configuration.

Heat support for "trusts" deferred_auth_method

---

roles/swift-proxy/templates/etc/swift/proxy-server.conf

In our previous releases, we were not using keystoneauth to validate
user role, so anybody with a valid token was allowed to use Swift. Now
we'll allow _member_ in, to match that functionality.
Also update the authtoken config to remove the old format of urls.
Temporarly skip ssl validation to keystone.

Update swift keystoneauth options

---

envs/example/defaults.yml
roles/common/defaults/main.yml
roles/common/tasks/ipmi.yml

Softlayer builds fail when ipmi state is __probe__ so we always change to __absent__ before deploy. This makes it easier to set in defaults without having to edit code and worrying about committing it :smile: 
Also threw ___baud_rate___ in to the role defaults since it looked lonely by itself in the task

Making change of ipmi state easier

---

roles/swift-proxy/templates/etc/swift/proxy-server.conf

In our previous releases, we were not using keystoneauth to validate
user role, so anybody with a valid token was allowed to use Swift. Now
we'll allow _member_ in, to match that functionality.
Also update the authtoken config to remove the old format of urls.
Remove the quotes on the cert file, as this seems to trip up requests.
(cherry picked from commit c8b8197a8ce29ee5c7ac99d64608cd4dcaf9bc76)

Update swift keystoneauth options (1.2.x)

---

requirements.txt

python-glanceclient just released 1.0.0 which changes some things
significantly, in a way that breaks tools like shade. Shade is working to
fix it, but until then we need to pin.
https://review.openstack.org/#/c/219005/

Temporarly pin python-glanceclient

---

README.md
Vagrantfile

Added .bashrc or .bash_profile instructions for sourcing /usr/local/bin/virtualenvwrapper.sh in order to use the 
environment created by the mkvirtualenv command. This is necessary to enter the environment.

Fixed README.md to include sourcing of mkvirtualenv

---

roles/glance/templates/etc/glance/glance-api.conf

During our last deploy, we identified a few bugs in `glance-api.conf`.
This PR is for ceph and corresponds to IDS epic 97391.

Fix rbd store user, add image direct url

---

requirements.txt
roles/client/defaults/main.yml
roles/openstack-package/defaults/main.yml

This tries to pull in a new package to get nimble working, but in order to do that it has to deal with some other changes that have happened in pip requirements since the last time we built, so this requires pinning some versions.

Get juno working again

---

envs/example/defaults.yml
envs/vagrant/defaults.yml
requirements.txt
roles/client/defaults/main.yml

Clients got updated recently that break our juno clouds, so pin those.
Backported from master.

Bump package for Nimble and pin clients on 1.2.x

---

envs/example/defaults.yml

This keeps the external network from showing up when building instances.

Don't mark external as shared

---

envs/example/swift/group_vars/all.yml
roles/cinder-common/handlers/main.yml
roles/cinder-common/tasks/main.yml
roles/cinder-common/templates/etc/cinder/cinder.conf
roles/cinder-data/tasks/main.yml
roles/cinder-data/tasks/monitoring.yml

if swift.enabled is true, the cinder-common and cinder-control roles will now setup cinder backup with swift as the backend.

Cinder backup to swift

---

envs/example/defaults.yml

This keeps the external network from showing up when building instances.
(cherry picked from commit 3c1c4d95e5c271bf409dbd352c9328ae6ec42ad2)

Don't mark external as shared (1.3.x)

---

roles/glance/templates/etc/glance/glance-api.conf

Putting default_store in the [DEFAULT] section has been deprecated since Juno. We verified this was causing failures in starting the glance service with ceph or swift enabled. Moved to the correct location under [glance_store].

Fix deprecated location for default_store

---

roles/horizon/defaults/main.yml
roles/horizon/templates/etc/openstack-dashboard/local_settings.py

Should set keystone_api_version default to __3__ for kilo. Enabling quotas for neutron also solves an issue we ran into earlier, though our patch won't break either way now. zrs233/horizon@b995cd4#diff-9582d630fda591281a820da973eaac94L114

Updating horizon role for kilo support

---

roles/common/tasks/ssl.yml

With the pinning, clients aren't able to auth to keystone. Just grab the
latest one.
(cherry picked from commit 6299c8850dace0a24b3edd752fd62335467e6350)

Don't pin requests, it breaks clients (1.2.x)

---

roles/common/tasks/ssl.yml

With the pinning, clients aren't able to auth to keystone. Just grab the
latest one.
(cherry picked from commit 6299c8850dace0a24b3edd752fd62335467e6350)

Don't pin requests, it breaks clients (1.3.x)

---

roles/openstack-package/defaults/main.yml

This pulls a newer neutron that fixes issues with snapshoting the only
instance on a hypervisor

Bump to bbc117

---

roles/percona-backup/tasks/main.yml
roles/percona-backup/templates/percona-xtrabackup.sh

Even with the previous fixes, backups that weren't being pruned previously remained on disk, being deleted one at a time.
* Allows you to run backup manually and still retain 7 days' backups
* As arcane as `find(1)` is, bash array syntax is exponentially worse

Simplify backup pruning by using find … -mtime

---

roles/ceph-common/handlers/main.yml
roles/ceph-common/tasks/main.yml
roles/ceph-compute/tasks/main.yml
roles/ceph-compute/templates/etc/ceph/secret.xml

We are doing some tasks in `cinder-common` that really should be done
in a separate task. Namely, these `virsh` commands should only be run
on compute hosts.
#1140 shows how `site.yml` will make use of this role.

Add ceph-compute

---

roles/ceph-osd/tasks/main.yml

After more thought and testing, we need `ignore_errors` on the
partition check. If it fails, it means the partition is not there,
so we're okay to proceed.
Part of the Ceph Epic & 104678: Improve Ceph Block Storage Automation — https://hub.jazz.net/ccm08/quickplanner/jazzhub.html#items:projectId=_MM_y5SldEeWSQOc0JZWznA&serverId=hub.jazz.net&planType=allwork&allIterations=true&itemId=97391

Add ignore_errors on partition check

---

roles/neutron-common/templates/etc/neutron/metadata_agent.ini

Avoids having to introduce an additional firewall rule for Neutron
metadata proxy to function, documented issue with making these requests
over HTTPS.

CHERRY-PICK - Neutron: Use internal uCARP address for metadata

---

roles/cinder-control/tasks/monitoring.yml
roles/glance/tasks/monitoring.yml
roles/heat/tasks/monitoring.yml
roles/keystone/tasks/monitoring.yml
roles/neutron-control/tasks/monitoring.yml
roles/nova-control/tasks/monitoring.yml
roles/swift-common/tasks/monitoring.yml

This reverts commit 0bcfbd815863364cc6d16150de3d9d6d1a61d5e2.
We aren't ready to monitor these in 1.3.x.

Revert "Added sensu checks for API SLA for current components"

---

roles/common/tasks/ssl.yml

With the pinning, clients aren't able to auth to keystone. Just grab the
latest one.

Don't pin requests, it breaks clients

---

library/sensu_metrics_check.py
roles/collectd-client/defaults/main.yml

Change default collectd and sensu metrics collection interval to 60 seconds to match default graphite storage retention interval, so we're not collecting and relaying a bunch of data only to discard it.

Change default collectd and sensu metrics collection interval to 60 seconds

---

library/ceph_pool.py

We tested with a fully-loaded node and wanted to clear one of the
ceph warnings by making a small improvement to our pg count automation.

Improve pg count automation

---

library/ceph_disks.py

Previous disk_detection code had an ansible issue where the script wouldn't run. These changes, tested throughout, should be enough to fix that problem.
Story: https://hub.jazz.net/ccm08/quickplanner/jazzhub.html#items:projectId=_MM_y5SldEeWSQOc0JZWznA&serverId=hub.jazz.net&planType=allwork&allIterations=true&itemId=104678
IDS Epic: https://hub.jazz.net/ccm08/quickplanner/jazzhub.html#items:projectId=_MM_y5SldEeWSQOc0JZWznA&serverId=hub.jazz.net&planType=allwork&allIterations=true&itemId=97391

fixed ansible issue for ceph disk_detection

---

roles/horizon/templates/etc/apache2/sites-available/openstack_dashboard.conf

CSS and other horizon elements were not loading correctly after a source install.
No static directory exists in  /opt/openstack/current/horizon/ (/opt/bbc/openstack-11.0-master/horizon/).
The static directory is available however, in /opt/stack/horizon/.

Fix horizon static directory not loading when doing source install

---

roles/openstack-package/defaults/main.yml
roles/openstack-package/tasks/main.yml

Ran into an issue with this when trying to deploy from packages.  Ansible wasn't finding the variable in it's scope.  Looked around and didn't find anything in the defaults either...
I modeled the fix after how it is done in the roles/openstack-source/ role, I believe this is how it was intended to be.

Fix virtualenv_base for package install

---

roles/neutron-data-network/tasks/ipchanged.yml
roles/neutron-data-network/templates/etc/ipchanged/add_floating_ip

Handler scripts for ipchanged do not work in deployments where gateway
for physical nodes and Neutron external network are external to the
controllers e.g. when using an external firewall. Refactor these so we
send gratuitous ARP to default gateway in all cases, and gratuitous ARP
to other pNodes in case when acting as gateway.

ipchanged: support case where controllers are not gateway

---

roles/common/tasks/python.yml

Kilo Swift needs version > 0.16.1 and reason that eventlet was set to 0.15.2 for Nova is not valid. Did a cloud deploy (from source) with latest eventlet and there were no issues

Unfreeze eventlet version

---

playbooks/tests/tasks/controller.yml
roles/client/defaults/main.yml
roles/common/tasks/python.yml
roles/nova-common/defaults/main.yml

The pinned version was having difficulty in parsing Kilo's glance
output. But the new version defaults to API v2, which does not translate
image names to IDs, so for now use v1 when looking at the cirros image
in our tests.

Unpin glanceclient.

---

roles/ceph-monitor/tasks/main.yml
roles/ceph-monitor/templates/etc/update-motd.d/92-ceph

This script is doing more harm than good. When the cluster is in a bad
state, it takes forever to get the status and causes issues with ssh.

Remove motd script from ceph monitor nodes

---

roles/neutron-common/defaults/main.yml

Pin it down to 0.1.3 until upstream sorts this out. This was breaking
neutron installs.

jsonrpclib bumped and is broken

---

envs/example/defaults.yml
roles/ceilometer-common/meta/main.yml
roles/ceilometer-common/templates/etc/ceilometer/ceilometer.conf
roles/ceilometer-control/tasks/main.yml
roles/haproxy/templates/etc/haproxy/haproxy_openstack.cfg
roles/mongodb-server/tasks/primary.yml

Added functionality to support standard ports from endpoints role.
Fixed corner case failure by prioritizing mongo primary to controller1.
Made Ceilometer disabled by default again.

Ceilometer Standard Ports

---

roles/swift-common/templates/etc/sudoers.d/swiftops

Allowing swift-init root access for swiftops user so it could start all services as part of ring deployment 
https://github.com/blueboxgroup/swifttool/pull/3

swiftops user need sudo access to swift-init to start services

---

envs/example/standard/hosts

The cinder data plane has moved to `controller1` & `controller2`. 
Should I change all environments or just this for now?

Move cinder_volume to controller nodes

---

roles/horizon/defaults/main.yml
roles/horizon/templates/etc/openstack-dashboard/local_settings.py

hid all admin panels from cloud_admin role, except host_aggregates.
hid domains panel, and resource types panel from non full admins.

horizon UI changes through customization module for cloud_admin/project_admin

---

roles/cinder-common/tasks/main.yml
roles/cinder-common/templates/etc/cinder/cinder.conf
roles/endpoints/defaults/main.yml
roles/haproxy/templates/etc/haproxy/haproxy_swift.cfg
roles/swift-proxy/defaults/main.yml
roles/swift-proxy/meta/main.yml

Cinder backup to Swift is currently going through public endpoint. Made changes to use internal URL that doesn't require SSL termination

Cinder backup changes to use Swift internal URL

---

playbooks/tests/tasks/controller.yml
playbooks/tests/tasks/integration.yml
roles/client/defaults/main.yml

The pinned version was having difficulty in parsing Kilo's glance
output. But the new version defaults to API v2, which does not translate
image names to IDs, so for now use v1 when looking at the cirros image
in our tests.
(cherry picked from commit f3bd92bb8576ed7da61dad2dcf8b657f60562184)

Unpin glanceclient (1.2.x)

---

playbooks/unmount-and-clear-disks.yml

To prep for swift deployment, this playbook unmounts and clears all drives specified for that node type. Skips unmounting any drives not defined as well as clearing any partitions.

Added playbook to unmount and clear all disks

---

roles/percona-server/tasks/main.yml

In roles/percona-server/tasks/main.yml, there is a typo on line 69. The name of the task is currently "are we already already bootstrapped" in master instead of just "are we already bootstrapped".

Typo in roles/percona-server/tasks/main.yml

---

site.yml

Found this bug this morning. The ceph-common role, which is called
by ceph-osd, populates a template that includes info about the monitor 
nodes. However, when you run with tag "ceph-osd", this info is not 
gathered and therefore absent from the conf file. Forcing fact 
gathering for this task fixes the issue.

gather facts for ceph-osd role

---

roles/cinder-common/tasks/main.yml

Give only cinder permissions to access cinder logs and cinder
configurations

Make cinder techspec compliant

---

roles/keystone/defaults/main.yml
roles/keystone/templates/etc/keystone/keystone-paste.ini
site.yml

If a site wants jellyroll, they get jellyroll. Middleware for password
validation and logging of rejected auth attempts.

Enable jellyroll keystone middleware

---

roles/common/defaults/main.yml
roles/common/tasks/main.yml

We install from an image or a pre-seed, and it has packages already
built in. We need a method to remove the packages we do not wish to ship
in the final product.

Support removing unwanted packages

---

roles/horizon/defaults/main.yml
roles/swift-common/defaults/main.yml

Horizon had a double entry for memcache, picked the one that sets a pin.
Swift doesn't use mysql, not sure why we were installing it into the
venv.

Clean up the source deps for horizon/swift

---

playbooks/unmount-and-clear-disks.yml

Allow user to unmount all partitions of a drive declaring just the drive in all.yml rather than the partitions themselves. Also fixed issue where sgdisk would not delete partitions on first pass.

Update to unmount-and-clear-disks playbook

---

roles/apt-repos/defaults/main.yml

The current key has sporadic timeouts. The commmunity ceph-ansible
recently changed to this url.

Update ceph key url

---

roles/ceph-common/defaults/main.yml
roles/ceph-osd/defaults/main.yml
roles/ceph-osd/tasks/main.yml
roles/ceph-osd/tasks/system_tuning.yml

Additional tunings for Ceph Storage/OSD nodes based on recommendations from IBM Research and Ceph community.
Ceph community link: https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-common/tasks/misc/system_tuning.yml

add osd node and ceph.conf tuning check for ceph

---

ansible.cfg

Using smart, instead of the default of implicit, facts will be gathered
from each host only once and cached between plays. This should improve
our runs a bit as we have a lot of plays where facts are gathered and
ansbile is needlessly gathering over and over again.

Gather facts smartly

---

roles/client/templates/root/stackrc
roles/common/templates/etc/sensu/stackrc

Newer novaclient defaults to v3 which breaks.

Force compute v2 in stackrc

---

roles/heat/defaults/main.yml

A new python requests was released that bundles urllib3, which causes issues with the glanceclient that heat is using. So pin to the previous release of requests which was working just fine. The fix is the same as https://github.com/blueboxgroup/ursula/commit/92e68a6ac6ea3ebc71d5b266173fe4b8a283eaab

ping requests to 2.7.0 so the urllib3 will be less then 1.11 for glance http header to work

---

roles/swift-common/meta/main.yml

No system dependencies are required, so the system_dependencies variable is not required.  Without this variable, it should default to the empty set and fix the current issues.

Remove system_dependencies variable

---

roles/cinder-common/tasks/main.yml
roles/glance/tasks/main.yml

Makes the glance and cinder policy files 644 so that Horizon can check them

Make glance and cinder policy files 644

---

roles/cinder-common/tasks/main.yml
roles/common/tasks/system-tools.yml
roles/glance/tasks/main.yml
roles/keystone/tasks/main.yml
roles/neutron-common/tasks/main.yml

Uses a combination of setguid sticky bit and ACL to enforce log file
permissions. These changes can be found in:
roles/cinder-common/tasks/main.yml
roles/glance/tasks/main.yml
roles/keystone/tasks/main.yml
roles/neutron-common/tasks/main.yml

WIP Redo the way the log file permissions are set

---

roles/ceph-compute/meta/main.yml
site.yml

Setup the appropriate dependency for ceph-compute, else running with
ceph-compute tag will fail.

ceph-compute depends on nova-compute

---

roles/nova-common/defaults/main.yml
roles/nova-common/tasks/main.yml

Add /var/log/nova-novncproxy.log to the nova.logs. It lists it as type
openstack and tags it as nova and novnc. This change is found in the file
roles/nova-common/defaults/main.yml
Make the nova configuration files have the mode 640 and be owned by
nova:nova. This change is found in roles/nova-common/tasks/main.yml.
Make the nova log files have the mode 640 and be owned by nova:nova. This
change can be found in roles/nova-common/tasks/main.yml.

Make nova techspec compliant

---

envs/example/defaults.yml

By using 10.0.0.0/8 we won't have to care about what dhcp is handing out
to instances in the target cloud we are testing on.

Make the undercloud_cidr less specific for testing

---

playbooks/reboot_cluster.yml

We should be doing everything one at a time, to avoid having significant
portions of instances down at once.

Do all reboots serially (master)

---

playbooks/reboot_cluster.yml

We should be doing everything one at a time, to avoid having significant
portions of instances down at once.

Do all reboots serially

---

roles/neutron-common/tasks/main.yml
roles/neutron-common/templates/etc/neutron/rootwrap-ursula.d/ursula.filters
roles/neutron-common/templates/etc/neutron/rootwrap.conf

We need to allow for killing processes that start from our virtualenv
python.
This may need care around upgrade time as to not leave agents stale from
the old venv path.

Add our own rootwrap filter for neutron

---

README.md

missing libssl-dev
mkvirtualenv alias does not exist until virtualenvwrapper has been sourced
changes in README.md

Two trivial gotchas on latest Mint 17.2

---

roles/common/tasks/python.yml

New version seems to have broken some of our code, so pin for now until
sorting out necessary changes.

Pin shade to last known working version

---

roles/keystone/templates/etc/keystone/policy.json

bug fix for defect 108531
policy changes needed for Create/Edit/Delete user buttons to appear on dashboard as a project_admin, while continuing to support existing CLI permissions

bug fixes for horizon user APIs in keystone policy - defect 108531

---

roles/haproxy/templates/etc/haproxy/haproxy_openstack.cfg

Haproxy does an httpchk on glance on / instead of /versions. This causes
a warning message to constantly fill the glance log files every ~2 seconds and
bloats the logs on a deploy. As of liberty, this warning message has been changed
to a debug. This is a workaround.
Please reference https://bugs.launchpad.net/mos/+bug/1479408 and https://bugs.launchpad.net/glance/+bug/1496138

Fix problem with glance logs becoming bloated

---

envs/example/defaults.yml

Whenever ucarp was on controller2, MongoDB would fail during deployment.
By switching the endpoint to be just controller1, MongoDB HA can handle everything.

Fix Controller2 ucarp Issue During MongoDB Deployment

---

library/swift_disk.py
playbooks/unmount-and-clear-disks.yml

During the local install, we saw a problem with disks and invalid
partition data. Swift code is currently creating GPT labels in the 
`swift_disk` library. I consider this cleanup/prep, so I'd like to move
it to the cleanup play, which also allows ceph to access it.

Create GPT labels for ceph and swift

---

roles/common/defaults/main.yml
roles/common/meta/main.yml
roles/common/tasks/audit-logging.yml
roles/common/tasks/main.yml
roles/common/tasks/system-tools.yml

Kvm is already mostly techspec compliant. We install auditd, logstash,
and logrotate its log file.

Make kvm techspec compliant

---

roles/glance/defaults/main.yml
roles/glance/templates/etc/glance/glance-api.conf

If swift is enabled, store glance in swift.  If swift is not enabled,
but ceph is, store in ceph. If neither swift nor ceph are enabled, store
on the filesystem. Also still allow for explicitly setting the store
method. Defaults to smart choice of backend.

Implement smart choosing of glance store

---

roles/glance/tasks/main.yml

Move above `flush_handlers`.
Cinder is okay, as services are already restarted 
after ceph integration.

Restart glance services after ceph integration

---

roles/mongodb-common/templates/etc/mongodb/mongod.conf

When `mongo_arbiter` is not defined in the host file, mongod.conf should default to nojournal = false.

Make mongod.conf template more robust

---

roles/horizon/tasks/main.yml
roles/horizon/templates/etc/apache2/mods-enabled/headers.conf

AppScan flagged that some of the cookies did not have the HttpOnly and the Secure attributes set on them. This enables mod_headers to always set the attributes on the cookies.

Add HttpOnly and Secure attributes to any cookie created by horizon

---

roles/neutron-common/defaults/main.yml
roles/neutron-common/templates/etc/neutron/neutron.conf
roles/neutron-control/tasks/main.yml
roles/neutron-data-network/handlers/main.yml
roles/neutron-data-network/tasks/main.yml
roles/neutron-data-network/tasks/monitoring.yml

Default of "smart" will enable lbaas when the controllers are dedicated.
Can still hard set true/false to enable/disable regardless of controller
configuration.

Use "smart" logic to enable lbaas

---

roles/endpoints/defaults/main.yml

Was previously pointed to ucarp, now it's the first server for setup.
This is meant to match the previous PR - https://github.com/blueboxgroup/ursula/pull/1317/files

Fixed MongoDB Endpoint In Role To Match defaults.yml

---

roles/ceilometer-common/templates/etc/ceilometer/ceilometer.conf
roles/heat/templates/etc/heat/heat.conf

The alarm URL is signed with an AWS-style signature because /
the handler for it is provided (for now) by Heat's AWS compatibility API.
In liberty, heat will start to support signal url for autoscaling.

Fixed Heat Autoscaling By Making Ceilometer Alarms Not Verify SSL

---

roles/cinder-common/templates/etc/cinder/cinder.conf
roles/neutron-common/templates/etc/neutron/metadata_agent.ini
roles/nova-common/defaults/main.yml

We should rely on /etc/hosts entries to turn fqdns into undercloud
floating IPs, to bypass upstream gateways when communicating within the
cloud.

Pull ip addresses out of configs

---

envs/example/defaults.yml
test/setup

Rather than guessing at what the subnet cidr is of the testenv's
internal network, we should just query for it.

Find and use actual subnet cidr

---

envs/example/defaults.yml
roles/cinder-common/defaults/main.yml
roles/cinder-common/tasks/main.yml
roles/cinder-common/templates/etc/cinder/cinder.conf
roles/cinder-data/templates/etc/tgt/conf.d/cinder_tgt.conf
roles/common/tasks/main.yml
roles/glance/defaults/main.yml
roles/glance/tasks/main.yml
roles/glance/tasks/monitoring.yml
roles/glance/templates/etc/cron.d/glance-image-sync
roles/glance/templates/etc/glance/glance-api.conf
roles/glance/templates/etc/rsyncd.conf
roles/nova-common/defaults/main.yml
roles/nova-common/tasks/main.yml
roles/nova-common/templates/etc/nova/nova.conf
roles/nova-data/tasks/main.yml
roles/nova-data/tasks/ssh.yml
test/setup

For the services that create potentially large amounts of data, move the
data to a standard data path, /opt/stack/data/<service>. In some
deployments we may have a different filesystem mounted to
/opt/stack/data.

Make use of custom state paths for services

---

roles/swift-common/defaults/main.yml

The default doesn't really get used, but it should match what the module
expects.

Update default for swift_disk values

---

roles/cinder-data/tasks/monitoring.yml
roles/nova-data/tasks/monitoring.yml

Easier to use `cinder.enabled_backends`. No fun looping over a
list of dictionaries to see if it contains a value.
This replaces #1382.

Add iscsi checks only when ceph is not a backend for cinder

---

playbooks/unmount-and-clear-disks.yml

Some test results after the change:
```
ok: [swiftnode1] => {
"var": {
"disk_list": [
"sdb",
"sdc",
"sdd",
"sde",
"sdf",
"sdg"
]
}
}
```
Same format as ceph:
```
ok: [ceph1] => {
"var": {
"disk_list": [
"sdd",
"sde",
"sdf"
]
}
}
```

Fix disk cleanup play to use new swift disk layout

---

playbooks/unmount-and-clear-disks.yml

The ansible mount module now has a bug where setting the state to unmounted doesn't clean the /etc/fstab file as it should. Some new tasks are introduced to remove the appropriate entries from the fstab file. Also, the new disk layout structure for swift had to be accommodated when removing shared partitions.

ensure fstab gets cleaned after unmounting

---

.gitignore

I just got annoyed from all of the vim and emacs backup files showing up in my `git status`.

Ignore emacs and vim backup files

---

envs/example/defaults-2.0.yml
roles/neutron-common/defaults/main.yml
site.yml

In some legacy deployments without firewalls we used the controllers as
gateways for the Neutron external and internal pNodes networks. All new
deployments use external network infrastructure to provide the gateway
for these networks. Remove code to automatically generate an
interfaces(5) file for the brq* interface for the external Neutron
network. Existing deployments will be unaffected since this file is
already written, and in most cases defined host_vars network_interfaces.
This will prevent erroneously assigning a duplicate IP address to the
controllers as the external default gateway. -- Dustin Lundquist

Feature flag Neutron external network interface config

---

roles/common/templates/monitoring/config.json
roles/monitoring-common/defaults/main.yml

Sensu should use the full hostname including domain whenever available
for registering the sensu client into monitoring. However, at times we
still need to override this automatic naming which is supported via the
`monitoring.client_name` configuration variable.
--
**NOTE:**
On upgrades to existing sites, this **will** cause alerting to the
production Sensu instance. There will be keepalive alerts for the
existing sensu client_name, and any silenced alerts will again alert on
the newly registered client_name with domain.
Essentially, upgrade with alerting the on-call pager receivers
proactively prior to deployment.

monitoring: sensu client_name use domain too

---

roles/haproxy/templates/etc/haproxy/haproxy_openstack.cfg

Disable httpchk in novnc in haproxy to avoid hangs of nova-novncproxy. The default method used is tcp-check

Fix for novnc in haproxy

---

roles/common/tasks/networking.yml
roles/common/templates/etc/sysctl.d/60-tcp-tuning.conf

The changes made in the previous PR for sysctl failed on baremetal deployments.
This PR will correct those changes and put the ipv4 settings in the
correct spot for deployment.
Swift-common contained a tuning role which would override one of these
settings so it has been depreciated.

Fix sysctl ipv4 changes made in PR #1336

---

roles/haproxy/templates/etc/haproxy/haproxy_openstack.cfg
roles/haproxy/templates/etc/haproxy/haproxy_swift.cfg

Increased HAProxy server and client timeouts from 30 seconds to 300 seconds to address issues with HTTP 504 errors on long-running API calls.

Increased HAProxy server and client timeouts

---

roles/swift-proxy/handlers/main.yml
roles/swift-proxy/tasks/main.yml

the default memcached ip address of `0.0.0.0` resulted in errors of the swift-proxy service. the respective line is now commented out in the `/etc/memcached.conf` file and the appropriate bond0 ip address is used. after these file edits, memcached will be restarted to ensure that the changes actually take place.

allow swift to connect to proper memcached host

---

roles/cinder-common/templates/etc/cinder/cinder.conf

Removed as part of a cleanup to use FQDNs in place of IPs. However,
cinder swift driver does not support certificates other than those
acknowledged by curl or python requests. Thus we must connect
directly to swift without ssl. If we gather the url's from keystone
we are then trying to connect to the swift ssl port without using
ssl.

Add 'swift_backup_url' back to cinder.conf

---

roles/common/templates/monitoring/config.json

The jinja2 ` | default()` filter does not respect falsey values like `~ (null)` by default. It only operates on fully `undefined` values. For sanity, we want to handle YAML `nil` and define the defaults so we know what vars are actually used in a role.

common: sensu client_name default handle falsey values

---

test/setup

Upgrading pip from 1.5.4 to 1.7.2 will get rid of the following type of
error during test run setup:
ERROR: os_security_group is not a legal parameter in an Ansible task
or handler

Upgrade pip in test

---

playbooks/ci-full/tasks/delete.yml

A traceback in one of our Jenkins logs indicated we were still using
the nova_compute module to delete the instance instead of os_server.
Associated with: https://trello.com/c/fXNGJuFH

Use os_server in delete task

---

roles/ceph-common/tasks/main.yml
roles/ceph-monitor/tasks/main.yml

Fix for issue https://github.com/blueboxgroup/ursula/issues/1433. 
Ensure ceph log files on Monitor and Storage/osd nodes are collected by logstash.

Ensure logstash can read all ceph logs

---

playbooks/ci-allinone/vars/main.yml
playbooks/ci-full/vars/main.yml
test/common
test/setup

To have concurrent test runs happening in the same cloud and tenant, we need to have unique keypair names.

Unique keypair name

---

roles/memcached/defaults/main.yml
roles/memcached/templates/memcached.conf
roles/swift-proxy/handlers/main.yml
roles/swift-proxy/tasks/main.yml
roles/swift-proxy/vars/main.yml

Parameterized the bind address in memcached role. Instead of manipulating memcached.conf, override that variable in proxy role.

Cleaning up how memcached bind address was configured in Swift

---

roles/nova-common/defaults/main.yml
roles/nova-common/templates/etc/nova/nova.conf

Adding this due to timeouts observed when copying large glance images to cinder volumes.  The default only allows 3 minutes for this action to finish.  This bumps the settings up to allow for 10 minutes.

Added parameters to tune block device allocation retry timeouts.

---

envs/example/defaults-2.0.yml
roles/openstack-setup/tasks/networks.yml

In some environments we cannot use the default IP allocation of the
entire subnet, and instead need to define a start and end to the pool.
When no start/end have been defined, do not pass along the options to
the module.

Support ip allocation pool definition for subnets

---

roles/percona-server/tasks/logging.yml

Percona logrotate is leaving logs open, even when they are deleted, causing the disk to fill up. Logrotate is modified to use flush logs directive.

Fix Percona logrotate script

---

roles/percona-server/tasks/main.yml

If the mysql data dir is provided by an LVM mount point, we need to
ensure permissions of the directory so that percona can write to it. We
have to have the task after the percona package installs so that the
mysql user/group exist.

Set mysql dir permissions

---

roles/client/defaults/main.yml
roles/client/meta/main.yml
roles/client/tasks/main.yml

If the package is not installed, pip will pull in python-prettytable
from pypi. Installation this way can lead to prettytable packages that
are only readable by root, breaking non-root usage of clients or other
things like that. Work around this by installing the package from apt to
satisfy the dependency.

Install python-prettytable for client usage

---

roles/common/defaults/main.yml

We were pinned to a hilariously old pip that was failing to parse some
requirements coming in from oslo.

Bump pip version

---

roles/neutron-common/tasks/main.yml
roles/neutron-common/templates/etc/modprobe.d/blacklist-openvswitch.conf

We do not want OVS starting when we are not using it...so blacklist
it on all neutron-common nodes (all nodes participating in the
neutron data plane shoudl be covered here).

Blacklist OVS

---

roles/heat/defaults/main.yml
roles/heat/templates/etc/heat/heat.conf

Upstream docs say that the default is 4, but in reality the default is
number of CPUs. Limit it to 4 as a default that can be overridden.

Limit heat engine workers

---

envs/example/defaults.yml
roles/openstack-setup/tasks/networks.yml

In some environments we cannot use the default IP allocation of the
entire subnet, and instead need to define a start and end to the pool.
When no start/end have been defined, do not pass along the options to
the module.
THe subnet creation task is duplicated here becuase Ansible 1.7 does not
have the "omit" filter.

Support ip allocation pool definition for subnets (1.2.x)

---

roles/common/defaults/main.yml
roles/common/tasks/main.yml

This will make the serial console passed to
roles/common/tasks/serial_console.yml a variable that defaults to ttyS0
It addresses issue #1472.

Make serial console a variable defaulting to ttyS0

---

playbooks/ci-full/tasks/keypair.yml

This is preventing us from unpinning our install of python-novaclient.

Remove use of nova_keypair

---

roles/heat/templates/etc/heat/heat.conf

When ceilometer is not enable, set heat notification driver to noop.

conditional for heat notification driver

---

roles/ceph-compute/meta/main.yml
roles/nova-common/templates/etc/nova/nova.conf

This is going to deprecate PR #1493. Adding ceph-common as a dependency for ceph-compute so that librbd1 and librados2 packages on compute nodes will be synced with the ceph nodes. In addition, a ceph.conf file will be generated for the compute nodes as well, allowing for RBD client configuration.

updating packages and creating ceph.conf on compute nodes

---

roles/percona-backup/templates/percona-xtrabackup.sh

This needs to be defined so that the percona backup script is able to
connect to the database.

Define mysql socket path

---

roles/percona-arbiter/tasks/main.yml

This directory appears to be needed now, as nobody owner so that data
can be written into it.

Create directory for garbd data

---

roles/percona-server/templates/etc/my.cnf

mysql will log all queries when this option is turned on. This leads to
many gig log files. Turning this off keeps the logs from filling our fs.

Turn off mysql general logging

---

roles/heat/templates/etc/heat/heat.conf

This is related to https://bugs.launchpad.net/heat/+bug/1491185 in which
large heat templates can cause errors from Heat. As a temporary work
around until the upstream code handles this automatically, we're bumping
the allowed overflows up to 1000.

Set higher allowed overflow for heat db

---

ansible.cfg
library/sensu_check.py
library/sensu_metrics_check.py
library/sensu_process_check.py
plugins/action/sensu_check.py
plugins/action/sensu_metrics_check.py
plugins/action/sensu_process_check.py
roles/monitoring-common/defaults/main.yml

Since we are moving to Flapjack.io as part of the
alerting pipeline, we should use a default and metrics
handlers instead of explicitly using pagerduty and graphite.
This allows us to easily control which handlers are actually
used as part of a set of handlers on the sensu-server.
Currently, default set is pagerduty and flapjack_http, and the
metrics handler is graphite.
This gives us flexibility rather than updating ursula proper with
our internal requirements and systems.

library: sensu modules use default, metrics handlers

---

roles/common/tasks/main.yml
roles/common/tasks/monitoring.yml
roles/percona-backup/files/percona-xtrabackup.sh
roles/percona-backup/tasks/main.yml
roles/percona-backup/templates/percona-xtrabackup.sh

Removes unused "email team if it fails" fucntionality which didn't work with 'set -e' anyway;
Installs file using copy instead of template, which was all templated in a "raw" block;
Removes unneeded "mailutils" dependency

Fix percona-extrabackup.sh for better monitoring

---

roles/keystone-setup/tasks/main.yml

Errors occur while attempting to use ursula with a playbook
similiar to site.yml that does not exist in the root ursula
directory.  The errors are do to references to files in one
role that exist in another role. The file reference assumes
the roles directory is in the same directory as the playbook.
The change made uses the role_path variable to find files that
are referenced by other roles.

Generalize references to files in other roles

---

roles/neutron-data-network/tasks/main.yml

When we are using vxlan in unicast mode via l2pop, we do not need to run
an IGMP router using xorp.

No IGMP with l2pop

---

roles/novnc/tasks/main.yml

Removed incorrect adding of firewall rule (did not point to an existing variable). The rule was also a duplicate, and can be found in roles/nova-common/tasks/novnc.yml line 34.
https://github.com/blueboxgroup/ursula/blob/master/roles/nova-control/tasks/novnc.yml#L33

Removed incorrect adding of firewall rule

---

Vagrantfile

No one uses "workstation", so kill it.

Remove unused workstation deploy type

---

roles/common/tasks/monitoring.yml
roles/percona-backup/tasks/main.yml
roles/percona-backup/tasks/monitoring.yml

Being in the common role means that every node that doesn't have the percona-backup role will falsely alert on this.

move percona check to correct role

---

roles/ceph-common/defaults/main.yml
roles/cinder-common/tasks/ceph_integration.yml
roles/glance/tasks/ceph_integration.yml

Squash the rbd and rados fetch blocks and extract the download urls so
that they can be overridden in openstack-envs based on the environment
being deployed.

Make rbd and rados locations overridable

---

roles/common/tasks/monitoring.yml
roles/percona-backup/tasks/main.yml
roles/percona-backup/tasks/monitoring.yml

Being in the common role means that every node that doesn't have the percona-backup role will falsely alert on this.

backport - move percona check to correct role

---

roles/percona-backup/templates/percona-xtrabackup.sh

Fix the template to avoid a new line before shebang. The run-parts command is failing to execute this for this.

Fix percona backup template to avoid new line before shebang

---

roles/rabbitmq/defaults/main.yml
roles/rabbitmq/tasks/monitoring.yml

Increased thresholds for rabbitmq-numqueues check to cluster_node_count\*60 for warning and cluster_node_count\*120 for critical

Increased thresholds for rabbitmq-numqueues check

---

roles/common/tasks/ssl.yml

This provides a way to add additional CA certificates to the system
store from an environment file. This can be useful for custom mirrors or
using a non-default CA certificate as an endpoint.

A way to install additional CA certificates

---

roles/apt-repos/defaults/main.yml

The default uri for this repo in the apt-repos role does not exist. This
was updated in envs/example/defaults-2.0.yml so CI passes, but not in
our role default.

Make the bbg_ubuntu default repo uris match CI

---

site.yml

A number of tasks were failing to download things because the
required proxy settings needed in production deployments were not
being exported to the environment.

Add missing environment exports

---

roles/neutron-data-network/tasks/main.yml

On some ubuntu images resolvconf is not installed so ensure that it is
before calling it.

Ensure resolvconf is installed

---

playbooks/ci-allinone/tasks/pre-deploy.yml
playbooks/ci-full/tasks/pre-deploy.yml

No need to upgrade the kernel to the backport of the Trusty kernel if we are
already deploying on Trusty.

pre-deploy: remove unnecessary kernel upgrade

---

envs/example/defaults-2.0.yml
roles/openstack-setup/tasks/images.yml

Glance does not know how to proxy `copy-from` URLs.  To workaround this
issue we simply download the images locally and then create glance
images using the `file` method.

Stop using "copy-from" to load glance images

---

roles/endpoints/defaults/main.yml
roles/haproxy/templates/etc/haproxy/haproxy_openstack.cfg
roles/haproxy/templates/etc/haproxy/haproxy_swift.cfg

Allowing round-robin mode for nova and keystone in haproxy to support higher number of concurrent VM deployments.

Switch to "round-robin" mode for nova and keystone in haproxy

---

roles/common/tasks/networking.yml

Don't run the hosts template if etc_hosts are not defined.

Only install hosts file when etc_hosts defined

---

roles/ceilometer-control/tasks/main.yml
roles/cinder-control/tasks/main.yml
roles/common/tasks/main.yml
roles/glance/tasks/main.yml
roles/heat/tasks/main.yml
roles/horizon/tasks/main.yml
roles/ironic-control/tasks/main.yml
roles/keystone/tasks/main.yml
roles/magnum/tasks/main.yml
roles/neutron-control/tasks/main.yml
roles/neutron-data/tasks/main.yml
roles/nova-control/tasks/main.yml
roles/nova-control/tasks/novnc.yml
roles/swift-proxy/tasks/main.yml

Tag all ufw operations so they can be ran independently. This was needed only because i made a mistake but it may still be useful to others.

Add a ufw tag to all ufw commands

---

roles/common/defaults/main.yml

This is a required variable in the common role

Add default value for gem-sources

---

envs/example/defaults-2.0.yml
envs/example/mirrors/group_vars/all.yml
roles/common/defaults/main.yml

Very little should be changing in ursula-monitoring for the 2.0.x point
releases, just point to the tag.

Pin ursula-monitoring to the 2.0.0 tag

---

roles/cinder-common/tasks/ceph_integration.yml

There is an unneeded space is ceph_integration.yml that will throw `msg: this module requires key=value arguments` errors when deploying cinder on package installs.

Fix syntax in ceph_integration.yml

---

envs/example/defaults-2.0.yml
roles/cinder-common/defaults/main.yml

Previously reviewed by JLK; will backport to 2.0 once checks pass

Disables cinder vg in role and enables in example for CI

---

roles/openstack-package/tasks/main.yml
roles/openstack-source/tasks/main.yml

If an operator passes "-e upgrade=true", then the symlink task will
trigger.
Also update tasks I'm touching to the desired format, and use the stat
module to check the link status.
(cherry picked from commit 40e7f8b8741ef9728e01564cf95443c7ac863e90)

Ensure the symlink target also on upgrade (2.0.x)

---

roles/client/templates/root/stackrc

When using predefined certificates any client operations that are
performed on a client installed inside a virtualenv and so requests
doesn't acknowledge the installed system CA. This fails particularly in
the case of heat-keystone-setup-domain where it doesn't follow the
system CA.
We could fix this purely for the heat case however everything relying
upon the stackrc file will have this same problem so add the system CA
there.

Add system CA to stackrc

---

roles/neutron-common/meta/main.yml

python_requirements does not appear to be used anywhere with the
variable being python_dependencies. Having this left around makes it
confusing.

Remove old python_requirements variable

---

site.yml

`site.yml` should use `env_vars` for ALL role executions in the playbook... or you're gonna have a bad time.

site: all roles need env_vars used

---

roles/common/meta/main.yml

No sense in continuing to use precise.

Use trusty hwraid when on trusty

---

roles/swift-ring/handlers/main.yml
roles/swift-ring/tasks/main.yml

Once https://github.com/blueboxgroup/swifttool/pull/8 is merged, swifttool would support modifying existing rings by adding/removing devices in current ring.
When the weights don't change, it will set weights to previous weights. However, this operation will not cause any data to reassign.

Always bootstrap rings for scaling support

---

roles/keystone/meta/main.yml
site.yml

This is going to be removed in favor of implicit calls
via role dependencies.

Remove the explicit call to the serverspec role

---

roles/keystone/tasks/main.yml

The openstack-package role defines virtualenv_base differently than
openstack_source, so we need a lookup to deep resolve variables.

Use a lookup to resolve a variable within a var

---

roles/nova-common/defaults/main.yml

DiskFilter prevents trying a build on a system without sufficient disk
space.
AggregateInstanceExtraSpecsFilter allows creating flavors with extra
specs and maping those flavors to host aggregates that have those extra
specs.
(cherry picked from commit 8ec2decc1a7bcbe52ee25751569b7b282268465f)

Add a couple missing useful schedule filters (2.0.x)

---

roles/common/tasks/monitoring.yml

(cherry picked from commit a4c084a906680ccf1e0e8ae5b42a14c4d92aba40)

Remove deprecated network monitoring check (2.0.x)

---

roles/swift-common/defaults/main.yml
roles/swift-common/templates/etc/rsyncd.conf

2 rsync connections for object/containers is relatively low. Setting the values according to https://github.com/openstack/swift/blob/master/etc/rsyncd.conf-sample which seems to work well during testing.

Increase number of rsync connections for object and container

---

roles/swift-account/defaults/main.yml
roles/swift-account/templates/etc/swift/account-server.conf
roles/swift-common/defaults/main.yml
roles/swift-container/defaults/main.yml
roles/swift-container/templates/etc/swift/container-server.conf
roles/swift-object/defaults/main.yml
roles/swift-object/templates/etc/swift/object-server.conf
roles/swift-proxy/defaults/main.yml

Deployment guide: http://docs.openstack.org/developer/swift/deployment_guide.html. During developer testing, these value solved the problems related to too many processes trying to access resource leading to EADDRNOTAVAIL errors.

Set the concurrency level as per recommendation by deployment guide

---

roles/nova-common/defaults/main.yml

DiskFilter prevents trying a build on a system without sufficient disk
space.
AggregateInstanceExtraSpecsFilter allows creating flavors with extra
specs and maping those flavors to host aggregates that have those extra
specs.

Add a couple missing useful schedule filters

---

roles/common/defaults/main.yml
roles/common/tasks/kernel-tuning.yml
roles/common/tasks/main.yml

When deploying ursula to SoftLayer virtual servers it was discovered that the
/etc/default/grub file did not exist and there was no serial console on the
virtual servers. The changes made in this commit allowed the ursula deploy
to proceed.

Added defaults for grub and serial_console

---

playbooks/ci-allinone/vars/main.yml
playbooks/ci-full/vars/main.yml

This bit was missed when we changed the endpoint ports.

Fixup CI security groups for new endpoint ports

---

roles/nova-common/templates/etc/nova/policy.json

(cherry picked from commit 8fd57fcf2b9ab301fd8dedce1787075181f5a846)

Disallow cloud_admin role to access host aggregates (2.0.x)

---

envs/example/defaults-2.0.yml
roles/openstack-setup/tasks/images.yml

Glance does not know how to proxy `copy-from` URLs.  To workaround this
issue we simply download the images locally and then create glance
images using the `file` method.
(cherry picked from commit 3b8b07d19d37389327e42fe4095d659763a72a32)

Stop using "copy-from" to load glance images (2.0.x)

---

roles/ceilometer-control/tasks/main.yml
roles/ceilometer-data/tasks/main.yml
roles/cinder-control/tasks/main.yml
roles/cinder-data/tasks/main.yml
roles/glance/tasks/main.yml
roles/heat/tasks/main.yml
roles/horizon/tasks/main.yml
roles/ironic-control/tasks/main.yml
roles/keystone/tasks/main.yml
roles/magnum/tasks/main.yml
roles/neutron-control/tasks/main.yml
roles/neutron-data-network/tasks/main.yml
roles/neutron-data/tasks/main.yml
roles/nova-control/tasks/main.yml
roles/nova-data/tasks/main.yml
roles/openstack-package/tasks/main.yml
roles/swift-account/tasks/main.yml
roles/swift-container/tasks/main.yml
roles/swift-object/tasks/main.yml
roles/swift-proxy/tasks/main.yml

If we change the package or the git repo we want to restart the
services. Currently this also depends on 'upgrade' being set to True.

Trigger service restarts on openstack code change

---

envs/example/defaults-2.0.yml

It's under a lot of pressure and needs some time off to sort through its
life.
(cherry picked from commit 116031a893a33fb502d09003550ee41cfec9e39e)

Stop using bluebox gem mirror for now (2.0.x)

---

roles/horizon/templates/etc/openstack-dashboard/local_settings.py

Update help_url so that horizon help link points to kilo docs.

update help_url to kilo

---

roles/ceph-common/defaults/main.yml
roles/ceph-common/handlers/main.yml
roles/ceph-update/tasks/main.yml
site.yml

Adding a new role that restarts the ceph services in a serialized manner after ceph expansion. The `noout`, `noscrub` and `nodeep-scrub` options are set when restarting ceph osd nodes in order to minimize the downfall in performance metrics observed in the ceph cluster. Those options are then unset after ceph services on _all_ of the osd nodes are restarted for the same reason above. Also updating the sync_interval field for `ceph.conf`.

update role for ceph scaleout

---

roles/horizon/tasks/main.yml

When updating a cluster, get_url would skip replacing the updated logo image as logo.png was already present. Given, we always copy the custom logo image to dest as fixed file name (logo,png) we must enforce force copy on get_url.

Enable force copy for custom horizon logo images

---

ansible.cfg

Simple change, profound effect. (In the midst of trouble-shooting, at least.)

ansible.cfg: set log_path for easier debugging

---

roles/mongodb-common/meta/main.yml

mongodb-common needs to pull in the endpoints role as a result of defaults-2.0.yml cleanup. Without it, ursula will throw undefined variable errors when installing mongodb config files, as it will not have the endpoint defined.

add endpoints role as dependency to mongodb-common

---

roles/logging-config/handlers/main.yml
roles/logging-config/meta/main.yml
roles/logging-config/tasks/main.yml
site.yml

Split the `logging` role from being a dependency of the `logging-config` role just to pick up a directory and  handler. This will speed up end-to-end deployments due to keeping the `logging` role from being run by every role which uses the `logging-config` role.

logging: split logging from logging-config deps

---

roles/common/tasks/kernel-tuning.yml

Backport of https://github.com/blueboxgroup/ursula/pull/1580 to prevent crash kernel from being loaded after kernel panics.

disable crash kernel in grub config

---

roles/common/tasks/monitoring.yml

service: name=sensu-client state=started enabled=yes does not properly create symlink in /etc/rc_x_.d

Force enable sensu-client

---

envs/example/defaults-2.0.yml

Enables admin and cloud_admin user to able to deploy heat stack out of the box.
In addition, we are no longer going to create project_admin user as cloud_admin can create once then have been on-boarded.

Grant admin and cloud_admin heat_stack_owner role

---

roles/rabbitmq/templates/etc/serverspec/rabbitmq_spec.rb

Fixing the error on rabbitmq serverspec by including the host name in the output.

Fixing defect 119584 for rabbitmq serverspec

---

envs/example/defaults-2.0.yml

Reverts blueboxgroup/ursula#1678
The project_admin role is getting created when we are assigning project_admin user a project_admin role. Need to fix this dependency before removing logic to create project_admin user.

Revert "Grant admin and cloud_admin heat_stack_owner role"

---

envs/example/standard/hosts

Changing up the host group names to keep the naming standard for OSD types constant with the BOM documents. This was reviewed and confirmed with Sam Cooper as well.

changing host names to match BOM notation

---

doc/dev-test.md
doc/ironic.md
doc/vagrant.md

Documentation in doc/ showed examples using:
`ursula --vagarant environment playbook`
Since --vagrant is deprecated, documentation now shows:
`ursula --provisioner=vagarant environment playbook`
Signed-off-by: Matt Langbehn <matthew.langbehn@gmail.com>

Updated documentation on working in vagrant

---

envs/example/defaults-2.0.yml

Enable cloud_admin and admin user to able to deploy heat stack out of the box.

Grant cloud_admin and admin user heat_stack_onwer role

---

roles/keystone-setup/tasks/main.yml
site.yml

`keystone-setup` was previously running on each iteration due to:
1. var registration was happening in-role _after_ the var was evaluated; now done in pre_tasks to ensure it evaluates before, not after
2. parameterized variable (`keystone_configured: false`) being passed into role, not needed anymore
3. var when checked was evaluating false, so be more explicit (`keystone_configured` vs `hostvars[inventory_hostname].keystone_configured`)
4. use a default to be ultra clear that we by default assume keystone to be unconfigured, unless checks indicate otherwise

fix keystone-setup checks so that it runs once

---

envs/example/defaults-2.0.yml
roles/keystone-defaults/defaults/main.yml
roles/keystone-setup/tasks/main.yml

cloud_admin user has enough authority to create a project_admin user for the out of the box "demo" tenant. This PR is removing out the box creation of the project_admin user to ease the customer onboarding.

Do not create default project_admin user for demo tenant

---

plugins/vars/default_vars.py

Ansible now provides the ability to gather group vars or host vars.  However, for backwards
compatibility they still provide both via `run`.  Given this plugin's use case, we want both.
This change is backwards compatible with Ansible 1.9 stable.

Updated vars plugin to support Ansible 2.0

---

library/os_nova_host_agg.py
library/os_nova_host_agg_host.py

These two new modules can be used to add / remove host aggregates and add / remove hosts within those aggregates.
Functionality for host aggregates doesn't exist natively within shade yet, so these call through to the nova_client object within shade. Work will progress upstream to make this native within shade, and then as upstream modules in Ansible.

Adding modules to deal with host aggregates

---

envs/example/ci/group_vars/compute.yml
roles/nova-common/defaults/main.yml
roles/nova-common/templates/etc/nova/nova.conf
roles/openstack-setup/tasks/computes.yml
roles/openstack-setup/tasks/main.yml
test/setup

Every compute node will define a type, which will be turned into a host
aggregate, that is exposed as an Availability Zone. A default
availability zone will be set based on the type of cluster being
deployed, or default to "nova".

[WIP] Set up host aggregate/AZs based on compute types

---

roles/ceph-common/meta/main.yml
site.yml

On Power we are able to pull the ceph packages directly from Ubuntu.

Install the ceph repo only on x86

---

roles/keystone/tasks/logging.yml

add copytruncate command to log rotation. 
if in the future this turns out to be problematic or undesireable, use https://uwsgi-docs.readthedocs.org/en/latest/MasterFIFO.html instead w/ postrotate

fix keystone uwsgi logrotate

---

roles/client/defaults/main.yml

When both heat client and ironic client are >=0.9.0 they pull in a new nova client which has issues with api version discovery in kilo.

Pin ironic/heat client versions

---

roles/ceph-osd/tasks/bcache.yml

Add wait_for task for bcache directory to be created before running next task. This will ensure /sys/block/bcacheX directory is present before writing into bcache/cache_mode file in that directory.

Add wait_for task for bcache directory to be created

---

plugins/callbacks/fail_on_unreachable.py

In 1.9, particularly in gather_facts, an unreachable host doesn't count
as a failed host for any_errors_fatal type settings. So this callback
will trigger when a host is unreachable and just truncate the play hosts
to an empty set, which will abort the play on the very next task.

Add a callback to fail on unreachable hosts

---

roles/neutron-common/defaults/main.yml
roles/neutron-common/meta/main.yml

Which has backported fixes that upstream will not take (due to kilo
being security fixes only now)

Use our fork of neutron

---

site.yml

Setting serial: 1 for ceph_osd role to ensure successful deploy of hybrid ceph cluster

setting serial for ceph_osd role 

---

roles/horizon/meta/main.yml

Good thing keystone-defaults is a info only role. Add that dep in.

Horizon config relies on keystone details

---

roles/glance/defaults/main.yml
roles/glance/templates/etc/glance/glance-api.conf

When using http location where url contains the query string, glance-store http driver is cutting out the querystring when making the request to download the image.
This PR will point glance-store to extended bbchttp driver that will retain the queryparameter.

WIP: Extend glance-store http location driver to retain uri  querystring

---

roles/rabbitmq/templates/etc/serverspec/rabbitmq_spec.rb

We were getting a false positive because the should match
paradigm uses regular expressions (who would have guessed)
We need it to match the expression exactly, so we threw parens
around the string.

Fix rabbitmq serverspec false positive

---

roles/common/templates/etc/serverspec/os_spec.rb

Ceph and Swift nodes do not have a /backup/ directory. It should not
therefore complain if it doesn't exist, but if it does exist, it should
check for the appropriate mode, etc.

Fix false positive serverspec checks on Swift and Ceph Nodes

---

roles/current_symlink/tasks/main.yml
roles/openstack-package/tasks/main.yml
roles/openstack-source/tasks/main.yml
site.yml

This allows having one package updated and restarted without disrupting
other packages while in an upgrade. NOT INTENDED FOR MIXED VERSIONS
OUTSIDE OF UPGRADES!
Also attempts to migrate an existing current symlink into the individual
symlinks based on the current target.

Use individual project symlinks for current

---

roles/keystone/tasks/main.yml

Don't want to drop a serverspec file for keystone if serverspec is turned off.

Check for serverspec flag in keystone

---

roles/ceph-common/defaults/main.yml

This package is un-needed on the ceph node and will turn on IP forwarding if it is running.

Remove libvirt-bin from the installed pkgs in ceph-common

---

roles/neutron-common/defaults/main.yml

There are 2 lists (?)
This is due to a potential bug with neutron-client not using the venv pip setup in /opt/openstack like everything else

Add neutron to etc alternatives

---

roles/swift-common/templates/etc/rsyncd.conf

Per rsync documentation: For pid file, do not use /var/run/rsync.pid if you are going to run rsync out of the init.d script. The init.d script does its own pid file handling, so omit the "pid file" line completely in that case.

No need to specify pid file when using init.d to start rsync

---

roles/swift-common/templates/etc/rsyncd.conf

(cherry picked from commit b721967347807c813d242479b69213789f23444e)

No need to specify pid file when using init.d to start rsync (2.0.x)

---

roles/common/tasks/kernel-tuning.yml
roles/nova-data/tasks/main.yml

First, there should be a space between smt-enabled and any other
kernel parameters. Second, even if this is incorrect, ensure that
we disable SMT at runtime.
Also, needs backport to 2.0.1

Fix smt-enabled flag and optimize SMT at runtime

---

roles/haproxy/handlers/main.yml
roles/haproxy/tasks/main.yml

This ensures that haproxy logging goes where the config file it lays
down says to go (/var/log/haproxy.log)

Restart rsyslog on haproxy install

---

roles/common/tasks/main.yml
roles/common/tasks/system-tools.yml

prevent hwraid and mcelog from attempting install on ppc64el arch

2.0.ppc fixes for hwraid and mcelog

---

roles/rabbitmq/templates/etc/serverspec/rabbitmq_spec.rb

I forgot to remove this last night when I made those one-liner changes.

Remove un-needed socket require in rabbitmq spec

---

roles/swift-ring/tasks/main.yml

swift-dispersion-populate is not being run automatically causing the swift-dispersion check to fail out of the box, /etc/sensu/plugins/check-swift-dispersion.sh

Run swift populate first time we deploy rings

---

roles/cinder-common/handlers/main.yml
roles/cinder-data/tasks/main.yml

When using a common host name for shared backend scenarios (like ceph),
starting two services at once with the same name can lead to a race
condition. We want to serialize at least the initial start up of the
service, but since that could be via a handler OR the role task we need
to serialize both.

Serialize cinder service (re)starts

---

site.yml

We need info from every host, for ansible_nodename.

Gather facts forcefully on openstack-setup

---

roles/ceilometer-common/templates/etc/serverspec/ceilometer_spec.rb

The process checked for by the ceilometer serverspec only exist
on controller nodes. We should only drop those checks on the node
ceilometer role is being run on if it is in the controller group.

Check ceilometer process on controller nodes only

---

library/ceph_bcache.py
roles/ceph-common/defaults/main.yml
roles/ceph-common/templates/etc/ceph/ceph.conf

- /etc/fstab entry matching osd mount options in ceph.conf
- Adding tcp rcvbuff parameter in ceph.conf to resolve performance issues.

ceph conf tcp parameter and fstab option

---

roles/swift-common/handlers/main.yml

Adding retry logic since service fails with following error: failed to create pid file /var/run/rsyncd.pid. It seems like timing issue

Add retry logic to rsync restart

---

roles/keystone/templates/etc/apache2/sites-available/keystone.conf

The OIDC claims sent from the OP were being truncated. Not all headers were being setup in the context for a request. This caused the SSO to fail.

Federation: Increase the uWSGI max vars to accomodate the oidc claims

---

roles/openstack-setup/tasks/dispersion.yml
roles/openstack-setup/tasks/main.yml
roles/openstack-setup/tasks/users.yml
roles/swift-ring/tasks/main.yml

Ideally openstack-setup will only be run once. Adding extra guard around dispersion run that it is only run when services are first created

Run dispersion as part of openstack-setup

---

roles/nova-common/defaults/main.yml
roles/nova-common/meta/main.yml

This is needed to fix a nova <-> cinder interaction with availability
zones.

Fork and use our nova kilo branch

---

roles/common/templates/etc/serverspec/os_spec.rb

Logrotate is rotating /var/log/wtmp to 664 from what we set it to 755. This serverspec change allows /var/log/wtmp to be 664.

Logrotate changes the permissions on /var/log/wtmp

---

envs/example/defaults-2.0.yml

While trying to split the roles logging and logging-config
we accidentally broke the allinone build process. This PR
will be a quick fix until we can get a more proper role
separation.

Add logging.follow to defaults-2.0

---

envs/example/defaults-2.0.yml

follow-up to #1782, it looks like `logging` is redefined further down the line, which was un-setting the fix applied in #1784 (wtf yaml). i'm fairly new to ansible, so not 100% on this, but it seems to have gotten me past the earlier error, though my initial bootstrap is still in progress, so there may be other issues :smile_cat:

fix issue 1782

---

roles/endpoints/defaults/main.yml
roles/haproxy/templates/etc/haproxy/haproxy_openstack.cfg

For the keystone the haproxy is set to the balancing scheme is set to round robin. During the OpenID connect handshake, the OP redirects back to the keystone URI. As the round robin scheme is setup on the haproxy for the keystone endpoint, the redirect may end up on the keystone instance (apache) from which the initial request did not originate. This could end up being redirected indefinitely. The cookie check added with this change makes the haproxy send the keystone redirect from the OP to the correct keystone endpoint. This makes it stick only for the OIDC handshake. API calls continue to be serviced in a round robin fashion.

Fix OpenID Connect handshake redirection issue

---

roles/common/defaults/main.yml
test/setup

Now that https://github.com/pypa/pip/issues/3384 has been resolved we
can use the latest version.

Upgrade deployments to pip 8.0.2

---

roles/ceilometer-common/defaults/main.yml
roles/ceilometer-common/tasks/main.yml
roles/ceilometer-common/templates/etc/ceilometer/api_paste.ini
roles/ceilometer-common/templates/etc/ceilometer/ceilometer.conf
roles/ceilometer-common/templates/etc/ceilometer/ceilometer_api_audit_map.conf
roles/cinder-common/defaults/main.yml
roles/cinder-common/templates/etc/cinder/api-paste.ini
roles/cinder-common/templates/etc/cinder/cinder.conf
roles/cinder-common/templates/etc/cinder/cinder_api_audit_map.conf
roles/glance/defaults/main.yml
roles/glance/templates/etc/glance/glance-api-paste.ini
roles/glance/templates/etc/glance/glance-api.conf
roles/glance/templates/etc/glance/glance_api_audit_map.conf
roles/heat/defaults/main.yml
roles/heat/tasks/main.yml
roles/heat/templates/etc/heat/api-paste.ini
roles/heat/templates/etc/heat/heat.conf
roles/heat/templates/etc/heat/heat_api_audit_map.conf
roles/neutron-common/defaults/main.yml
roles/neutron-common/templates/etc/neutron/api-paste.ini
roles/neutron-common/templates/etc/neutron/neutron.conf
roles/neutron-common/templates/etc/neutron/neutron_api_audit_map.conf
roles/nova-common/defaults/main.yml
roles/nova-common/templates/etc/nova/api-paste.ini
roles/nova-common/templates/etc/nova/nova.conf
roles/nova-common/templates/etc/nova/nova_api_audit_map.conf

The pyCADF middleware will be enabled by default to have audit events logged
in the API logs for the following services:
ceilometer, cinder, glance, heat, neutron, and nova

Add the audit pyCADF middleware for audit logging

---

playbooks/ci-full/tasks/create.yml
test/setup

Because the test VMs share a private subnet with the Jenkins server, we
do not need to access them using public IP addresses.

Use private IPs only for CI

---

envs/example/defaults-2.0.yml
roles/keystone-defaults/defaults/main.yml
roles/keystone-setup/tasks/main.yml
roles/keystone/templates/etc/keystone/keystone-paste.ini
site.yml

This obviates the need for admin_token usage, which we've never liked. It also removes a keystone service restart when doing the boot strapping. Everything is nice and idemotent.
This cherry picks (with modifications) a few commits that were used to implement this from another dev team.

Use keystone-manage to bootstrap a cloud

---

roles/heat/tasks/main.yml
upgrade.yml

Suprisingly little had to chance. Removal of a bunch of no longer needed
upgrade bits, and re-ordering of services, and adding forced fact
gathering in a few places.
Also a failed_when conditional in Heat had to be updated as the old
keystone output didn't match the new keystone output.

Update upgrade playbook for kilo -> mitaka

---

roles/swift-common/defaults/main.yml
roles/swift-common/meta/main.yml

Swift deploy failed since it required setuptools  > 17 http://docs.openstack.org/developer/pbr/compatibility.html#evaluate-marker
Also adding erasurecode dependency

Changes to build swift mitaka from source

---

roles/cinder-common/tasks/ceph_integration.yml
roles/glance/tasks/ceph_integration.yml
roles/keystone/tasks/main.yml
roles/neutron-common/templates/etc/neutron/rootwrap-ursula.d/ursula.filters

This double lookup doesn't seem to be a problem with Ansible 2.0, but
the use of the lookup function was breaking things, so take it out.

Remove use of lookup for finding virtualenvbase

---

roles/ceilometer-common/defaults/main.yml
roles/ceilometer-common/handlers/main.yml
roles/ceilometer-common/templates/etc/ceilometer/ceilometer.conf
roles/ceilometer-common/templates/etc/serverspec/ceilometer_spec.rb
roles/ceilometer-control/tasks/main.yml
roles/ceilometer-control/tasks/monitoring.yml
roles/ceilometer-data/tasks/main.yml
roles/ceilometer-data/tasks/monitoring.yml

Lots of change from Kilo -> Mitaka
Alarms were split off to aodh
Auth stuff changed syntax
Mongo module needs auth creds to add non-admin user
New polling service replaces some agents services
With all these changes, the services appear to run, but doing anything
useful with them may require more changes.

Make ceilometer work again

---

roles/ceilometer-control/tasks/monitoring.yml
roles/ceilometer-data/tasks/monitoring.yml

These services no longer exist, stop monitoring them.

Purge outdated ceilometer alerts

---

roles/endpoints/defaults/main.yml
roles/glance/templates/etc/glance/glance-api-paste.ini
roles/glance/templates/etc/glance/glance-registry-paste.ini

This provides a lighter way to see if glance is up and running.

Use healtcheck middleware for Glance

---

roles/nova-data/tasks/ssh.yml

The symlink task currently fails when the file exists and it is not already a symlink due to missing the force option.
Opting to template twice rather than the force the link so that root's known_hosts aren't forever determined by the nova user.

template root known hosts rather than symlink

---

roles/nova-data/tasks/ssh.yml

(cherry picked from commit 4a6ef9fc1fcfc112ca0ea35c446bd173cd71284b)

template root known hosts rather than symlink (2.1.x)

---

roles/keystone-setup/handlers/main.yml
roles/keystone-setup/tasks/federation.yml

This is to get around the keystone bootstrap failure when the "federated_domain_name = Default" is set in the keystone config file. This is needed so that horizon is scoped to the default domain after the oidc authentication with the BoxPanel auth

Changes to oidc keystone federation setup fo mitaka

---

roles/nova-common/templates/etc/nova/nova.conf

The ansible_processor_vcpus fact has been found to detect the incorrect number of available cpus.  Moving to ansible_processor instead.

use ansible_processor fact in place of ansible_processor_vcpus

---

playbooks/ci-full/tasks/create.yml
test/common

Test VMs running into the new CI cloud will need to boot in a specific
availability zone.

Add the ability to specify availability zone

---

roles/nova-common/templates/etc/nova/api-paste.ini

This is new oslo middleware to automatically translate from an http(s)
proxy to the wsgi application so that all the right references get sent
back. This replaces the one-off handling of the HTTPS proxy header.
This is just for nova to prove the model, before applying to all
services.
https://review.openstack.org/#/c/227868/4

Introduce oslo middleware for http proxy (nova)

---

roles/nova-common/templates/etc/nova/nova.conf

novnc should only be turned on (if configured to be on) on compute nodes
only. The upstream default value has changed to default to enabled, so
we have to explictly turn it off.

Enforce novnc off on dedicated controllers

---

roles/ceph-osd/tasks/bcache.yml

Backporting https://github.com/blueboxgroup/ursula/pull/1798 to RELEASE-2.1.x

add "udevadm trigger" invocation to discover new bcache devices

---

roles/horizon/defaults/main.yml
roles/horizon/tasks/main.yml
roles/horizon/templates/etc/openstack-dashboard/local_settings.py

Having CSRF issues with horizons nextgen panel, enabling legacy panel by default until that is resolved.

Disable horizon next gen panel

---

roles/horizon/defaults/main.yml
roles/horizon/templates/etc/openstack-dashboard/local_settings.py

By default the session engine used is signed cookies.
This changes the default to use the cache session engine and
makes the option configurable.
This patch relates to the security note:
https://wiki.openstack.org/wiki/OSSN/OSSN-0017
The security note refers to a vulnerability back in icehouse. When a user logged out, horizon invalidated the session but did not send a request to keystone to invalidate the token (which was stored inside the cookie). This has been fixed here: https://github.com/openstack/django_openstack_auth/commit/cad8def073222618857bebf9a18bb4d8dd098bfc
Although the bug has been fixed, the token is still available to anyone who has access to the local token (cookie in the browser) or who have stolen it in transit (Non TLS). Using the cache session engine prevents the …

Make default horizon session engine to use cache backend

---

roles/cinder-common/defaults/main.yml
roles/cinder-common/templates/etc/cinder/cinder.conf

This config option allows cinder volumes to be created in default availability zone (nova) when cinder doesn't have an az equal to compute's az.  This config option is introduced in Liberty release.
upstream defect: https://review.openstack.org/#/c/217857/

Adding allow_availability_zone_fallback option to cinder.conf

---

roles/nova-data/tasks/libvirt.yml
roles/nova-data/templates/etc/machine-id

This does two things:
1) Ensure a uuid exists in /etc/machine-id
2) Write value from machine-id into libvirt config as host_uuid
host_uuid should always be unique, as it's used to validate a live
migration target.
Nova exposes to the guest some information about the host, including the
uuid. The nova default is to read /etc/machine-id and fallback to what
libvirt shows. Since we need to store a generated uuid somewhere, we're
picking /etc/machine-id for this storage.

Generate our own host uuid for libvirt

---

roles/nova-data/tasks/ssh.yml

Some hosts wound up with a symlink instead of a file, and template will
change permissions on the symlink target, which is not good.

Handle known_hosts symlink (2.1.x)

---

roles/nova-common/templates/etc/nova/nova.conf
roles/nova-control/tasks/main.yml
roles/nova-control/tasks/novnc.yml
upgrade.yml

Found that we weren't passing env details into the upgrade roles
Fixed up confusion about novncproxy and where it should run
Caught a regression with vnc keymap.

More upgrade fixes from production run

---

roles/keystone/templates/etc/keystone/keystone.conf

Keystone is running under uwsgi, so setting public_workers or
admin_workers in keystone.conf has no effect and is confusing
since someone might think that changing this value will have
some effect.

Stop setting public/admin_workers in keystone.conf

---

roles/swift-common/templates/etc/init/swift-service.conf

This is causing a very weird traceback on mitaka, and it's not
necessary. swift-init does the right thing anyway.

Drop the & from swift init scripts

---

roles/ceilometer-common/templates/etc/ceilometer/ceilometer.conf
roles/cinder-common/templates/etc/cinder/cinder.conf
roles/glance/templates/etc/glance/glance-api.conf
roles/glance/templates/etc/glance/glance-registry.conf
roles/heat/templates/etc/heat/heat.conf
roles/keystone/templates/etc/keystone/keystone.conf
roles/neutron-common/templates/etc/neutron/neutron.conf
roles/nova-common/templates/etc/nova/nova.conf

In master branch of oslo.middleware, by default proxy header parsing
is disabled. We need to enable is respective openstack api conf files.

Enable proxy header parsing in oslo_middleware.http_proxy_to_wsgi

---

roles/nova-common/defaults/main.yml
roles/nova-common/templates/etc/nova/nova.conf
test/setup

Turns out that if nothing is specified, the scheduler will just toss it
at any available compute and not try to filter by AZ. This is most
likely what we want for our stacks.
However we do want to retain the ability for for a site to override the
default, which can be done in site config.

Remove default availability zone settings

---

library/keystone_federation_mapping.py
library/keystone_service_provider.py
roles/horizon/templates/etc/openstack-dashboard/local_settings.py
roles/keystone-defaults/defaults/main.yml
roles/keystone-setup/tasks/federation.yml
roles/keystone/handlers/main.yml
roles/keystone/tasks/k2k-idp.yml
roles/keystone/tasks/k2k-sp.yml
roles/keystone/tasks/main.yml
roles/keystone/templates/etc/apache2/sites-available/keystone.conf
roles/keystone/templates/etc/keystone/keystone-saml.crt
roles/keystone/templates/etc/keystone/keystone-saml.pem
roles/keystone/templates/etc/keystone/keystone.conf
roles/keystone/templates/etc/shibboleth/attribute-map.xml
roles/keystone/templates/etc/shibboleth/shibboleth2.xml
roles/keystone/templates/etc/shibboleth/sp-cert.pem
roles/keystone/templates/etc/shibboleth/sp-key.pem

Adds the feature to support keystone to keystone federation.
This feature enables:
1. Setting up keystone as an identity provider (idp) for another keystone
2. Setting up keystone as a service provider (sp) that takes assertions from
a keystone identity provider.
The federation protocol used between the idp and sp is SAML 2.0.
Shibboleth is installed on the sp to process the SAML assertions.
```
To setup a k2k idp, you will need these variables in the all.yml:
keystone:
federation:
enabled: True
idp:
k2k:
enabled: True
service_providers:
- id: k2kf-sp
service_provider_url: https://k2kf-sp.open-test.ibmcloud.com:5000/Shibboleth.sso/SAML2/ECP
service_provider_auth_url: https://k2kf-sp.open-test.ibmcloud.com:5000/v3/OS-FEDERATION/identity_providers/k2kf-idp/protocols/saml2/auth …
```

Keystone to Keystone Federation

---

roles/nova-common/defaults/main.yml
roles/nova-common/templates/etc/nova/nova.conf

This is opinionated for the way we name things, but a site can change
'external' to 'nova' to reflect the upstream default value.

Reintroduce nova default floating pool

---

roles/keystone-defaults/defaults/main.yml
roles/keystone-setup/tasks/federation.yml

The variables for federation should not have example strings and
should have useful default values.
The group, role, mapping, and protocol, federation variables will be moved
into the sp section since they are considered to be variables intended for
service providers.

Clean up federation defaults and move sp variables

---

roles/heat/tasks/main.yml

feedback from tesla:
seems like heat_domain_admin user is not created under heat domain. Also, is missing the description (just a nit)..
clients) ➜  
tesla openstack --insecure domain list
+----------------------------------+---------+---------+--------------------+
| ID                               | Name    | Enabled | Description        |
+----------------------------------+---------+---------+--------------------+
| 9766008e644d481381188681e8c9bb2d | heat    | True    |                    |
| default                          | Default | True    | The default domain |
+----------------------------------+---------+---------+--------------------+
(clients) ➜  
tesla openstack --insecure user show heat_domain_admin
+-----------+----------------------------------+
| Field     | Value …

Revert to cli client from os_user due to os_user not respecting domain field

---

roles/keystone/templates/etc/keystone/keystone.conf

This was added inside the federation if block, so it was not getting
written out on non-federated installs.

Relocate keystone oslo_middleware config

---

roles/openstack-setup/tasks/dispersion.yml
roles/swift-common/tasks/main.yml
roles/swift-object/tasks/main.yml
site.yml

Fixing the bare variables deprecation warnings generated with ansible 2.0.
Also found that dispersion check was not using ansible way to check bools.

Fix deprecation warning and insecure checks, add tags for roles

---

roles/client/defaults/main.yml

This will break things for us if it goes above 3.0.0, such as our old
clients and modules.

Pin keystone client below 3.0.0

---

roles/horizon/defaults/main.yml
roles/horizon/tasks/main.yml
roles/horizon/templates/etc/apache2/mods-enabled/headers.conf

Adding the secure and httponly attributes to horizon cookies was causing CSRF validation failures when using ajax panels. These attributes can be set using django settings. With this fix, I've enabled the next gen instance panel and made the legacy panel disabled by default.

Remove apache cookie manipulation for horizon

---

roles/endpoints/defaults/main.yml
roles/haproxy/templates/etc/haproxy/haproxy_swift.cfg

Increased number of maxconn parameter in haproxy since some of swift connections could persist longer.
Also, roundrobin would distribute requests evenly across all proxy nodes

Update haproxy config to support large clusters

---

envs/example/defaults-2.0.yml
roles/apache/meta/main.yml
test/setup

Let the CI enable logging to logstash since it knows where logs should
be forwarded to and how it should be configured.

Disable logging to logstash by default
